### PR TITLE
[milestone/12.0] Version 12.0

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
PR for version 12.0:
- built on top of `feature/avatar` because that branch already contains many changes
- code for < iOS 13.4 removed, now targeting iOS 13, upgrading to newer APIs where deprecated APIs were used
- PRs merged into this PR:
   - #1162 
      - #1158 
      - #1140 
      - #1136 
      - #1179
      - merge `11.11.0` and `fastlane/enterprise-adhoc` changes from `master`
   - #1194
   - #1195
   - #1196
   - #1198 
   - #1205
   - #1208

## Related Issue
https://github.com/owncloud/ios-app/issues/1221)](https://github.com/owncloud/ios-app/issues/1221

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

## QA

Test plans:

Regression: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2012.0/Regression.md
Spaces: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2012.0/1101_spaces.md
Sharing in sidebar: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2012.0/Sharing-oCIS.md

(need merging)

Reports:
 
- [ ] (1) [LOW] Soft keyboard over the results https://github.com/owncloud/ios-app/pull/1095#issuecomment-1559068546
- [X] (2) [HIGH] Reopening shows empty list of accounts https://github.com/owncloud/ios-app/pull/1095#issuecomment-1559088422 [FIXED]
- [x] (3) [LOW] Small indentation issue https://github.com/owncloud/ios-app/pull/1095#issue-1112888644 [FIXED]
- [x] (4) [MED] Open links on folder does not open the folder https://github.com/owncloud/ios-app/pull/1095#issuecomment-1573975815 [FIXED]
- [ ] (5) [MED] Download instead of streaming -> black screen https://github.com/owncloud/ios-app/pull/1095#issuecomment-1576610804
- [x] (6) [LOW] Clipboard notification missing https://github.com/owncloud/ios-app/pull/1095#issuecomment-1576729845 [FIXED]
- [ ] (7) [LOW] Full screen mode does not work properly https://github.com/owncloud/ios-app/pull/1095#issuecomment-1578169428
- [x] (8) [LOW] Create folder icon repeated in share sheet https://github.com/owncloud/ios-app/pull/1095#issuecomment-1578652215 [FIXED]
- [ ] (9) [MED] Offline indicator not gone after re-atuhenticate https://github.com/owncloud/ios-app/pull/1095#issuecomment-1578991305
- [x] (10) [HIGH] Delete option missing in shared items inside an space https://github.com/owncloud/ios-app/pull/1095#issuecomment-1580134555 [FIXED]
- [x] (11) [MED] File not saved if created with a 3rd-party-app https://github.com/owncloud/ios-app/pull/1095#issuecomment-1580209778 [FIXED]
- [ ] (12) [LOW] Sharing option duplicated in Files App https://github.com/owncloud/ios-app/pull/1095#issuecomment-1580259507
- [x] (13) [HIGH] Incorrect list in Files app with the shared items https://github.com/owncloud/ios-app/pull/1095#issuecomment-1584137139 [FIXED]
- [x] (14) [LOW] Theme mapping https://github.com/owncloud/ios-app/pull/1095#issuecomment-1584162872 [FIXED]
- [x] (15) [MED] Paste option in space does nothing https://github.com/owncloud/ios-app/pull/1095#issuecomment-1584325667 [FIXED]

### CODE REVIEW

**Comment by jesmrec** [comment]
For this 12.0 branch, test will be done over all the content that's already merged into. Specific features like application provider or new search experience will be tested in the scope of their branches, unless they are merged into 12.0 as well.

I will set an index in the top message with all the QA reports, part of them moved from [here](https://github.com/owncloud/ios-app/pull/1101).

**Comment by jesmrec** [comment]
### (1) (improvement)

1. Login in an oCIS account with no spaces available

Current: List of available spaces is displayed. Only the personal account is there.
Suggestion: in case there is only one item in the list, jump directly to the file list, as in regular accounts

iPhone 13 iOS16
`c98dab89`

**Comment by jesmrec** [comment]
### (2)

1. Set Dark theme
2. Open a space with few items (~2,3)

Current: background is white

Screenshot 2022-06-14 at 17 28 58

Expected: dark background

iPhone 13 iOS16
`c98dab89`

**Comment by jesmrec** [comment]
### (3) (improvement)

The option `Set as space description` is available for text files in accounts with `Editor` and `Manager` permissions over spaces. It allows to set the content of the text file as space description.

It'd be cool to add it to the client as well (low priority).

Not sure if it'd have some server/API dependency

**Comment by jesmrec** [comment]
### (4)

1. Create an space and share it with another user granting `Viewer` permission.

If `Viewer` user opens empty folder, it looks like:

Screenshot 2022-06-14 at 17 56 51

Menu to add content is hidden because no actions are available for `Viewer`. In that case, the header should be also hidden,  showing an placeholder like the one used before (A folder image with a title or similar)

NOTE: Same issue when a space is disabled.

iPhone 13 iOS16
`c98dab89`

**Comment by jesmrec** [comment]
### (5)

If user with `Viewer` permissions on a space clicks on the `+` button on the top, nothing happens (`Viewer` is not allowed to add new content)

I'd hide the `+` or show a warning about this issue (first one better IMO)

iPhone 13 iOS16
`c98dab89`

**Comment by jesmrec** [comment]
### (6)

I know that sharing is still a restriction, but i will comment this one:

If `Viewer` user clicks on three dot button on the top, `Searching Shares...` and the spinner are there forever. Not sure if the best here is hiding the option, or there is any other bad thing happening under the hood. No infinite requests are sent to the server indeed.

iPhone 13 iOS16
`c98dab89`

**Comment by jesmrec** [comment]
### (7)

Favorite/Unfavorite star returns non translated error for `Viewers` permission users:

Screenshot 2022-06-14 at 18 08 17

iPhone 13 iOS16
`c98dab89`

**Comment by jesmrec** [comment]
### (8)

Items in the space for `Viewer` users have the `Cut` option available. `Cut` removes the original file after pasting wherever. Removing files is not allowed to `Viewer` so that it should not be available. 

iPhone 13 iOS16
`c98dab89`

**Comment by jesmrec** [comment]
### (9)

`Links` option in action card is available for `Viewers` and `Editors`,  but empty. It shouldn't be available, since sharing is only available for `Managers`:

Screenshot 2022-09-30 at 09 56 35

iPhone 13 iOS16
`c98dab89`

**Comment by jesmrec** [comment]
(10) (improvement)

I miss the footer file/folder counter available in personal drives. Very useful!

**Comment by jesmrec** [comment]
### (11)

1. Open app in iPad
2. Set `Dark` theme
3. Open the list of files of oCIS instance
4. Open multiselection mode and select some items

Current: actions bar does not follow the theme:

Screenshot 2022-10-03 at 13 45 49

iPadAir2 v15
`4b9af63aa`

**Comment by jesmrec** [comment]
### (13)

1. Create a new space in web
2. In app open the space
3. In web, disable and remove the space
4. In app, try to upload something or create new folder

Current: Space was deleted, so those actions are not posible. Error is not friendly:

Screenshot 2022-10-05 at 10 09 45

Screenshot 2022-10-05 at 10 09 55

iPhone 13 iOS16
`c98dab89`

**Comment by jesmrec** [comment]
### (14)

1. Open any space with content inside
2. Open the card for any file and select `Copy`
3. Select `Choose destination directory...`

Current: empty list
Expected: folders listed to select destination directory

NOTE: Same bad behaviour with move operation

iPhone XR iOS16
`f0d2ce2c`

**Comment by jesmrec** [comment]
### (15) 

pull to refresh action is missing in the list of files to force everything to date.

iPhone XR iOS16
`f0d2ce2c`

**Comment by jesmrec** [comment]
### (16)

1. Open personal space
2. Share a file with another user in the platform (default permissions)

Current: Recipient does not see the file in the list of pending shares
Expected: Recipient sees file in the list of pending shares

App sends a  POST request like with payload:

```
path:        /Share1.txt
shareType:   0
permissions: 22
shareWith:   bob
```

is that `22` correct?? 

By opening the created share and sending change with same permissions, the `PUT` request contains `18` in permission.

iPhoneXR v16
`f0d2ce2c01`

**Comment by felix-schwarz** [comment]
As of `fix/v12-fixes`, the following are addressed:
- (1) no longer applicable
- (4) adjusted text
- (5) now shows a message
- (6) fixed alongside new sharing UI
- (7) favorite/unfavorite is no longer shown if it is not supported
- (8) + (9) fixed by permission checks
- (10) fixed
- (11) fixed since `feature/css`
- (12) + (13) views into disabled spaces are removed from navigation as soon as the space is detected as having been removed
- (14) has been fixed
- (16) can no longer reproduce after implementing new sharing

**Comment by felix-schwarz** [comment]
As of `fix/v12-fixes` #1207 now also addresses (15).

**Comment by jesmrec** [comment]
### (1)

**Feature**: Searching
**Severity**: Low

In a folder with some files (more than 10 for iPhone, more than 20 for iPad). 

1. Click on lens icon
2. Select `Folder` as scope
3. Select `Type = file` 

Current: all files in the folder are correctly listed. But, the files on the screen bottom are hidden behind the soft keyboard
Expected: any way to vanish the soft keyboard?

https://user-images.githubusercontent.com/14894746/197511405-cf9646e8-020b-4426-b0f0-13a3d12e8ea2.MP4

iPhoneXR v16.3
`11297b97`

**Comment by jesmrec** [comment]
### (2)

**Feature**: iPad
**Severity**: High

1. Install the app from scratch to iPad
2. Add some accounts
3. Close the app
4. After some minutes open the app

Current: Attached accounts are not there, empty view. By clicking on `+` and adding new account, all the accounts appear again

Expected: list of accounts visible after reopening

Video recording with the `Current` section (app reopened, before the accounts were attached). You can see in the video that in the opening there is no accounts (just the `+`) and after adding new account, the three accounts attached before appear again

https://user-images.githubusercontent.com/14894746/225292511-4790d558-e1fe-4f1e-a7ff-31518386f9ff.MP4

Logs caught: 
[ownCloud_23_May_2023_at_13_10_26.log.txt](https://github.com/owncloud/ios-app/files/11543055/ownCloud_23_May_2023_at_13_10_26.log.txt)


NOTE: I reproduced the problem after state restoration as well

iPadPro, iPadOS16.3 
`11297b97`

**Comment by felix-schwarz** [comment]
@jesmrec Regarding (2): I can't find anything that would explain that issue in either the source code or the provided logs. I also tried reproducing it on an iPad Pro 9.7", but without success.

Do the missing accounts appear if you "resize" the app / put the app in split view with another app?

Can you reproduce the issue when launching the app from Xcode? A remote debug session might be a chance to get to the bottom of the issue then.

**Comment by jesmrec** [comment]
> Do the missing accounts appear if you "resize" the app / put the app in split view with another app?

No they don't appear.

> Can you reproduce the issue when launching the app from Xcode? A remote debug session might be a chance to get to the bottom of the issue then.

reproducible also when launching from Xcode.

**Comment by jesmrec** [comment]
(2) fixed

**Comment by ChrisEdS** [comment]
Seen in latest Testflight build:

image

**Comment by michaelstingl** [comment]
Private link `owncloud://demo.owncloud.com/f/9` to folder "`/Photos`" no longer opens the folder, only highlights it:

IMG_3712 | IMG_3713
-- | --
`ownCloud release version 11.11.1 build 230 (app: 58fd75c, sdk: 57729a6)` | `ownCloud release version 12.0 build 266 (Fri Jun 2 11:51:44 CEST 2023) (app: v12.0-appstore.1 - milestone/12.0@0ae63e9e, sdk: v12.0-appstore.1 - feature/graph-api@cf34eda)`

**Comment by jesmrec** [comment]
### (5)

**Feature**:  Previews
**Severity**: Medium

1. Upload a big video 
2. in `Settings`, enable `Download instead of Streaming`
3. In list of files, click the video file

Current: black screen while the video is downloading. If video file is large, black screen for much time on foreground
Expected: kind of download indicator 

iOS/iPadOS v16
`8cb83d7f`

**Comment by jesmrec** [comment]
### (6)

**Feature**: Copy
**Severity**: Low

1. Select a folder and `Copy`
2. Select `Copy to clipboard`

Current: notification missing
Expected (11.11.1): notification:

Screenshot 2023-06-05 at 14 43 50

Copy files through clipboard to another account is not an allowed feature 

iOS/iPadOS v16
`8cb83d7f`

**Comment by jesmrec** [comment]
### (7) 

**Feature**: Previews
**Severity**: Low

1. Open a PDF file
2. Double click on it

Current: Full screen mode not totally shown, top bar stays in screen
Expected: Full screen mode. Only the file in screen, top and bottom bars hidden

iOS/iPadOS v16
`8cb83d7f`

**Comment by jesmrec** [comment]
### (10)

**Feature**: List of files
**Severity**: High

1. Create a new space in the oCIS account
2. Add an item to the space
3. Share the item with other user (invite) 
4. Go to the space's list of files
5. Open the card of the shared item

Current: `Unshare` option instead of `Delete`. Clicking on that option does nothing. Item is neither unshared nor deleted.

Screen Shot 2023-06-07 at 09 46 16

Expected: `Delete` option should be there. In addition, `Unshare` option could be there too, to remove all the sharees. 

iOS/iPadOS v16
`8cb83d7f`

**Comment by jesmrec** [comment]
### (11)

**Feature**: Files App
**Severity**: High

1. In an external app (MS Office, f.ex.), create a new file
2. Save the new file in oC account (Files App)

Current: file is saved as 0B
Expected: file is saved correctly, with the content

iOS/iPadOS v16
`8cb83d7f`

**Comment by jesmrec** [comment]
### (12)

**Feature**: Files App
**Severity**: Low

`Share` option is duplicated in contextual menu in Files App. Both options trigger different actions but could be confusing.
 
Screenshot 2023-06-07 at 11 01 46

iOS/iPadOS v16
`8cb83d7f`

**Comment by jesmrec** [comment]
### (13)

**Feature**: Files App
**Severity**: High

1. In oCIS account, user1 shares some items with user2
2. User2 accept shares
3. User2 open the account in Files App

Current: items listed:

- Personal space ✅ 
- Available Spaces ✅ 
- Shared with me ✅ 
- Items shared in step1  ❌ 

|Spaces (app view)|Shares with me (app view)|Files app|
|:-:|:-:|:-:|
|Screen Shot 2023-06-09 at 09 52 14|Screen Shot 2023-06-09 at 09 52 25|Screen Shot 2023-06-09 at 09 52 53|

Expected: Item listed

- Personal space ✅ 
- Available Spaces ✅ 
- Shared with me ✅ 

iOS/iPadOS v16
`8cb83d7f`

**Comment by jesmrec** [comment]
### (14)

**Feature**: Files App
**Severity**: Low

Expected behaviour? In `11.11.1` we had 5 different themes, in `12.0` only two available themes. Mapping is:

| 11.11.1 | 12.0 | Result | Comment |
|:-:|:-:|:-:|:-|
|Light| Light | ✅ 
|Dark web| Light | ❌ | Dark theme turns into light theme |
|Dark Blue| Dark | ✅ 
|Dark Black| Light | ❌ | Dark theme turns into light theme |
|Classic| Light | ✅ 

iOS/iPadOS v16
`8cb83d7f`

**Comment by jesmrec** [comment]
### (15)

**Feature**: Spaces
**Severity**: Medium

1. In any account, open card of a file and select  `Copy`
2. Select `Copy to clipboard`
3. Open `Spaces` view
4. In 3-dot-button of any space with writing permission, select `Paste`

Current: nothing happens
Expected: Copie item pasted inside the space

iOS/iPadOS v16
`8cb83d7f`

**Comment by felix-schwarz** [comment]
@jesmrec I just fixed findings (3) (4) (6) (8) (13).

Regarding (14): the old themes didn't account for a segmented UI (side bar area + content area) and therefore have been replaced with a single light and a single dark theme. Additional themes can be added in the future if needed.

**Comment by felix-schwarz** [comment]
@jesmrec finding (11) is fixed as well now

**Comment by felix-schwarz** [comment]
@jesmrec finding (15) is fixed as well now.

**Comment by felix-schwarz** [comment]
@jesmrec #1220 fixes (1) and (7)

**Review by hosy — APPROVED** [review]

**Comment by felix-schwarz** [comment]
@jesmrec #1220 now also fixes (9)

**Comment by felix-schwarz** [comment]
@jesmrec #1220 now also fixes (12). That string is stored in the File Provider UI's `Info.plist` and therefore can't be changed dynamically at runtime. To keep it branding-friendly, I chose "Share by cloud" instead of "Share via ownCloud", "Share (ownCloud)", which would have required to customize both the `Info.plist` and the translations for branding.

**Comment by felix-schwarz** [comment]
@jesmrec finding (5) is also fixed in #1220 now

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
