### PR TITLE
[feature/new-search] New search experience for version 12

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
Implements a new and refined search experience for version 12. Key improvements:
- integrated scope switcher (folder / tree (folder + subfolder) / space / account)
- localized tokenization of special search terms
- scope-specific suggestion bar aiding with discoverability and composition of special search terms ("tokens")

Description of how parts of it work internally: https://github.com/owncloud/ocis/issues/4667#issuecomment-1259216514

## Related Issue
#933 

## TODO
- [x] placeholder content view when no search term has been entered yet
- [x] a richer representation of tokens in _saved searches_ and _search views_
- [x] the ability for users to enter a name for their _saved search_ or _search view_
- [ ] ~integration of _saved searches_ in side bar or quick access~ (moved to `feature/new-navigation`)

## Screenshots (if appropriate):

Search with scope picker, tokenization of special terms while entering (here `:image`), limiting search results with regular search terms:

Inline Scope Picker | Tokenization while typing | Limiting with search term
---|---|---
Simulator Screen Shot - iPhone 13 mini - 2022-09-14 at 21 39 35 | Simulator Screen Shot - iPhone 13 mini - 2022-09-14 at 21 40 18 | Simulator Screen Shot - iPhone 13 mini - 2022-09-14 at 21 40 22

The search scope's suggestion bar provides quick access to type, date and size filters. If the user picks a suggestion, the suggestion's category is highlighted. Selecting the suggestion in the popup again removes it from the search query:

Type Suggestions | Date Suggestions | Size Suggestions
--|--|--
Simulator Screen Shot - iPhone 13 mini - 2022-09-14 at 21 40 32 | Simulator Screen Shot - iPhone 13 mini - 2022-09-14 at 21 40 36 | Simulator Screen Shot - iPhone 13 mini - 2022-09-14 at 21 40 39 | Simulator Screen Shot - iPhone 13 mini - 2022-09-14 at 21 40 48

It's also possible to save searches and restore them. There should be a differentiation in _saved searches_ and _search views_ down the road:
- _saved searches_ save scope (folder / account / space), filters (type, date, size, …), search terms and the searched location (think "Smart Folders" like on macOS)
- _search views_ save scope (folder / account / space), filters (type, date, size, …), search terms, but not the searched location (think "search settings quickly re-applicable to any location")

Save as search view / search template | Without any search terms | Selecting `:presentation Reports`
--|--|--
Simulator Screen Shot - iPhone 13 mini - 2022-09-30 at 21 44 03 | Simulator Screen Shot - iPhone 13 mini - 2022-09-30 at 21 42 09 | Simulator Screen Shot - iPhone 13 mini - 2022-09-30 at 21 46 57

## Special filter keywords / tokens

Compared to #933, `feature/new-search` adds additional filter keywords. Below is an updated table with examples, covering all of them:

Term | Meaning
------|---------
`engineering` | find items with `engineering` in their name
`engineering demos` | find items with `engineering` and `demos` in their name
`"engineering demos"` | find items with `engineering demos` in their name
`"engineering "demos` | find items with `engineering` and `demos` in their name
`type:pdf` | limit search to items with a pdf suffix
`type:pdf,mov` | limit search to items with a pdf or mov suffix
`before:2021` | limit search to last modified before 2021-01-01
`before:2021-02` | limit search to last modified before 2021-02-01
`before:2021-02-03` | limit search to last modified before 2021-02-03
`after:2020` | limit search to last modified after 2020-01-01
`after:2020-02` | limit search to last modified after 2020-02-01
`after:2020-02-03` | limit search to last modified after 2020-02-03
`on:2020-02-03` | limit search to last modified on 2020-02-03 (0h-24h)
`on:2020-02-03,2020-02-05` | limit search to last modified on 2020-02-03 (0-24h) or 2020-02-05 (0-24h)
`smaller:200mb` | limit search to items smaller than 200 MB (supports tb / tib / gb / gib / mb / mib / b)
`greater:1gb` | limit search to items greater than 1 GB (supports tb / tib / gb / gib / mb / mib / b)
`owner:cscherm` | limit search to items owned by user cscherm
`:file` | limit search to files
`:folder` | limit search to folders
`:image` | limit search to images (MIME type starting with `image/` or TypeAlias equal to `image`) **extended**
`:video` | limit search to videos (MIME type starting with `video/`) **new**
`:audio` | limit search to audio (MIME type starting with `audio/`) **new**
`:document` | limit search to documents (TypeAlias equal to `x-office/document`) **new**
`:spreadsheet` | limit search to spreadsheets (TypeAlias equal to `x-office/spreadsheet`) **new**
`:presentation` | limit search to presentation (TypeAlias equal to `x-office/presentation`) **new**
`:pdf` | limit search to PDFs (MIME type equals `application/pdf`) **new**
`:year` | limit search to items last modified since Jan 1st of the current year
`:month` | limit search to items last modified since the current months's first day
`:week` | limit search to items last modified since beginning of the current week's Monday 
`:today` or `:d` | limit search to items last modified on the current day
`:5d` | limit search to items last modified  in the last 5 days
`:2w` | limit search to items last modified in the last 2 weeks
`:1m` | limit search to items last modified this or last month
`:m` | limit search to items last modified this month
`:1y` | limit search to items last modified this or last year
`:y` | limit search to items last modified this year
`-[term]` | negates the search term, i.e. `-:image` to exclude images, or `-wrd` to exclude all matches containing `wrd`. This works with any of the examples above.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## QA

Test plan:

Reports:

- [ ] (1) Soft keyboard over the search results https://github.com/owncloud/ios-app/pull/1142#issuecomment-1288862130
- [ ] (2) Hidden files in different scopes https://github.com/owncloud/ios-app/pull/1142#issuecomment-1288924350
- [ ] (3) Parent folder in results of folder search in tree scope https://github.com/owncloud/ios-app/pull/1142#issuecomment-1288939392
- [ ] (4) Add txt files to the type filter https://github.com/owncloud/ios-app/pull/1142#issuecomment-1291583357
- [ ] (5) Behaviour of templates/views https://github.com/owncloud/ios-app/pull/1142#issuecomment-1293393517
- [ ] (6) Tint of button label in template/view creation dialog https://github.com/owncloud/ios-app/pull/1142#issuecomment-1293396244 
- [ ] (7) Empty list in screen with search view https://github.com/owncloud/ios-app/pull/1142#issuecomment-1293416104
- [ ] (8) Incorrect space displayed when jumping to file's location in Account scope https://github.com/owncloud/ios-app/pull/1142#issuecomment-1293465289
- [ ] (9) `Open in new window` jump to incorrect view https://github.com/owncloud/ios-app/pull/1142#issuecomment-1296857849
- [ ] (10) owner criteria to search in custom spaces https://github.com/owncloud/ios-app/pull/1142#issuecomment-1296884911

### CODE REVIEW

**Comment by jesmrec** [comment]
Will test on `experimental/12.0` branch

**Comment by jesmrec** [comment]
### (2)

In an empty space (no matter if personal or custom space):

1. Click on lens icon
2. Set `Folder` scope
3. Set `Type = Folder` -> empty result
4. Set `Tree` scope
5. Set `Type = Folder` 

Current: hidden folders like `.space` and `/` (root) appears as result. Setting `Show hidden files` is disabled.
Expected: Same search over two different "empty" scopes should return same results.

https://user-images.githubusercontent.com/14894746/197519923-e875faaf-80a1-477d-ac2b-4a38b85f50ed.MP4

iPhoneXR iOS16.1
`8ad0aa62`

**Comment by jesmrec** [comment]
### (3)

(probably related with (2)

1. Create a folder structure like `A/B/C`
2. Browse to `B` -> `C` is listed inside
3. Click on lens
4. Set `Tree` as scope
5. Set `Type = folder` 

Current: Results are `B`(current folder) and `C`
Expected: Result is `C`,  because `B` is out of the tree (parent folder). If expectation is different just let me know which one is expected.

https://user-images.githubusercontent.com/14894746/197522342-178af8a0-a3db-4526-af3d-a9e4cc9ed10e.MP4

iPhoneXR iOS16.1
`8ad0aa62`

**Comment by jesmrec** [comment]
### (4)

Just a suggestion: In the `Type` filter, i miss an option for text files (.txt). Would it make sense to add?

**Comment by jesmrec** [comment]
### (5) (question)

Mentioned above:

> saved searches save scope (folder / account / space), filters (type, date, size, …), search terms and the searched location (think "Smart Folders" like on macOS)
search views save scope (folder / account / space), filters (type, date, size, …), search terms, but not the searched location (think "search settings quickly re-applicable to any location")

is that correct?

Checking the implementation (`f0d2ce2c`), i noticed the opposite behaviour

- `Saved search template` applies the filter to the current location. For ex, `Type = Tree "GIF"` returns a folder called `GIF` in the current folder and it subfolders. Same `Saved search template` applied to other folder with no matches, returns empty. That means, searched location not saved.

https://user-images.githubusercontent.com/14894746/198271484-265b17f0-dad5-4600-b710-062521805b4f.MP4

- `Saved search view`, returns always the same result, no matter where the filter is applied:

https://user-images.githubusercontent.com/14894746/198273616-fe6b3e71-c048-4f05-a538-ce0f79a60015.MP4

Which is correct, the implementation or the description?

**Comment by jesmrec** [comment]
### (6)

Template/View creation dialog contains almost-transparent button labels `Cancel` and `Save` in default theme:

Screenshot 2022-10-27 at 13 35 35

iPhoneXR iOS16
`f0d2ce2c0`

**Comment by jesmrec** [comment]
### (7)

1. Create a `Search View` that returns empty
2. Save it
3. Click on lens icon and apply that `Search View`

Current: empty screen
Expected: `No matches` view displayed

https://user-images.githubusercontent.com/14894746/198277741-358acd45-333b-4d8b-a62d-3860f1fe22f0.MP4

iPhoneXR iOS16
`f0d2ce2c0`

**Comment by jesmrec** [comment]
### (8)

1. Create an empty space, called `Space1`
2. Create another empty spaced called `Space2`
3. Upload two videos to `Space2`
4. Open `Space1`
5. Click on lens icon and select `Account` scope
6. Select `Type = Video` -> Videos in `Space2` are shown as result :+1: 
7. Click on right arrow, at the right of the result's cell, to jump to the file location

Current: `Space1` shown with the videos. That's not correct because videos are stored in `Space2`
Expected: Videos stored in `Space2`, so `Space2` should be displayed instead

(name of spaces and videos as type are only examples, also reproducible with other options)

https://user-images.githubusercontent.com/14894746/198285891-bbddb485-a7a7-4ed7-9415-184f9844a4f8.MP4

iPhoneXR iOS16
`f0d2ce2c0`

**Comment by jesmrec** [comment]
### (9)

this one is not directly related with searching, but is reproducible in the current branch (`experimental/12.0`) and not reproducible in `milestone/12.0`

iPad:

1.  Open list of files. 
2. In any file, open three-dot-button and select `Open in a new Window`

Current: List selector is displayed in the new window
Expected: File is opened in new window

iPadPro iOS16
`f0d2ce2c0`

**Comment by jesmrec** [comment]
### (10)

This one is about the `owner:` . That seems to work only in personal space.

By creating a new custom space and uploading some files there, the `owner:` returns nothing with the proper username

iPadPro iOS16
`f0d2ce2c0`

**Review by hosy — APPROVED** [review]

**Comment by felix-schwarz** [comment]
Merged in `milestone/12.0` in cfa9100a6fff3e4dea55bafca61c1db9eae52d45.

**Pull request closed without merging**
