### PR TITLE
[feature/gridview] Gridview implementation (v12)

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
- implements a grid view for items, with switching possible with a new button i the sort bar.
- implements a dynamically adapting grid layout – used for item grid view and the spaces grid overview
- fixes spaces grid staying on screen after disconnect
- fixes more (...) buttons next to space titles being compressed sideways in spaces grid
- fixes quota not being displayed for Personal space
- fixes "empty folder" being shown instead of "loading" + indicator

## Related Issue
#744 

## Screenshots (if appropriate):
Icon + Files | Images only | List view
--|--|--
Simulator Screenshot - iPad (10th generation) - 2023-04-04 at 12 17 00 | Simulator Screenshot - iPad (10th generation) - 2023-04-04 at 12 17 14 | Simulator Screenshot - iPad (10th generation) - 2023-04-04 at 12 17 19

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Comment by jesmrec** [comment]
When folder is set with grid view, all descendants are also grid view but parents preserves the list view. That means, setting grid view affects current folder and descendants, so it is not a account feature. Is that right?

**Comment by jesmrec** [comment]
Create a folder tree with 3 levels, all of them with items inside like /A/B/

1. Browse to A
2. Set Grid mode in A
3. Browse to B

Current: Grid mode in B, but the indicator shows "Grid" instead of "List":

Screenshot 2023-04-12 at 10 09 17

Expected: if list is in "Grid", indicator showing "List" and viceversa

iPadAir2 iPadOS15, iPhoneXR v16
`720e2512`

**Comment by felix-schwarz** [comment]
@michaelstingl Side-by-side comparisons of left-aligned and centered grid cell content:

Left-aligned | Centered
-----|-----
Simulator Screenshot - iPad (10th generation) - 2023-04-12 at 15 26 43 | Simulator Screenshot - iPad (10th generation) - 2023-04-12 at 15 28 25
Simulator Screenshot - iPad (10th generation) - 2023-04-12 at 15 27 03 | Simulator Screenshot - iPad (10th generation) - 2023-04-12 at 15 28 37

**Comment by felix-schwarz** [comment]
@jesmrec wrote:
> When folder is set with grid view, all descendants are also grid view but parents preserves the list view. That means, setting grid view affects current folder and descendants, so it is not an account feature. Is that right?

That's correct.

c4ec2ea8cd20d65563ac08be18cbd38d6ec1439f fixes https://github.com/owncloud/ios-app/pull/1195#issuecomment-1504855318

**Comment by michaelstingl** [comment]
> @michaelstingl Side-by-side comparisons of left-aligned and centered grid cell content

I personally like to previews/icons centered and the text left-aligned, especially when long file names break to a 2nd line with only a few characters.

**Comment by michaelstingl** [comment]
> @michaelstingl The quota is also displayed for the personal space as of https://github.com/owncloud/ios-app/commit/da208f55f94c1a2195e2f4a665df248cc24a902f in this PR. I couldn't immediately find the issue this was reported in.

I’d like to verify in a new TestFlight

**Comment by felix-schwarz** [comment]
@michaelstingl Build 255 with all the latest changes is currently uploading. It also includes a checkmark for grid view multi select.

**Comment by felix-schwarz** [comment]
@jesmrec Build 256 (955b38a) partially addresses https://github.com/owncloud/ios-app/pull/1195#issuecomment-1504839973 by centering the cells if needed, improving the look. 

Cell size is now computed dynamically based on a minimum width, with an optional maximum width (currently used for the spaces grid only) towards which the cell width is increased to use the maximum amount of space. The remaining space is then used to center the items.

Which device did you take the screenshot with?

**Comment by jesmrec** [comment]
iPhone XR with iOS16, i will take another look. Thanks for improving!

**Review by hosy — APPROVED** [review]

**Comment by jesmrec** [comment]
QA checks

- [X] Grid view iPhone
- [X] Grid view iPad
- [X] Grid view change orientation (rows and columns adapted)
- [X] Grid view persisting subfolders
- [X] Grid view drag & drop
- [X] Grid view in Dark Theme
- [X] Grid view only pictures (all thumbnails)

From my side is OK

**Review by jesmrec — APPROVED** [review]

**Comment by felix-schwarz** [comment]
Accidental merge

**Comment by felix-schwarz** [comment]
Merged into https://github.com/owncloud/ios-app/pull/1095.

**Pull request merged**
