### PR TITLE
Take Photo or Video and Upload

### PR DESCRIPTION
**Pull request by mneuwert**
## Description
Added new action allowing to take picture or shoot a video-clip and then upload it to the current folder. Also the action is following users settings concerning media export before upload (JPEG vs HEIC, MP4 vs MOV). This feature is residing in the menu behind the "+" button.

## Related Issue
#615 

## Motivation and Context
This feature saves time and also doesn't require to first create a media file, store it to the photo library and then upload it from there.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## QA

Test Plan: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2011.4.0/Take%20Photo%20or%20Video.md

Reports:

- [x] (1) Some wording minor issues https://github.com/owncloud/ios-app/pull/707#issuecomment-634640476
- [ ] (2) Pictures not uploaded in iPad https://github.com/owncloud/ios-app/pull/707#issuecomment-634648729

### CODE REVIEW

**Comment by jesmrec** [comment]
### (1)

Details about wording:

- In the view to take the picture: `Use photo` or `Use video` . What about `Upload Photo` or `Upload Video` . What do you think?

- Uploading photo results in a `.jpg` or `.heic` file. Uploading video in a `.MOV` file (extension in uppercase). Maybe this is something not related with the current PR, so it can be moved. This is not an important issue, for sure. 

you mentioned:

> Also the action is following users settings concerning media export before upload (JPEG vs HEIC, MP4 vs MOV)

just to be in the same page, MP4 vs MOV is not currently available.

**Comment by jesmrec** [comment]
### (2)

With an iPadAir v13.4, pics are not being uploaded (videos are correctly uploaded). No error is displayed, nothing is stucked in `Status`

ezgif com-optimize (4)

I've also taken logs, if it helps:

[ownCloud_27_May_2020_at_14_59_56.log.txt](https://github.com/owncloud/ios-app/files/4688910/ownCloud_27_May_2020_at_14_59_56.log.txt)

**Comment by mneuwert** [comment]
### Re (2)
Tested with iPad Pro running iOS13.3.1 and could take and upload photos with front and back cameras with JPEG conversion ON and OFF.

**Comment by jesmrec** [comment]
(1) -> OK, thanks for clarification. 

(2) -> iPadAir 2, iOS13.4. oC server 10.4.1 with basic auth. Only open the app, select the option, take the picture. 

If Conversion to JPG is enabled -> Picture is uploaded
If Conversion to JPG is disabled (heic format) -> Picture is not uploaded.

**Comment by mneuwert** [comment]
@jesmrec just tried to change format setting for Camera.. and also couldn't reproduce. Will try to update my update and check again..

**Comment by jesmrec** [comment]
ok, if you need something like more logs or whatever, please let me know

**Comment by hosy** [comment]
I tried it too and for me the heic file appeared after I took a second photo. 
Maybe it takes some seconds!?

**Comment by mneuwert** [comment]
@hosy I think.. in the file-list the file would appear first, when it was imported by the `OCCore` as part of `OCQuery` results attached to the list. It can take some time I guess..

**Comment by hosy** [comment]
maybe using the placeholder completion handler? First thought was, the photo was not taken. Maybe this can confuse some users. 
Anyway: I love this new feature!

**Comment by mneuwert** [comment]
@hosy I will check what can be done.. may be some progress indication.. I tested on iPad Pro / iPhone Pro.. and didn't notice any delays

**Comment by mneuwert** [comment]
@jesmrec @hosy added progress HUD shown while writing media asset to disk is ongoing.

**Comment by jesmrec** [comment]
These are the logs taken with commit `66022b99` and two heic pics:

[ownCloud_29_May_2020_at_08_38_06.log.txt](https://github.com/owncloud/ios-app/files/4700079/ownCloud_29_May_2020_at_08_38_06.log.txt)

This is the performance:

ezgif com-optimize (5)

In any case, if no one of you are able to reproduce it, we can use the TetstFlight beta as benchmark to get more details

**Comment by mneuwert** [comment]
@jesmrec Hm.. I see this 

 - [APP, CAMERA_UPLOAD] Creating CGImageDestination with URL file:///private/var/mobile/Containers/Data/Application/812D18C6-CB51-4E72-91C0-23CE81629A67/tmp/Photo-2020-05-29-08-38-24.heic 
- [ERROR] | [APP, CAMERA_UPLOAD] Destination or image is not valid [UploadCameraMediaAction.swift:110|FULL]

Which I didn't expect meaning that we can't create a `CGImageDestination` with above URL or the system view controller didn't return a valid `UIImage`...

I added even more logs.. please try once.. Now we should able to catch it.  Otherwise may be there is something wrong with the iPad, did you try to reboot? Is there enough of free flash memory? Can you please also share camera app settings?

**Comment by jesmrec** [comment]
@mneuwert logs taken with the latest commit `c450ffc`. Two pics were taken with no upload:

[ownCloud_1_Jun_2020_at_09_24_53.log.txt](https://github.com/owncloud/ios-app/files/4709965/ownCloud_1_Jun_2020_at_09_24_53.log.txt)

**Comment by mneuwert** [comment]
@jesmrec Ok.. looks like for whatever reason system you are testing on is not able to write HEIC compressed files. This log message comes from iOS:

[OS] [ownCloud] findWriterForType:129: unsupported file format 'public.heic' [NSLog:0|FULL]

It is printed as `CGImageDestinationCreateWithURL()` is being called. May be some temporary hiccup.. since HEIC support was introduced in iOS7 and should be definitely supported on your iPad.

I added a check if HEIC is supported. If not, I fall back to the jpg and add a warning to the log. Please check with the latest commit.

**Comment by jesmrec** [comment]
With the latest commit, the problem is fixes by forcing to upload in jpg format if not posible in heic.

From my side this is approved.

**Pull request merged**
