### PR TITLE
[fix/continuous-audio-playback] Fix: Continuous Audio Playback

### PR DESCRIPTION
**Pull request by hosy**
## Description
Fixed continuous audio playback, which stopped, after two audio files, because of not setting the `activeDisplayViewController`, when starting a new audio file

## Related Issue
https://github.com/owncloud/enterprise/issues/4924

## Motivation and Context
Play continuous all audio files in a folder

## How Has This Been Tested?
- Put some audio files (at least 3 files) in a folder
- Select the first audio file
- The new audio file should start playing, when the current has finished

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Added changelog files for the fixed issues in folder changelog/unreleased

## QA

- [X] (1) Title missing from 2nd file https://github.com/owncloud/ios-app/pull/1088#issuecomment-1011037914
- [x] (2) Wordart exceeds the screen width https://github.com/owncloud/ios-app/pull/1088#issuecomment-1011067496 [FIXED]
- [ ] (3) `Open in a new window` does not reproduce the mp3 file https://github.com/owncloud/ios-app/pull/1088#issuecomment-1011072901

### CODE REVIEW

**Review by felix-schwarz — APPROVED** [review]

**Comment by jesmrec** [comment]
### (1)

Look at these steps:

1. Inside a folder with many mp3 files, play one of them
2. When it finishes, it jumps to the next one

Current: 1st mp3 file shows the file name on the top. 2nd (and so on) mp3 title is missing on the top:

Screenshot 2022-01-12 at 14 16 52

`7a822d2`
iPhoneXR v15.1

**Comment by jesmrec** [comment]
### (2)

This is not a regression, so, feel free to fix here or address in another issue.

Artwork images does not fit the screen width. I checked with our latest versions with same result. For example:

Screen Shot 2022-01-12 at 14 21 57

`7a822d2`
iPhoneXR v15.1

**Comment by hosy** [comment]
@jesmrec 
(1) is fixed

**Comment by jesmrec** [comment]
### (3)

Same as (2), this is not a regression, so, feel free to fix here or address in another issue.

1. In iPad, open the app after killing (it's needed to reproduce that the app was not opened before)
2. Open a folder with mp3 files
2. Select any of them with the action `Open in a new Window`

Current: New window is open, play control displayed on the center, but this is not clickable. No way to play the music. Then, by selecting another file, it works. First time fails, second time OK

iPadAir2 iPadOS14.7
`7a822d2`

**Comment by hosy** [comment]
(2) is fixed too

**Comment by jesmrec** [comment]
(1) and (2) fixed correctly!!

is (3) fixable? otherwise, we could move this forward.

**Pull request merged**
