### PR TITLE
[feature/fp-series-3] File Provider improvements

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
Further improvements to the file provider:
- this branch updates the app and the SDK to implement and use a new `OCLocalID`, which stays identical for the lifetime of an item (including the transition from local placeholders to items on the server). It'd be a fourth option (in terms of the last comments in #167) to fully solve the import issue found by @jesmrec in #167.
- …

## Related Issue
#167 #204 #165 #175

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

____

**Status check**:

- [x] https://github.com/owncloud/ios-app/pull/167#issuecomment-456344038
- [ ] Check creation of files from 3rd party apps (F.ex. MS Office)
- [ ] Propagation: https://github.com/owncloud/ios-app/issues/204#issuecomment-456058095 (check second bullet point)
- [x] Tests are broken in  https://github.com/owncloud/ios-app/blob/efe24f4a035a97acecf01183ecfc1afeb3117133/ownCloudTests/Login/EditBookmarkTests.swift#L85 , in the call of ` `UtilsTests.refreshServerList()`  [FIXED]
- [ ] #165 [QA in progress, see below]
- [ ] #175 [QA in progress, see below]
______

BUGS & IMRPOVEMENTS

- [ ] (1) Switch account with an executing option https://github.com/owncloud/ios-app/pull/233#issuecomment-458612687
- [ ] (2) Clicking area size https://github.com/owncloud/ios-app/pull/233#issuecomment-458626801
- [ ] (3) Two clicks to repeat a download https://github.com/owncloud/ios-app/pull/233#issuecomment-458629486
- [ ] (4) Cancel current operation from Activity https://github.com/owncloud/ios-app/pull/233#issuecomment-458634138
- [ ] (5) Cancel enqueued operations https://github.com/owncloud/ios-app/pull/233#issuecomment-458639928
- [ ] (6) Download with no connection https://github.com/owncloud/ios-app/pull/233#issuecomment-458844543
- [ ] (7) Spinner in Server down https://github.com/owncloud/ios-app/pull/233#issuecomment-459250786

### CODE REVIEW

**Comment by jesmrec** [comment]
summing up: 

- [ ] https://github.com/owncloud/ios-app/pull/167#issuecomment-456344038
- [ ] Check creation of files from 3rd party apps (F.ex. MS Office)
- [ ] Propagation: https://github.com/owncloud/ios-app/issues/204#issuecomment-456058095 (check second bullet point)
- [ ] Tests are broken in  https://github.com/owncloud/ios-app/blob/efe24f4a035a97acecf01183ecfc1afeb3117133/ownCloudTests/Login/EditBookmarkTests.swift#L85 , in the call of ` `UtilsTests.refreshServerList()`

**Comment by jesmrec** [comment]
### (1)

Commit: 966eddfda1968d62369e1ffd62f610744b3bc34a

1. Attach two accounts 
2. In one of them, upload a huge file (so, you will have time to do other actions)
3. Switch to the other account
4. Switch again to the account with the upload

Current: app is stucked when the bookmark is selected
Expected: Switching accounts work correctly

**Comment by jesmrec** [comment]
Activity view seems to work for each bookmark separately, am i correct?

**Comment by jesmrec** [comment]
### (2)  (Improvement)

Clicking area to cancel action is a bit small. Maybe it should take more room to make easier the clicking action

**Comment by jesmrec** [comment]
### (4)

1. Copy a folder to another location (select one with much content, so you will have time to perform the next steps)
2. Go to Activity and cancel.
3. Action is stucked:

jan-29-2019 18-35-54

Note: it is more difficult to reproduce (it runs faster), but the same effect  happens in a file deletion

iPhoneX iOS12.1

**Comment by jesmrec** [comment]
### (5)

1. Enqueue several actions. F.ex, a huge upload and then, create a folder and remove a file
2. While the upload is running, go to Activity and try to remove the enqueued operations (creation of a folder or file removal)

Current: Not posible, by clicking the "stop" icon the action is not cancelled. 
Expected: Action cancelled and not executed after the current one finishes

iOS12.1.2 iPhoneX

**Comment by felix-schwarz** [comment]
@jesmrec Thanks for the feedback!

Regarding the issues:
(1) This is a known issue on my end and I'm looking into it.

> Activity view seems to work for each bookmark separately, am i correct?
Yes, like everything else, this, too, is separate for every bookmark.

(2) The touch target is much larger than just the circle and the small rectangle in the middle. In fact, it's the same size as the "* * *" button whose place it takes:

bildschirmfoto 2019-01-29 um 21 48 57

(3) Thanks, I'll try to reproduce this one.

(4) + (5) Not all sync actions will yet handle cancelling gracefully. The first iteration of the activity view may therefore limit cancellation to uploads and downloads until the sync actions catch up. I'd like to work on this between 0.4.0 and the App Store 1.0.0.

**Comment by jesmrec** [comment]
### (6)

1. Switch device connection off
2. Tap in a file to download it

Current: Nothing happens
Expected: Every action must have a reaction. The previous behaviour was, showing a message `There is no network`

iOS12.1.2 iPadAir2

**Comment by jesmrec** [comment]
Other question regarding downloads: afaik, when a file is downloaded to the device, it is stored in a temporal folder, that will be wiped up somewhere. In case it happens (files wiped up), will the "not downloaded" icon be displayed again? how are currently handled the downloaded files? It will also will have to do with the future available offline feature (https://github.com/owncloud/ios-app/issues/134)

**Comment by felix-schwarz** [comment]
@jesmrec Small update from my side:
(3) Fixed in latest commit. That issue reached really deep and required adjustments on the Sync Engine and even database scheme level.
(6) Fixed in latest commit.

Regarding the life cycle of files:
- due to FileProvider requirements, files can't be stored in a temporary location
- right now, local copies are only deleted if
    - the user deletes the file
    - the local copy has no modifications and the server holds a different/newer version
- auto-deletion of local files is currently not supported by the SDK, but I plan to implement it in a way that deletes local files
   - if they are unmodified and
   - if they haven't been downloaded in the same session and
   - if they meet a criteria configurable by the user:
       - after a period of time has passed
       - if less than a certain amount of space is left on the device
       - if all locally stored files together exceed a certain amount of space on the device
- once there's no longer a local copy of a file, the "download from cloud" icon is shown again for that item

**Comment by jesmrec** [comment]
Batched uploads reported here: https://github.com/owncloud/ios-app/pull/167#issuecomment-456344038, were tested with about ~1000 files, and they worked fine (only one account, pending of https://github.com/owncloud/ios-app/pull/233#issuecomment-458612687 to check with more that one account)

**Comment by jesmrec** [comment]
### (7)

About server down #230:

By pulling down with server no available, the spinner on the top remains forever:

jan-31-2019 08-57-13

Commit: ce937dde83f88426ebfb656c538411187d1e03ff

**Comment by felix-schwarz** [comment]
@jesmrec (7) should be fixed as of https://github.com/owncloud/ios-app/pull/233/commits/8f85aaf5ff3fb1f5d7f423159176f607a78767c9

**Pull request merged**
