### PR TITLE
[fix/markup-ios16-crash2] Markup Mode on iOS 16

### PR DESCRIPTION
**Pull request by hosy**
…) on iOS 16

## Description
This PR fixes another crash when opening a PDF in markup mode.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Comment by jesmrec** [comment]
@hosy crash is fixed in iPadOS16. 

But, Markup mode not enabled by default (iPadOS16).

**Comment by hosy** [comment]
@jesmrec please can you attach a screenshot of the UI after not enabling?

**Comment by jesmrec** [comment]
sure, here it is. 

After selecting `Markup`, image is open but markup palette is not there. Only when i click manually on it:


https://user-images.githubusercontent.com/14894746/196938993-6b5c9d50-8d0a-4cc8-9151-260c8c007121.MP4

iPadPro iPadOS 16
`13889dc2a`

**Comment by hosy** [comment]
@jesmrec please try again on iPad and iPhone with the latest commit

**Comment by jesmrec** [comment]
@hosy commit `1a127074` does not fix the problem in iPadOS16 If you need extra info (logs, screensharing or whatever), just let me know.

**Comment by hosy** [comment]
@jesmrec I fixed a problem on the iPad. Please can you try it again?

**Comment by jesmrec** [comment]
Now is fixed.

Ready to go.

**Comment by hosy** [comment]
@jesmrec unfortunately I found another edge case on the iPad if the UI is in compact view (can be tested in split view). Please can you have a look again before merging?

**Pull request merged**
