### PR TITLE
[release/1.1.2] Release 1.1.2

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
- uses only local `NSURLSession`s in the app and adds resume support for downloads
- this works around an issue in background `NSURLSession`s that adds long delays before starting a request (details: https://forums.developer.apple.com/thread/124450)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by jesmrec** [comment]
Downloading a big file (1GB) and moving the app to background

The observed behaviour in `master`:

`2019-10-22 16:42:09.115000+0200 ownCloud[439:025776] ⚪️ | [HTTP, Background, …] Task [taskIdentifier=<1>, url=http://.../remote.php/dav/files/user1/Archive.mp4] didFinishCollectingMetrics: { total: [2019-10-22 14:38:48 +0000 - 2019-10-22 14:39:48 +0000, 59.79 sec], startedAfter: 0.01, redirects: 0, transactions: [1: fetchStart: 0.01, DNS: 0.02..0.02 (0.00), connect: 0.02..0.03 (0.01), request: 0.03..0.03 (0.00), cloud: 0.03..0.19 (0.15), response: 0.19..59.79 (59.60)] } [… PipelineID:background, Instance:0x102d49cd0, URLSessionID:background;com.owncloud.ios-app, HTTP, Metrics, GET, RequestID:6EB79E96-D215-4729-A268-DE6F50989638, URLSessionTaskID:1] [OCHTTPPipeline.m:1776|FULL]`

Fetch: 0.01
End Response: 59.79

i execute 5 times and not always was reproducible. I got a response of 5.04 in another two times.

With the fix (current branch):

`2019-10-22 16:30:21.661000+0200 ownCloud[405:020362] ⚪️ | [HTTP, Local, …] Task [taskIdentifier=<15>, url=http://.../remote.php/dav/files/user1/Archive.mp4?y=400&preview=1&x=400&c=%22bd8565afa16d3a9484e45c7722cf8a89%22&a=1] didFinishCollectingMetrics: { total: [2019-10-22 14:30:21 +0000 - 2019-10-22 14:30:21 +0000, 0.28 sec], startedAfter: 0.01, redirects: 0, transactions: [1: **fetchStart: 0.01**, DNS: 0.04..0.04 (0.00), connect: 0.05..0.10 (0.05), request: 0.10..0.10 (0.00), cloud: 0.10..0.28 (0.18), **response: 0.28**..0.28 (0.00)] } [… PipelineID:ephermal, Instance:0x111b7cb60, HTTP, Metrics, GET, RequestID:03B8EAEB-912A-4F81-A004-567BEC7BE53A, URLSessionTaskID:15] [OCHTTPPipeline.m:1854|FULL]`

Fetch: 0.01
End Response: 0.28

Executed 5 times with correct timings.

Tested with iOS 13.1.3
Not reproducible in iOS13.1.2

Please, if you miss something, let me know

**Comment by jesmrec** [comment]
I also noticed that the class `ownCloud/Settings/UploadsSettingsSection.swift` was totally removed. Does this affect to the app, or is it only unused code? @felix-schwarz

**Comment by hosy** [comment]
@felix-schwarz @jesmrec this is the class I mentioned today. This is the UI for auto upload options. Can we recycle this class for the auto upload issue?

> I also noticed that the class `ownCloud/Settings/UploadsSettingsSection.swift` was totally removed. Does this affect to the app, or is it only unused code? @felix-schwarz

**Comment by felix-schwarz** [comment]
@jesmrec Those metrics look perfectly reasonable and it seems that the background NSURLSession did not hit you in that case. I noticed, though, that the two log excerpts show different transfers:

- the `master` snippet shows the download of `Archive.mp4` (the 1 GB file) (`url=http://.../remote.php/dav/files/user1/Archive.mp4`)
- the `release/1.1.2` snippet shows the response to a thumbnail request for `Archive.mp4` (`http://.../remote.php/dav/files/user1/Archive.mp4?y=400&preview=1&x=400&c=%22bd8565afa16d3a9484e45c7722cf8a89%22&a=1`)

Re `ownCloud/Settings/UploadsSettingsSection.swift`: I removed this file as it was just a placeholder and not used anywhere, so it's removal has no effects at all.

The features that it was a placeholder for have since been implemented by @mneuwert in `MediaUploadSettingsSection.swift`.

**Comment by jesmrec** [comment]
> the release/1.1.2 snippet shows the response to a thumbnail request for Archive.mp4, which of course is much shorter (http://.../remote.php/dav/files/user1/Archive.mp4?y=400&preview=1&x=400&c=%22bd8565afa16d3a9484e45c7722cf8a89%22&a=1)

here, i paste the incorrect metric, but every metric in the logs i got for that case were correct. I will repeat anyway.

**Comment by jesmrec** [comment]
Test repeated, with the following result in the current branch

`019-10-23 09:49:22.007000+0200 ownCloud[412:033922] ⚪️ | [HTTP, Local, …] Task [taskIdentifier=<1>, url=http://10.40.40.198:32000/remote.php/dav/files/user1/Archive.mp4] didFinishCollectingMetrics: { total: [2019-10-23 07:42:46 +0000 - 2019-10-23 07:49:22 +0000, 395.48 sec], startedAfter: 0.01, redirects: 0, transactions: [1: fetchStart: 0.01, DNS: 0.06..0.06 (0.00), connect: 0.06..0.07 (0.01), request: 0.07..0.07 (0.00), cloud: 0.07..0.17 (0.10)] } [… PipelineID:default, Instance:0x10d0dd920, HTTP, Metrics, GET, RequestID:1910FB6B-E655-42D8-9B01-3F9AEF6032F0, URLSessionTaskID:1] [OCHTTPPipeline.m:1854|FULL]`

correct timings

**Comment by felix-schwarz** [comment]
@jesmrec Thanks!

**Comment by jesmrec** [comment]
Smoke test checklist

app: `5904205`
sdk: `5996863`

- [X] Basic Auth  
- [X] OAuth2 Auth 
- [X] Transfers (upload & download big files)
- [X] Basic item operations (create folder, copy, move, delete, rename, duplicate, av. offline)
- [X] Public share
- [X] Private share

- [X] Upgrade from 1.1.1 (iOS13 iPhone)
- [X] Upgrade from 1.1.1 (iOS12 iPad)

**Comment by hosy** [comment]
@jesmrec did you also check the file provider (Files.app)?

**Comment by jesmrec** [comment]
In Files App i did not get the metric log for the file. The other metrics related with other requests were correct. Could it be different than downloading in the app? 

The file is correctly downloaded.

**Pull request merged**
