### PR TITLE
[PDF] Search Results Navigation

### PR DESCRIPTION
**Pull request by mneuwert**
## Description
Additional UI is displayed on top of PDF document after the search has been performed. It allows to jump back and forth between found search hits.

## Related Issue
#418 

## Motivation and Context
As a user I would like to be able to jump back and forth between search results to easier find the one I was looking for.

## Screenshots (if appropriate):
Screenshot 2020-11-15 at 21 39 31

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## QA

QA checks: https://github.com/owncloud/ios-app/pull/836#issuecomment-729611334

Bugs & improvements:

- [X] (1)Items selected besides of highlighted https://github.com/owncloud/ios-app/pull/836#issuecomment-729623867   [FIXED]
- [X] (2) Clicking area seems to be small https://github.com/owncloud/ios-app/pull/836#issuecomment-729625931 [FIXED]

### CODE REVIEW

**Review by hosy — APPROVED** [review]

**Comment by hosy** [comment]
@mneuwert Great feature and implementation!

**Comment by jesmrec** [comment]
QA checks:

- [X] 0 results -> no feature
- [X] 1 result -> no navigation
- [ ] +1 result -> navigation displayed portrait
- [ ] +1 result -> navigation displayed landscape
- [ ] Navigation: go forth
- [ ] Navigation: go back
- [ ] Navigation: close

**Comment by jesmrec** [comment]
### (1)

Not sure if this is an issue or a feature:

1. Open PDF
2. Click lens icon to search
3. Enter some string in order to get many results in different pages.
4. Select the first result of the list

Current: 

First result is correctly highlighted:

Screenshot 2020-11-18 at 12 21 47


Browse to the next result with the navigation bar that is in another page. This result is not only highlighted, is also selected:

Screenshot 2020-11-18 at 12 23 12


From now on, while browsing every result will be selected, displaying also the contextual menu. This is not bad, but i stumbled upon glitches like:

Screenshot 2020-11-18 at 12 25 28

in which the contextual menu overlaps the navigation bar

- Is correct that the results are selected instead of highlighted? 
- In case selection is the correct way to do, the first result should be also selected (now, only highlighted)

iPhoneXR iOS14.1
iPadAir2 iPadOS 13.7
`f262bcd`

**Comment by jesmrec** [comment]
### (2)

Another thought that came to my mind while i was checking the feature with the iPhone: i realised that the clicking area around the navigation arrows seems to be kind of small, so the tap must be pretty accurate to navigate. Someone with big fingers could have some problems to use the menu. What do you think?

**Comment by michaelstingl** [comment]
Auto-selection the 2nd result isn’t necessary. Highlighting it would be sufficient.

**Comment by mneuwert** [comment]
@jesmrec 

### Re (1)
Seen this when compiled with Xcode 11.7. With Xcode 12 selection menu doesn't appear when result is highlighted.. And I also can't built with Xcode 11 anymore since @hosy has updated the branch. Tested on iPhone X running iOS 13.6 and iPhone 11 Pro running iOS 14.2.

### Re (2)
Made touch targets slightly bigger

**Comment by jesmrec** [comment]
(1)  Actually, i use Xcode 12.1 (12A7403) to compile. This is not a very bad behaviour or a blocker, but i still reproduce it with iPhone 14.1 and iPad 13.7. Could it be a matter of the iOS version?

(2) fixed

**Comment by mneuwert** [comment]
> (1) Actually, i use Xcode 12.1 (12A7403) to compile. This is not a very bad behaviour or a blocker, but i still reproduce it with iPhone 14.1 and iPad 13.7. Could it be a matter of the iOS version?
> 
> (2) fixed

Regarding (1).. what annoys me the most is that behaviour is inconsistent. I changed the way we jump to a search hit slightly. Lets see if it brings some improvement on your side.. If it doesn't I could just jump to the page where the hit was found, but don't highlight the actual word, then I guess the selection menu won't appear. However it would be harder for the user to follow where on the page the search hit is actually located.

**Comment by jesmrec** [comment]
(1)

checking the last commit `3af51af`, behaviour in both iPad and iPhone has been improved. The selection menu is not there anymore at the time the results are highlighted. 

As you've commented, different devices/version could show tiny differences, but probably, this is something we can improve by iterations in case new feedback arrives to us. 

From my side we can move this forward.

**Comment by mneuwert** [comment]
@jesmrec agree! Thanks!

**Pull request merged**
