### PR TITLE
[fix/branded-state-restoration] Branded Login State Restoration

### PR DESCRIPTION
**Pull request by hosy**
## Description
State restoration was not working for branded clients.

## Related Issue
#957 

## Motivation and Context
Reopen last used items after an app restart.

## How Has This Been Tested?
- open an item 
- set app to background
- force quit app
- restart app
- as a result the last shown item should be reopened
- on the iPad: all windows should be reopened with the last items

Please test this steps in the regular unbranded app and for a branded client like ownCloud Online

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Review by felix-schwarz — APPROVED** [review]

**Comment by ChrisEdS** [comment]
Works not perfectly.

What I see is a screen only with the logo after connecting to the server.

What I have to do to make it work as expected:

1. Connect to the server
2. See a screen only with the logo
3. Quit the app
4. See the manage screen (Access Files, Settings, ...)
5. Go to Access Files
6. Quit the app
7. See the manage screen (Access Files, Settings, ...)
8. Go to Access Files
9. Quit the app
10. See the expected behavior (Files View)

**Comment by hosy** [comment]
@ChrisEdS your issue is unrelated to this PR. It appears, if passcode is enforced. This will be fixed inside the `milestone/11.6` branch.

**Comment by jesmrec** [comment]
### (1)

I see the following behaviour with commit `d38c7c91c`:

1. Open a file
2. Kill the app and open again -> file is displayed
3. Open a different file
4.  Kill the app and open again

Current: The file opened at 2. is displayed:

https://user-images.githubusercontent.com/14894746/116674669-3a6f4200-a9a5-11eb-8404-ae83be51d067.MP4

is that correct? i performed steps fast to record the short video, but, from this moment, every time the app is reopened, the file is displayed

iPhoneXR v14.4

**Comment by hosy** [comment]
@jesmrec  Yes, this is the￼ correct behaviour. If you want to open the second file after a restart, you need to put the app into the background before force quitting the app. ￼

**Comment by jesmrec** [comment]
QA checks:

1. iPhone: open file + kill app + open app -> File displayed
2. iPhone: open 1. file + kill app + open app + open 2. file + kill -> File 1. displayed
3. iPhone: open file + backgorund (homescreen) + open other app + kill + open app -> File displayed
4. iPhone: open 1. file + kill app + open app + open 2. file + background (homescreen) + kill + open app -> File 2. displayed
5. iPad: open file + kill app + open app -> File displayed
6. iPad: open file + background (homescreen) + open other app + kill + open app -> File displayed
7. iPad: open 1. file + kill app + open app + open 2. file + kill + open app -> File 1. displayed
8. iPad: open 1. file + kill app + open app + open 2. file + background (homescreen) + kill + open app -> File 2. displayed
9. iPad Multiwindow: open 2 files in 2 windows + background (homescreen) + kill + open app -> Files displayed

**Comment by jesmrec** [comment]
Will add some checks to regression test.

Approved on my side

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
