### PR TITLE
[feature/feedback-url] Open URL when selecting "Send feedback"

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
Adds `branding.send-feedback-url` class setting to provide a URL to open when selecting _Send feedback_. The string supports the same template elements as `http.user-agent`.

`Branding.plist` example:
```
<key>branding.send-feedback-url</key>
<string>https://www.owncloud.com/?appVersion={{app.version}}</string>
```

#### Template for composed emails - and what's available for `branding.send-feedback-url`
If `branding.send-feedback-url` is not provided, _Send feedback_ would compose an empty email to `branding.send-feedback-address` with the following subject:

```
{{app.version}} ({{app.build}}) BUILD_TYPE APP_NAMEAPP_SUFFIX
```

These placeholders are supported by `branding.send-feedback-url`:
- `{{app.version}}`
- `{{app.build}}`

These are **not** supported and would need to be hardcoded into `branding.send-feedback-url`:
- `BUILD_TYPE` (`release` or `beta`)
- `APP_NAME` (f.ex. `ownCloud`)
- `APP_SUFFIX` (either empty or `-emm`).

## Related Issue
https://github.com/owncloud/enterprise/issues/4726

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by hosy — APPROVED** [review]

**Comment by jesmrec** [comment]
QA checks:

url means `branding.send-feedback-url`
address means `branding.send-feedback-address`

- [ ] address contains an email address, url non existing -> Feedback sends email to the address
- [ ] address contains an email address, url existing and empty ->  Feedback sends email to the address
- [ ] address contains an email address, url existing containing an URL -> 
- [ ] address empty, url existing containing an URL -> URL is open
- [ ] address non existing, url existing containing an URL -> URL is open

**Comment by jesmrec** [comment]
note for myself: 

`branding.send-feedback-url` intended to have more priority than `branding.send-feedback-address`

**Comment by jesmrec** [comment]
One question about the description above:

> If branding.send-feedback-url is not provided, Send feedback would compose an empty email to branding.send-feedback-address with the following subject:

> {{app.version}} ({{app.build}}) BUILD_TYPE APP_NAMEAPP_SUFFIX

as you described, `BUILD_TYPE` and `APP_NAMEAPP_SUFFIX` must be hardcoded into `branding.send-feedback-url`

but, the email is only composed if `branding.send-feedback-url` is not provided. 

@felix-schwarz could you clarify, please? thanks in advance.

**Comment by hosy** [comment]
@jesmrec I do not understand your last question. Please can you describe in detail?

Composing a mail is working like before this PR. If `branding.send-feedback-url` was given, composing a email inside the app is not possible and the `branding.send-feedback-url` will be opened, with the (optional) hardcoded parameters `BUILD_TYPE` and `APP_NAMEAPP_SUFFIX`.

**Comment by felix-schwarz** [comment]
@jesmrec Under `Template for composed emails…`, I tried to document:
- what the contents of the email that is composed by `Send feedback` looks like if `branding.send-feedback-url` is not used
- when using `branding.send-feedback-url`: how to mimic that content as closely as possible using template support for that config parameter - and what is not available as template fields there.

Since `branding.send-feedback-url` will only be used for specific apps, hard coding `BUILD_TYPE`, `APP_NAME` and `APP_SUFFIX` into the provided URL should not be a problem.

**Comment by jesmrec** [comment]
Thanks for the response.

Testing is complete, then.

Approved on my side

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
