### PR TITLE
Added support for additional mime-types

### PR DESCRIPTION
**Pull request by hosy**
## Description
Support to support further mime-types in WKWebView:
application/javascript, application/json, application/octet-stream, application/x-php

## Related Issue
#315 

## Motivation and Context
As a user, I want to see as much file previews directly in ownCloud app.

## How Has This Been Tested?
Copy the following file types into your ownCloud:
- JavaScript
- JSON
- PHP
- Swift, Objective-C

In detail view, all files should be previewed.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jesmrec** [comment]
Checked files:

- [X] JavaScript
- [X] JSON
- [X] PHP
- [ ] XML
- [X] Swift
- [X] Objective-C

@hosy, with XML files i see a blank. The mime type is text/xml

**Comment by jesmrec** [comment]
In case of XML files, if they are not supported (or whatever the reason) by the web view, we should not open them. I have checked with different XML files, and most of them are shown as blanks. Till the web view supports such kind of files, maybe is better to keep the details view for them.

**Comment by hosy** [comment]
@jesmrec XML mime type was removed

**Comment by jesmrec** [comment]
re-checked and everything OK 

Approved

**Pull request merged**
