### PR TITLE
[feature/disable-fileprovider] Disable access to File Provider via MDM

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
Adds a new MDM option `fileprovider.browseable` that:
- brings up an error message when entering the File Provider in the Files.app
- brings up an error when trying to save a file via the "Save to Files" iOS share action
- brings up an error when trying to create a folder via the "Save to Files" iOS share action

## Usage
Add this option to the `Branding.plist` or via MDM:
```xml
<key>fileprovider.browseable</key>
<false/>
```

## Related Issue
https://github.com/owncloud/enterprise/issues/5371

## Screenshots (if appropriate):
Files.app | Import via "Save to files" | Create folder via "Save to files"
--|--|--
Simulator Screen Shot - iPhone SE (3rd generation) - 2022-09-25 at 12 32 24 | Simulator Screen Shot - iPhone SE (3rd generation) - 2022-09-25 at 12 32 40 | Simulator Screen Shot - iPhone SE (3rd generation) - 2022-09-25 at 12 32 35

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by jesmrec** [comment]
QA checks:

1. `fileprovider.browseable = false`
  - [ ] Open Files App without passcode -> Not allowed
  - [ ] Open Files App with passcode -> Not allowed
  - [ ] Save file to Files App -> Not allowed
  - [ ] Create folder via "Save files"  -> Not allowed
  - [ ] UI -> new view correct with all themes

2. `fileprovider.browseable = true`
  - [ ] Open Files App without passcode -> Allowed
  - [ ] Open Files App with passcode -> Allowed
  - [ ] Save file to Files App -> Allowed
  - [ ] Create folder via "Save files"  -> Allowed

**Comment by jesmrec** [comment]
just a comment: when the branding option is `false` and Files App is opened, the authentication view (to trigger the passcode/ biometrical) is showed before the warning of Files App disabled, no matter if the unlocking methods are enabled or disabled in the app. With steps:

1. Set `fileprovider.browseable = false`
2. In app, disable passcode / biometrical
3. Open Files App

Current: Authentication view, before the warning. 

This is not a bad behaviour or blocker at all. Just to confirm this is expected.

**Comment by felix-schwarz** [comment]
@jesmrec If you open the Files app and it is already "open" in the ownCloud File Provider, that is the expected behaviour.

But if you pick "ownCloud" from the list of available file providers (next to "iCloud Drive", "My device", etc.) in the Files app, the UI with the error message should pop up right away.

**Comment by jesmrec** [comment]
> But if you pick "ownCloud" from the list of available file providers (next to "iCloud Drive", "My device", etc.) in the Files app, the UI with the error message should pop up right away.

Right, if you cancel the error message view, the "authentication required" is there again to be clicked.

So, the "authentication required" view in this context is kind of mandatory somehow, no matter if locking is enabled or not (its regular use). As commented, this is OK anyway for me. Main requirement (preventing use of Files App) is fulfilled with no bad behaviours.

**Review by hosy — APPROVED** [review]

**Review by jesmrec — APPROVED** [review]

**Comment by felix-schwarz** [comment]
Merged into #1162. No longer destined to be merged in 11.x outside of special builds.

**Pull request closed without merging**
