### PR TITLE
[feature/suffix-protection] File extension / suffix protection

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
Prevents users from removing or changing the suffix for:
- [x] new documents
- [x] document scanner

## Related Issue
#1292

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by hosy — APPROVED** [review]

**Comment by jesmrec** [comment]
QA checks:

- [ ] New document
- [ ] Document scanner

**Comment by jesmrec** [comment]
QA checks:

- [ ] New document
- [ ] Document scanner

**Comment by jesmrec** [comment]
### (2)

Following the line of (1), if creating new document with empty name (just the extension), it works and creates the file as `.docx` (f .ex), that's a hidden file name. Should we prevent this? or let users do that? If they do that and the setting for hidden files is not enabled, file will not be listed (that's correct) but could be confusing.

feature or bug?

**Comment by michaelstingl** [comment]
> ### (2)
> Following the line of (1), if creating new document with empty name (just the extension), it works and creates the file as `.docx` (f .ex), that's a hidden file name. Should we prevent this?

Okay for now 👍

**Comment by felix-schwarz** [comment]
@jesmrec Good catch on (2)! Disabling the Save button for filenames consisting of just the suffix was easy to implement, so I went for it.

(1) was a lingering bug computing a conflict-free filenames.

Both are fixed as of 5b57fda.

**Comment by jesmrec** [comment]
(1) and (2) both fixed.

**Comment by jesmrec** [comment]
This is approved on my side

**Review by jesmrec — APPROVED** [review]

**Review by JoKacar — APPROVED** [review]

**Pull request merged**
