### PR TITLE
[feature/postbuild-settings] Postbuild Settings

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
Postbuild settings allow modification of branding and class settings via URL scheme, allowing to quickly iterate during development without the need to rebuild the app.

### Enabling the feature
By default, it is not possible to set/change branding or class setting values.

To allow changes, the allowed changes need to be allowed - either specifically or generally - through the setting `post-build.allowed-settings` as an array of setting identifiers. 

Examples:
#### Allow changing the app name (`branding.app-name`)
```xml
<key>post-build.allowed-settings</key>
<array>
	<string>branding.app-name</string>
</array>
```

#### Allow changing ALL settings
```xml
<key>post-build.allowed-settings</key>
<array>
	<string>*</string>
</array>
```

### Changing values
Values can be changed by entering a URL following this pattern into Safari on the device/Simulator:
```
[scheme]://pb/[set|clear]/[all|settingID]/?[int|string|sarray]=[value]
```

#### Examples
Action | URL
--|--
Change app name to `ocisCloud` | `owncloud://pb/set/branding.app-name?string=ocisCloud`
Clear changed app name | `owncloud://pb/clear/branding.app-name`
Set example option to int value | `owncloud://pb/set/example.option?int=1`
Set example option to string value | `owncloud://pb/set/example.option?string=str`
Set example option to string array | `owncloud://pb/set/example.option?sarray=str1,str2,str3`
Clear all changes | `owncloud://pb/clear/all`

If a change was made, a notification will be shown. Tapping on that notification will terminate the app - and tapping on a subsequently appearing notification will re-launch the app.

If a change was not applied - f.ex. due to a lack of permissions - no notification will be shown.

## Screenshots (if appropriate):
Before change | Notification after entering `owncloud://pb/set/branding.app-name?string=ocisCloud` into Safari | After tapping the notification | After tapping the launch notification, the app now calls itself `ocisCloud`
--|--|--|--
Simulator Screen Shot - iPad (10th generation) - 2023-01-16 at 22 30 57 | Simulator Screen Shot - iPad (10th generation) - 2023-01-16 at 22 31 08 | Simulator Screen Shot - iPad (10th generation) - 2023-01-16 at 22 31 11 | Simulator Screen Shot - iPad (10th generation) - 2023-01-16 at 22 31 16

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by hosy — APPROVED** [review]

**Comment by hosy** [comment]
@felix-schwarz from my side this is ready and could be merged. Is there QA needed @jesmrec?

**Comment by jesmrec** [comment]
will take a look, just in case.

**Comment by jesmrec** [comment]
QA checks

- [ ] Allow all + set app name -> name set in the app (notifications in screen)
- [ ] Allow all + set app name + clear name ->  name cleared (notifications in screen)
- [ ] Allow all + set app name + clear all ->  name cleared (notifications in screen)
- [ ] Allow name + set app name -> name set in the app (notifications in screen)
- [ ] Allow name + set app name  + clear name -> name cleared (notifications in screen)
- [ ] Allow name + set app name  + clear all -> name cleared (notifications in screen)
- [ ] Don't Allow name + set app name -> name not set in the app (no notifications)

**Comment by jesmrec** [comment]
### (1)

Check this scenario out

1. Allow all settings to be post-setup:

```
<key>post-build.allowed-settings</key>
<array>
	<string>*</string>
</array>
```
2. Build the app
3. Send via Safari a new app name: `owncloud://pb/set/branding.app-name?string=testExample`
4. Send via Safari a "clear app name: `owncloud://pb/clear/branding.app-name`
5. Send via Safari a new app name: `owncloud://pb/set/branding.app-name?string=testExample2`

Current: app seems to close and new app name is not applied. It's like it works only the first time
Expected: New app name applied

NOTE: if step 4. is done with the `clear/all` instead of `crear/branding.app-name`, it works fine.

iPhone XR v16
`8d4be6b39`

**Comment by jesmrec** [comment]
### (2)

is there somewhere a correct list of available branding parameters to be applied here?

**Comment by michaelstingl** [comment]
> ### (2)
> is there somewhere a correct list of available branding parameters to be applied here?

Some parameters can't be changed dynamically. This is the case for some [Build Options](https://doc.owncloud.com/ios-app/next/appendices/mdm.html#build-options), and probably some [Branding Parameters](https://doc.owncloud.com/ios-app/next/appendices/mdm.html#branding-parameters) are affected too. It could be clarified in the description of each parameter.

**Comment by felix-schwarz** [comment]
@jesmrec Regarding the issues:

(1) I could not reproduce this.

Have you applied `post-build.allowed-settings=*` via `Branding.plist` or via Xcode env variables? If it's the latter, that would explain the issue, since env vars are only used while the app is being run from Xcode. Once the apps quits and relaunches outside of Xcode, env vars are gone and no longer have any effect.

(2) All settings that work in `Branding.plist` should also work here - provided they are allowed via `post-build.allowed-settings` - with the exception of `build.flags` or other options that influence the build process of the app.

**Comment by jesmrec** [comment]
@felix-schwarz about (1), i managed to reproduce it with the iPhoneXR (iOS16.3), so i tried with iPadOS (iPadOS15), and a simulator with iOS 16.2. In the iPad and simulator i do not reproduce the problem

This is how i reproduced it with the iPhone:

 i've used the following setup in `Branding.plist`, not the env. variables

```
<key>post-build.allowed-settings</key>
	<array>
		<string>branding.app-name</string>
	</array>
```

and a video with the steps. Initially, `ownCloud` is the app name. Then changed to `ocisCloud`, then cleared, and set again with the same command:

https://user-images.githubusercontent.com/14894746/217197936-94ebea63-3c2c-447f-b08c-966ef712e73f.MP4

I caught some logs in which you will find a `CRASH` (i hope it helps). 

[ownCloud_7_Feb_2023_at_10_44_59.log.txt](https://github.com/owncloud/ios-app/files/10673656/ownCloud_7_Feb_2023_at_10_44_59.log.txt)

**Comment by felix-schwarz** [comment]
@jesmrec Thanks for the video and the crash log. I just pushed an update that fixes the issue. Please let me know if it fixes the issue for you, too, so I can merge the PR into `feature/new-navigation`.

**Comment by jesmrec** [comment]
@felix-schwarz last commit does not build in Xcode. Errors like:

Screenshot 2023-02-07 at 13 29 39

**Comment by felix-schwarz** [comment]
@jesmrec Sorry. I overlooked API changes in other places. Fixed by merging the changes from `feature/new-navigation` into this PR. It builds now.

**Comment by jesmrec** [comment]
@felix-schwarz thanks for fixing the building problem, now the branch builds. 

But, with the latest commit (`b8398a66`), the parameters are not applied as before, no notifications... was something missing after merging the big branch inside this one?

https://user-images.githubusercontent.com/14894746/217475415-7d11da29-4304-4868-8e4b-8e66ade9de89.MP4

**Comment by felix-schwarz** [comment]
@jesmrec I did a quick test after merging and it worked. Do you have the options in `Branding.plist` still in place?

**Comment by jesmrec** [comment]
OMG, you are right @felix-schwarz, i checked out the branch, losing the changes in `Branding.plist`. Then i forgot to add them again. 

Everything in place, checked with the app name and fine. 

From my side, you can move this forward 👍

**Review by jesmrec — APPROVED** [review]

**Comment by felix-schwarz** [comment]
@jesmrec No problem. Thanks for testing!

**Comment by felix-schwarz** [comment]
Merged into #1162.

**Pull request closed without merging**
