### PR TITLE
Permission increasing UX in reshares

### PR DESCRIPTION
**Pull request by mneuwert**
## Description
See related issue

## Related Issue
#439 

## How Has This Been Tested?
Tested as described in the original issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## QA

Test plan:

https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%201.1.0/Permission%20increasing%20UX.md

Bugs & improvements:

- [X] (1) Files resharing edit permission https://github.com/owncloud/ios-app/pull/467#issuecomment-519469425 [FIXED]
- [X] (2) Re-enabling edit permissions resets the subpermissions https://github.com/owncloud/ios-app/pull/467#issuecomment-519473168 [FIXED]
- [X] (3) Resharing with public link https://github.com/owncloud/ios-app/pull/467#issuecomment-519481346 [FIXED]
- [X] (4) Increasing permissions in resharing https://github.com/owncloud/ios-app/pull/467#issuecomment-521917601 [FIXED]

### CODE REVIEW

**Comment by mneuwert** [comment]
@jesmrec please check from QA perspective

**Comment by jesmrec** [comment]
### (1)

1. Share a file grating sharing, revoking editing
2. Recipient reshares the file

Current: option `Can Edit and Change` is displayed
Expected:  option `Can Edit and Change` is not displayed, since the recipient is not allowed to edit.

**Comment by jesmrec** [comment]
### (2)

1. User1 shares a folder with User2, granting "share" and "create", revoking "change" and "delete"
2. User2 shares the folder with User3 -> he sees only "create" 
3. User2 unchecks "edit", and checks it again

Current: "create" is hidden. By saving, the error of increasing permissions is displayed. Permissions are set to 31.

Expected: create is displayed, change and delete are hidden and disabled. By saving, no errors are displayed. Permissions are set to 21.

**Comment by jesmrec** [comment]
### (3)

Increasing of permissions also affects when the recipient creates a public link over the shared content. For example:

1. User1 shares a folder with User2, granting "share" and "create", revoking "change" and "delete"
2. User2 create a public link over the folder. 

In this case, the permission over the folder is 5: read (1) + create(4). Permissions over the public link are handled in the following way:

- Download/View: this is permission 1. We are not increasing, so this permission can be granted and have to be displayed

- Download/View/Upload: this is permission 15: read (1) + update (2) + create (4) + delete (8). In this case we are increasing the granted permission (5), so this permission is not allowed for the public link, and must not be displayed

- Upload only (File Drop): this is permission 4: create (4). We are not increasing, so this permission can be granted and have to be displayed.

These behaviours were not explicitly mentioned in the original issue, so, the can be addressed in a separate issue for "increasing permissions when create public shares". If you'd rather to fix in the current, it is also OK for me.

**Comment by mneuwert** [comment]
@jesmrec Regarding (3)... now I have added code to correctly handle creation of public links from shared items. Now the link will inherit the share permissions in the same way web UI does.

**Comment by jesmrec** [comment]
### (4)

1. Share a folder with a user, granting change and sharing. Create a public share on the shared folder.

Web UI permissions:

Screenshot 2019-08-16 at 09 29 51

App permissions: 

Screenshot 2019-08-16 at 09 30 53

Expected: "Upload only" permission (4) can not be granted since it exceeds the change permission (2). It should be hidden

NOTE: same happens if the permissions granted in step 1. are delete and sharing.

**Comment by mneuwert** [comment]
@jesmrec Fixed (4), was a small copy / paste issue in the code

**Comment by mneuwert** [comment]
@jesmrec findings (1) and (2) shall be fixed with commit 77e6bc1954fa221a48fce685bb9116c8080fc2d7

**Comment by jesmrec** [comment]
Everything fixed.

Approved

**Pull request merged**
