### PR TITLE
Feature/more

### PR DESCRIPTION
**Pull request by pablocarmu**
## Description

This PR makes a new view for actions instead of swipes.

## Related Issue

https://github.com/owncloud/ios-app/issues/82

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jesmrec** [comment]
@pablocarmu why is the file name twice at the right of the thumbnail:

screen shot 2018-08-20 at 14 52 38

**Comment by jesmrec** [comment]
View in landscape with iPhone X:

screen shot 2018-08-20 at 15 05 35

the `Action` label is too close to the notch

**Comment by michaelstingl** [comment]
I think we discussed this on Friday: Maybe keep same margin from left as in the file list.

**Comment by jesmrec** [comment]
All stuff fixed. OK from side

**Comment by felix-schwarz** [comment]
Started reviewing and, using the default theme, I'm getting this:
bildschirmfoto 2018-08-23 um 20 35 01

Can you reproduce that?

**Comment by jesmrec** [comment]
Approved

**Pull request merged**
