### PR TITLE
[fix/shortcut-save-file]

### PR DESCRIPTION
**Pull request by hosy**
## Description
File could to be saved, when trying to save a file with Shortcuts and it already exists

## Related Issue
#622 

## How Has This Been Tested?
Check Issue #622 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jesmrec** [comment]
The fix directly overwrites the existing file in the same path. This behaviour can be dangerous and lead to data loss. Should it be better to create a new file with the incremental number (same as uploading twice the same file)?

**Comment by hosy** [comment]
@jesmrec yes, this is exactly what it should do, because as I user I want to write data to the same file.
If you do not agree, we can add a parameter `Overwrite if already exists` with `YES/NO`, to prevent overwriting, if it should not. What do you think?

**Comment by jesmrec** [comment]
It sounds good. So, the user can decide to overwrite the latest version or keep it by creating a new one.

**Comment by hosy** [comment]
@jesmrec new parameter was added, please check again

**Comment by jesmrec** [comment]
Works properly when  `Overwrite existing file` is enabled and disabled. And it is good to have that this is disabled by default, so the user has to decide explicitly if the file will be overwritten.

Approved.

**Pull request merged**
