### PR TITLE
Update CONFIGURATION.json

### PR DESCRIPTION
**Pull request by mmattel**
## Description
Fix the link for `doc/BUILD_CUSTOMIZATION.md` as this renders as text and results to nowhere.

Seen while working on the issue below.

## Related Issue
Referencing: https://github.com/owncloud/docs/issues/4480 (Hard to interpret the dashes because of line breaks)

## Motivation and Context
Improve rendered result

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Comment by michaelstingl** [comment]
This file is autogenerated. Don’t change manually!!

**Comment by mmattel** [comment]
@michaelstingl in this case it would be great if you fix the source with the changed content and link it to the PR so it can be tracked.

**Comment by michaelstingl** [comment]
> @michaelstingl in this case it would be great if you fix the source with the changed content and link it to the PR so it can be tracked.

Sure. Please open issue for tracking.

**Comment by mmattel** [comment]
> Sure. Please open issue for tracking.

Done

**Pull request closed without merging**
