### PR TITLE
Fix flexible header height in MoreViewHeader / cards

### PR DESCRIPTION
**Pull request by felix-schwarz**
- fixes an issue where the title in the header of a card view using a MoreViewController would be cut off.
- adds a useful NSLayoutConstraint extension to change the priority on the fly
- removes line_length limit from SwiftLint rules as a higher limit of 300 doesn't work - and the limit of 200 often makes for worse formatting

screenshot 2018-09-04 at 11 06 42

### CODE REVIEW

**Comment by jesmrec** [comment]
Let's start a new review over the `More`

**Comment by jesmrec** [comment]
In landscape, the options in the card are cut:

sep-06-2018 11-01-20

**Comment by felix-schwarz** [comment]
@jesmrec Thanks!

Does that happen when
a) in landscape mode and tapping the "more-dots" .. or ..
b) switching from portrait to landscape mode when already in the "more" view?

**Comment by jesmrec** [comment]
@felix-schwarz with the following steps i can reproduce it:

1.- Device in portrait. Open the card
2.- With card opened, switch to landscape -> Card is visible correctly
3.- Swipe the card to the top of the screen and release like here: https://github.com/owncloud/ios-app/pull/113#issuecomment-419020392

**Comment by felix-schwarz** [comment]
@jesmrec Thanks!

I tried with an iPhone 6s, 6s Plus and X and couldn't reproduce the issue: 
owncloudcardresizingafterrotation

IIRC a previous commit had that issue. Can you try again with the latest commit?

**Comment by jesmrec** [comment]
i will try

**Comment by jesmrec** [comment]
i have tried out, and also reviewed your gif @felix-schwarz. Just in the moment you change the orientation to landscape, the `Delete` option is not visible, only the `Rename` one. This is the frame: 

screen shot 2018-09-28 at 12 52 02

After that, each time the card is pulled up/down, the options are correctly displayed.

Checking in iOS12, i noticed that in the reverse case (switching from landscape -> portrait): If the name is long, by pulling up the card, the options are not visible:

ezgif com-optimize

**Comment by felix-schwarz** [comment]
@jesmrec With the latest commit, the issue should now be fixed and from my point of view can be merged.

**Comment by jesmrec** [comment]
fixed. Moving forward...

**Pull request merged**
