### PR TITLE
[Release] 1.0.2

### PR DESCRIPTION
**Pull request by hosy**
PR for next release 1.0.2, will include all fixes and QA findings

Release a new version
### Git & Code

- [X] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [ ] [TRFX] Update translations from transifex branch.
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [X] [QA] Design Test plan
- [x] [QA] Regression Test plan -> Not needed, checklist is enough
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code) 
- [ ] [mail] inform #marketing about the new release.
- [x] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [x] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [x] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [x] [DIS] Upload the binary to the App Store
- [x] [DIS] App Store Connect: Trigger release (manually)
- [x] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [x] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [x] [DIS] App Store Connect: Update changelogs
- [x] [DIS] App Store Connect: Submit for review

___

bugs & improvements

- [X] #423 
- [x] #424
- [x] #425 
- [x] #437 
- [x] Smoke test
- [x] Upgrade check from 1.0.1

### CODE REVIEW

**Comment by jesmrec** [comment]
Related with #423

Crash is fixed, but the list of favourites is empty, even with favourites in the web UI. By waiting some minutes, the list is filled up.

**Comment by hosy** [comment]
> Related with #423
> 
> Crash is fixed, but the list of favourites is empty, even with favourites in the web UI. By waiting some minutes, the list is filled up.

For me the favorites will appear immediately but I think this has something to do with the initially scan. @felix-schwarz is it possible to load the favorites immediately?

**Comment by jesmrec** [comment]
Issues included:

#423 -> Fixed
#424 #425 -> Done
#437 -> Different checks:
- [X] Token granted -> OK
- [X] Token renewed via refresh token -> OK
- [X] Token revoked via web -> OK (user asked to re-authenticate)

Smoke test:

- [X] Authentication basic
- [X] Authentication OAuth2
- [X] Upload from albums
- [X] Upload from Files App
- [X] Download files
- [X] Basic operations: create folder, rename, move, copy, delete, duplicate
- [X] Share with users/group
- [X] Share by link

Upgrades

- [ ] 1.0.1 -> 1.02

**Review by jesmrec — APPROVED** [review]

**Review by felix-schwarz — APPROVED** [review]
Technical approval to allow merge.

**Pull request merged**
