### PR TITLE
[fix/rtl-ui-adaptions] Improved Right-to-Left Language UI-Design

### PR DESCRIPTION
**Pull request by hosy**
## Description
This PR improves the UI-Design for Right-to-Left languages.
The most views were already prepared for RTL support, but we had some missing UI elements, which were not ready for RTL.

## Related Issue
#861 

## Motivation and Context
Give users which are on a Right-to-Left language a perfect UI experience.

## How Has This Been Tested?
Change language to `Arabic` and check if view design is mirrored compared to the Left-to-Right UI design.
Please have a look at the `Screenshots` section, which elements were changed:
- Account list
- Settings (Mostly rows on the bottom)
- File list
- File list sort bar
- Sort popover
- More menu
- Account to file list animation direction

## Screenshots:
| English Left-to-Right                                                                                                  | Arabic Fixed Right-to-Left                                                                                              | Arabic Outdated Right-to-Left                                                                                           |
|------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|
| en_accountlist | new_accountlist | old_accountlist |
| en_filelist    | new_filelist    | old_filelist    |
| en_more_menu   | new_more_menu   | old_more_menu   |
| en_settings    | new_settings    | old_settings    |
| en_sortbar     | new_sortbar     | old_sortbar     |

### Push Animation

| Wrong Push Animation Direction                                                                                               | Fixed Push Animation Direction                                                                                               |
|------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------|
| ezgif-7-ab3d5008f72d | ezgif-7-9352b3fde683 |

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by felix-schwarz — CHANGES_REQUESTED** [review]
Looks fine, except the position of the icons in the action card in both LTR and RTL should be the other way round than this:

| English Left-to-Right                                                                                                  | Arabic Fixed Right-to-Left                                                                                              | Arabic Outdated Right-to-Left                                                                                           |
|------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|
| en_more_menu   | new_more_menu   | old_more_menu   |

If there is no other way, we may need to take care of the view layout for these `StaticTableViewRow` type(s). Don't hesitate to let me know if I can help.

**Comment by hosy** [comment]
> Looks fine, except the position of the icons in the action card in both LTR and RTL should be the other way round than this:
> 

> If there is no other way, we may need to take care of the view layout for these `StaticTableViewRow` type(s). Don't hesitate to let me know if I can help.

I changed the icon position from the left side to the right side (LTR), to adopt this to the UIMenu. So in RTL the icon position on the left side is correct. You can see, it is mirrored to the LTR design.

Simulator Screen Shot - iPhone 12 - 2021-01-14 at 13 59 56

**Comment by felix-schwarz** [comment]
I wish iOS itself was more consistent there:
- for alerts (like we use when hitting the "+" button inside a folder), it presents the icons on the left
- for context menus, it presents them on the right
- for the share sheet, it shows them on the right

Alerts are the oldest of these three design patterns, and the other two are both much newer and much closer to our "card" view. So yeah, you're absolutely right and the change of position for the icons is actually more in line with recent iOS design. Maybe I've gotten used to the icons being in the left spot for too long now :-D

Approved!

**Review by felix-schwarz — APPROVED** [review]

**Comment by hosy** [comment]
@felix-schwarz you are right! With iOS 14 we should remove this view with the `UIMenu` implementation.

**Comment by jesmrec** [comment]
I performed some exploratory testing through the app to check if views'  layout is RTL. I put only focus in the view, no features were tested/checked. 

From my side this is approved.

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
