### PR TITLE
Display view: use complete screen height

### PR DESCRIPTION
**Pull request by hosy**
## Description
Screen height is not fully used and bottom bar does not look nice

## Related Issue
#303 

## Motivation and Context
Better usage of the screen

## How Has This Been Tested?
look at the issue description

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jesmrec** [comment]
Portrait images are not correctly scaled to the screen size:

Before:

screen shot 2019-03-07 at 09 22 08


Now (top is overlapped with the upper bar):

screen shot 2019-03-07 at 09 26 29

**Comment by hosy** [comment]
For me this is an other bug and has nothing to do with this fix.

**Comment by jesmrec** [comment]
If this is a platform bug, i would keep the current approach till the problem is fixed.

**Comment by jesmrec** [comment]
@hosy, after merging `image_gallery` could you rebase the branch against `master` so we can check the current feature together with the gallery? thanks.

**Comment by jesmrec** [comment]
after upgrading with gallery, behaviour is correct.

Tests over the branch ran locally and on bitrise

Approved on my side.

**Pull request merged**
