### PR TITLE
[feature/autoconnect] Auto-connect support

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
Saves the last opened account and automatically reconnects to it on next launch unless the user has logged out of the account in the meantime.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## QA

https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%201.0.2/Autoconnection.md

### CODE REVIEW

**Review by mneuwert — APPROVED** [review]

**Comment by michaelstingl** [comment]
Related issue: https://github.com/owncloud/ios-app/issues/424

**Comment by michaelstingl** [comment]
Is the settings screen now too difficult to discover?

**Comment by felix-schwarz** [comment]
Since users see the transition from account list into the account on launch (providing a sense of place), I wouldn't think so.

**Comment by hosy** [comment]
@felix-schwarz please can you try to add "Accounts" as back label to the navigation controller?

**Review by jesmrec — APPROVED** [review]

**Comment by felix-schwarz** [comment]
> @felix-schwarz please can you try to add "Accounts" as back label to the navigation controller?

Done:

Bildschirmfoto 2019-07-02 um 23 23 02

If the name of the account is very long, however, iOS will not show the back button label:
Bildschirmfoto 2019-07-02 um 23 25 14

**Comment by jesmrec** [comment]
With the commit  `12c60ca` and iPhoneX, wording is different:

iPhone: `Back`
iPad: `Accounts`

Jul-03-2019 08-42-24

Jul-03-2019 08-43-59

**Comment by hosy** [comment]
> With the commit `12c60ca` and iPhoneX, wording is different:
> 
> iPhone: `Back`
> iPad: `Accounts`

@jesmrec please can you recheck it again. I tested all device sizes in simulator and everything will show "Accounts", if the server name is not too long.

**Review by hosy — APPROVED** [review]

**Comment by jesmrec** [comment]
Rechecked with iPhoneX and same result. In the following GIF you can check the commit hash as well:

Jul-03-2019 10-25-10

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
