### PR TITLE
[fix/collapsible-progress-bar-position] Collapsible Progress Bar in Detail View

### PR DESCRIPTION
**Pull request by hosy**
## Description
This PR fixes the misplaced Collapsible Progress Bar in Detail View

## Related Issue
#906 

## Screenshots (if appropriate):

| Before                                                                                                                                                                                       | Updated                                                                                                                                                                                      | Updated in Full screen                                                                                                                                                                       |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-02-23 at 15 24 56 | Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-02-23 at 15 23 51 | Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-02-23 at 15 23 56 |

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Comment by felix-schwarz** [comment]
Thanks for tackling this tricky problem!

I found a number of visual glitches and possibly unwanted behaviour - like f.ex. the progress bar being shown at all times in the viewer unless the user dismisses the navigation bar - and wondered what needs to be done to address them.

I ended up looking for the root causes and putting together `fix/collapsible-progress-bar-position-flex` starting from your changes. That branch hides the progress bar aggressively and animates its position and size alongside transitions from the `UINavigationController`.

If it's ok for you, I'd merge those changes into `fix/collapsible-progress-bar-position` and then request a code review from you for these changes.

**Comment by hosy** [comment]
@felix-schwarz  yes, this is ok for me. Looking forward to review your implementation.

**Comment by felix-schwarz** [comment]
@hosy Thanks! I just merged my changes to this branch / PR.

**Comment by felix-schwarz** [comment]
Hmm, looks like I can't add you as reviewer. I'll create a new PR.

**Pull request closed without merging**
