### PR TITLE
[fix/branding-login-retry] Retry Section for Branded Login Error

### PR DESCRIPTION
**Pull request by hosy**
## Description
This PR adds a retry section to the branded login, e.g. if a server url could not be reached. In some cases (passcode setup) the error alert could not be presented. This solves the problem and furthermore it adds a `Retry` button to proceed with the login again.

## Related Issue
https://github.com/owncloud/enterprise/issues/4786

## How Has This Been Tested?
- test in branded app
- set a unreachable server url into the `Branding.plist` as server url
- enable passcode enforced 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Comment by hosy** [comment]
@jesmrec problem should be fixed now with latest commit

**Comment by hosy** [comment]
@jesmrec was this one already tested by you? I thought we got positive feedback from the customer?

**Comment by jesmrec** [comment]
i think so, but maybe other one should confirm the customer feelings. I was working on this:

- iPhoneXR with iOS15 -> everything was fine

- iPadAir with iOS14 -> i got a bad behaviour that no other one was able to reproduce with any other device and version, so it was moved forward. Here, i can take another look (does this branch contain the same as the mashup branch?), just in case the problem it's gone. If it persists, maybe the customer feeling should prevail. Open to discussion

**Comment by hosy** [comment]
@jesmrec yes, we figured out, that this was a special problem on your device, with a specific branding configuration. So we can move forward.

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
