### PR TITLE
[milestone/12.0.3] Milestone 12.0.3

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
Implements these changes:
- new: adds `mtime` metadata to TUS uploads
- new: CSS gains variable support (via `experimental/branding`)
- improved: App Provider fixes / feature detection
- fix: update connection name in sidebar after it has been edited
- fix: avoid unwanted Auto Layout collapse of select button in location picker / `BottomButtonBar`
- fix: FileProvider slowness and hangs
- fix: FileProvider crash when being passed a `nil` item identifier by iOS
- updated translations via #1269 

## Related Issues
- https://github.com/owncloud/ios-app/issues/1273
- https://github.com/owncloud/enterprise/issues/5747
- #1227
- #1254
- https://github.com/owncloud/enterprise/issues/5889
- #1240 
- #1262
- #1266

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Comment by jesmrec** [comment]
# QA

This is a bugfixing release, so no complete regression test needed

### Changelog

- [ ] Open in web (oC10) https://github.com/owncloud/enterprise/issues/5747
- [ ] Header `X-OC-mtime` https://github.com/owncloud/ios-app/issues/1227
- [ ] Bookmark name https://github.com/owncloud/ios-app/issues/1254. Fixed??
- [ ] "Copy here” in spaces  https://github.com/owncloud/enterprise/issues/5889
- [ ] Files app issues -> not reproducible on my side. Fixes confirmed by users

### Smoke test


### Upgrade test

**Comment by jesmrec** [comment]
### (1)

Is this look change in the login view expected? Shows a dark login view with  `Light` theme selected (fresh installation)

| 12.0.2 | 12.0.3 |
| :-: | :-: |
|Screen Shot 2023-08-22 at 12 15 28|Screen Shot 2023-08-22 at 12 14 47|

iPhoneXR v16.5.1
`c41b0cc8d9`

**Comment by jesmrec** [comment]
In addition to the comments above, the login view does not look like nice in iOS17. Fix here or in following releases?

Screenshot 2023-08-28 at 08 40 53

**Comment by michaelstingl** [comment]
> In addition to the comments above, the login view does not look like nice in iOS17. Fix here or in following releases?

Uh. not nice. Worse then I expected. I thought color-wise, everything is better in iOS 17… 🤔

**Comment by jesmrec** [comment]
@felix-schwarz was this [fix](https://github.com/owncloud/ios-app/issues/1254) included in the release branch? It is closed but i can reproduce the problem in `b5391b8` . Changes in the name are not applied till apps is reopened.

**Comment by felix-schwarz** [comment]
> @felix-schwarz was this [fix](https://github.com/owncloud/ios-app/issues/1254) included in the release branch? It is closed but i can reproduce the problem in `b5391b8` . Changes in the name are not applied till apps is reopened.

It was merged into `milestone/12.0.3` and closed after @michaelstingl could no longer reproduce the issue after that. I also just tried to reproduce the issue with the latest build but couldn't. Can you share a video?

**Comment by felix-schwarz** [comment]
@jesmrec @michaelstingl All color issues (including status bar) should be fixed as of the latest commit / build.

**Comment by michaelstingl** [comment]
Yeah, rock-solid in iOS 16 + 17, following system dark + light mode  ✅

**Comment by jesmrec** [comment]
> It was merged into milestone/12.0.3 and closed after @michaelstingl could no longer reproduce the issue after that. I also just tried to reproduce the issue with the latest build but couldn't. Can you share a video?

@felix-schwarz here it is:

https://github.com/owncloud/ios-app/assets/14894746/d32ef46d-4ded-4154-80bf-f6b0a3374655

**Comment by jesmrec** [comment]
> @jesmrec @michaelstingl All color issues (including status bar and iOS 17) should be fixed as of the latest commit / build 280.

fixed in `a455ce1dc`. 

Still dark login view, but it will be expected in 12.0.3

**Comment by felix-schwarz** [comment]
@jesmrec Thanks for the video. I can now reproduce it on an iPhone when the bookmark did not have a name previously. Looking into it.

**Comment by jesmrec** [comment]
@felix-schwarz  also, detected this glitch in an iPhoneX. I guess it's caused because the screen width:

Settings  >  Media Upload > Auto Upload Photos -> switch on

Button to select destination is not correct. Curiously, just happens with Auto Upload Photos and not with Videos

Screenshot 2023-08-29 at 10 57 18

iPhoneX 16.5
`a455ce1d`

**Comment by felix-schwarz** [comment]
@jesmrec The rename issue is fixed as of https://github.com/owncloud/ios-app/pull/1236/commits/19329939298f3c5e87e0af51cd4751566081029f.

**Comment by felix-schwarz** [comment]
@jesmrec The layout glitch is also fixed now:
Bildschirmfoto 2023-08-29 um 15 04 18

**Comment by jesmrec** [comment]
Everything fixed

**Comment by jesmrec** [comment]
# QA

This is a bugfixing release, so no complete regression test is required

### Changelog

- [x] Open in web (oC10) https://github.com/owncloud/enterprise/issues/5747
- [x] Header `X-OC-mtime` https://github.com/owncloud/ios-app/issues/1227
- [X] Bookmark name https://github.com/owncloud/ios-app/issues/1254 
- [x] "Copy here” in spaces  https://github.com/owncloud/enterprise/issues/5889
- [x] Files app issues -> not reproducible on my side. Fixes confirmed by users

### Smoke test

**Server version**: [10.13.0](https://hub.docker.com/layers/owncloud/server/10.13/images/sha256-59dc6d256f36db168b18ac104a567eecc5e089eeb2618891a0f055a20da9d536?context=explore) && [4.0.0](https://hub.docker.com/layers/owncloud/ocis/4.0.0/images/sha256-a89891e46031e681b6d32a792bbad1ca3a4671e71edeb6bddb9713d278eb668d?context=explore)
**Device & iOS version**: iPhoneX, iOS 16.5.1 (REAL), iPhone 14, iOS 16.5 (SIM), iPhoneXR 17.0 (REAL)


Test Case | Steps | Expected Result | Result | Related Comment
| :------ | :---- | :-------------- | :----- | :---------
| Login Basic | Login in an oC10 server, typing correct credentials | Access to account |  Passed |  AUTO |
| New folder | Open '+' and select to create a new folder with correct name|The folder is created with the correct name| Passed  | [AUTO](https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber/createfolder.feature) |
| Rename | 1. Select an item by clicking on 3-dot-button<br>2. Select Rename and type new correct name  |  Item is renamed with the new name | Passed | [AUTO](https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber/rename.feature) |
| Move | 1. Select an item by clicking on 3-dot-button<br>2. Select Move, and a new location | Folder is moved to the specified location | Passed | [AUTO](https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber/move.feature) |
| Copy | 1. Select a folder by clicking on 3-dot-button<br>2. Select Copy, and a location to copy to (including space) | The folder and all its content is copied to the location, and also remains in the original | Passed | [AUTO](https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber/copy.feature) |
| Duplicate | 1. Select a folder by clicking on 3-dot-button<br>2. Select Duplicate | The folder and all its content is duplicated in the current location, with the name adding `2`| Passed | [AUTO](https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber/duplicate.feature)
| Delete | 1. Select a folder by clicking on 3-dot-button<br>2. Select Delete and submit deletion | Item deleted |   Passed | [AUTO](https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber/delete.feature) |
| Upload Files| Select many files from File apps to upload to oC | Files are uploaded  | Passed |  [AUTO](https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber/upload.feature)
| Upload Albums | Select 300 images and videos from Albums to upload to oC | Images and videos are uploaded  | Passed
| Download | Tap to download a file | The file is downloaded and previewed |  Passed |
| Av Offline | 1. Select a folder by clicking on 3-dot-button<br>2. Select set as Av Offline file| The file is downloaded and set as Av Offline  | Passed | 
| Av Offline folder | 1. Select a folder with subfolders inside by clicking on 3-dot-button<br>2. Select Av. offline<br>3. Add new content to the folder | 2. The folder and all its content is downloaded and set as Av Offline<br>3. New content is available offline | Passed | 
| Share with user  |  1. Select file and folder by clicking on 3-dot-button<br>2. Select Share and add new recipient<br>3. Recipient accepts the share | Both are correctly shared and visible by the recipient in Shares space   | Passed | [AUTO](https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber/shares.feature)
| Link  | Create a link over a file and a folder | Links are correctly created| Passed | [AUTO](https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber/links.feature) |
| Spaces | 1. In web, create some spaces that are visible for the user | List of spaces is visible in the account | Passed | [AUTO](https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber/spaces.feature) |
| Files App | 1. Add several accounts<br>2. Open Files app | All accounts are correctly listed and are browsable | Passed |  |

[Autom test report vs oCIS](https://reports.cucumber.io/reports/d02b1bc2-a25a-4036-8774-20ac95006349)

[Autom test report vs oC10](https://reports.cucumber.io/reports/6a7c94d9-e4f6-418e-b3f0-684178865b90)

### Upgrade test

12.0.2 -> 12.0.3 with oC10 (basic), oC10 (OAuth2), oCIS (OIDC) ✅ 

Approved commits:

app: `40dfc92`
sdk: `740b63e`

Devices:

iPhoneX 16.6
iPhoneXR 17.0 (just basic checks)

Xcode version: `14.3.1 (14E300c)`

**Review by jesmrec — APPROVED** [review]

**Review by hosy — APPROVED** [review]

**Pull request merged**
