### PR TITLE
Autoplay Media / Show album artwork in the media player view

### PR DESCRIPTION
**Pull request by mneuwert**
## Description
- If there are further media files in the current folder they will enqueued for playing after current item has finished
- If media file contains artwork meta data it will be shown as overlay in the player

## Related Issue
#59 
#374 

## Motivation and Context
Improved UX concerning media playback

## How Has This Been Tested?
Tested with different mp3 files

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## QA

Test plan:

https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%201.2.0/Autoplay%20%26%20Artwork.md

### CODE REVIEW

**Comment by hosy** [comment]
@mneuwert it does not play the next item, if the app is in background. Furthermore do not get player controls in lock screen.

**Comment by mneuwert** [comment]
@hosy strange thing is.. it works in simulator but not on the device. However since `UIKit` is involved, I think current implementation would be hard to get working in the background. The way to go would be to refactor the preview sub-system and allow `DisplayViewController` instances to handle multiple items and then also to use `AVQueuePlayer`. Regarding lock screen controls, I will continue to analyse what is going wrong

**Comment by mneuwert** [comment]
@hosy Fixed the issue with background audio continuity and added even more features to the now playing view in the lock screen:
- Pause / play
- Skip 10 seconds backwards / forwards
- Show artwork, title, artist name

**Comment by hosy** [comment]
@mneuwert great improvement. Thank you!

**Comment by jesmrec** [comment]
Approved.

**Pull request merged**
