### PR TITLE
[feature/settings-metadata] Class Settings Metadata support

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
Support for class settings metadata.

## Related Issue
https://github.com/owncloud/ios-sdk/pull/71
Refresh of https://github.com/owncloud/ios-app/pull/831 (which wouldn't refresh to the latest branch `HEAD`)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## QA

Report: https://github.com/owncloud/ios-app/pull/838#issuecomment-745278147

### CODE REVIEW

**Review by hosy — APPROVED** [review]

**Review by mneuwert — APPROVED** [review]

**Comment by jesmrec** [comment]
### QA [WIP]

The aim of the current PR QA stage is checking how the documentation is generated, not the documentation itself. All entries in the doc will be checked at the time the MDM fields' behaviour is tested.

**1) Script execution**

execution of  `generate_docs.sh` finishes with  **TEST SUCCEEDED**

no problems detected during the execution

**2) JSON file**

The JSON file generated by the script is correctly shaped. Every object contains several fields and meta-fields (do not appear in the final document, but probably needed somehow). It'd be interesting to write somewhere (adoc file, documentation or wherever), about it, so that the reader/system admin/whoever can understand correctly what do they mean.

**3) adoc file**

This is the product of the script. With testing purposes, i've rendered it to html5 by using the `asciidoctor` (just for an easier visualization and comparison)

Document is correctly generated, but not with all objects in the JSON file (this was already reported in the chats). The missing objects are:

- `connection-allowed-authentication-methods` in category `Security`
- `connection.connection-preferred-authentication-methods`  in category `Security`
- `allow-cellular`  in category `Connection`

**Comment by michaelstingl** [comment]
> * `connection-allowed-authentication-methods` in category `Security`
> * `connection.connection-preferred-authentication-methods`  in category `Security`
> * `allow-cellular`  in category `Connection`

@dschmidt this 3 doesn't get picked up from gomplate. They're in JSON, but they aren't in the adoc.

**Comment by michaelstingl** [comment]
@felix-schwarz @mneuwert can we merge this? What's left? Open new issue for the remaining tasks?

**Comment by felix-schwarz** [comment]
@michaelstingl As last addition, I added the space-less `categoryTag`s and merged the PR. The adoc generation issue is still open and now tracked in https://github.com/owncloud/ios-app/issues/854.

**Comment by mneuwert** [comment]
@felix-schwarz After merging your changes and while generating docs with antora I get following warnings:

asciidoctor: WARNING: ios_mdm.adoc: line 37: tag 'actions' not found in include file: modules/ROOT/pages/ios_mdm_tables.adoc
asciidoctor: WARNING: ios_mdm.adoc: line 49: tag 'passcode' not found in include file: modules/ROOT/pages/ios_mdm_tables.adoc
asciidoctor: WARNING: ios_mdm.adoc: line 89: tag 'shortcuts' not found in include file: modules/ROOT/pages/ios_mdm_tables.adoc

**Comment by michaelstingl** [comment]
Are the tags `actions`, `passcode` and `shortcuts` in the JSON?

**Comment by mneuwert** [comment]
@michaelstingl I had to regenerate JSON, so please ignore my previous comment.. Shortcuts need some more implementation work and 'display settings' are missing eventually due to problems in template file...

Latest checked in configuration does include `actions` and `passcode` at least

**Pull request merged**
