### PR TITLE
#283 Fixed Localization in code and localizable.strings

### PR DESCRIPTION
**Pull request by hosy**
## Description
Added missing key, value in localizable strings (en, de, de_DE) and missing localize calls for strings in code.

## Related Issue
#283 

## Motivation and Context
Fix missing localization

## How Has This Been Tested?
- change iOS device language to German 

### File List
- open file list
- right bar button should localized with title "Auswählen"
- select right bar button "Auswählen"
- right bar button should now localized with title "Fertig"

### File List (with wrong account credentials)
- change your account credentials to wrong values
- open file list
- alert will appear
- alert title "Authorization failed" should localized in "Anmeldung fehlgeschlagen"
- alert message "The server declined access with the credentials stored for this connection." should localized in "Der Server verweigerte den Zugriff mit den für diese Verbindung gespeicherten Anmeldeinformationen."

### File Search
- open file list and begin typing into the search field
- enter a search string, which will not match with a file or folder
- label "No matches" should localized in "Keine Treffer"
- label "There is no results for this search" should localized in "Es gibt keine Ergebnisse für diese Suche"

### Create / Rename Folder
- open File list
- create and rename a folder
- add a "/" to the folder name
- alert will appear
- message "File name cannot contain / or \\" should localized in "Dateiname darf nicht / oder \\ enthalten."

### Server List
- open server list
- table header label should localized with title "Konten"

### Pin Lock
- open settings
- label "Pin Lock" should be localized in "PIN-Sperre"

### Theme Names
- open settings
- select "Theme"
- Theme names should localized:
"ownCloud Dark" -> "ownCloud Dunkel"
"ownCloud Light" -> "ownCloud Hell"
"ownCloud Classic" -> "ownCloud Klassik"
- Table Header "Options" should be localized in "Optionen"

### Actions
- open file list
- select "More" action for a file or folder
- "Actions" header label should be localized in "Aktionen"

### Edit Account (by swiping)
- open server list
- swipe left on an account
- "Edit" label should be localized in "Bearbeiten"
- "Credentials" label should be localized in "Zugangsdaten"

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mneuwert** [comment]
@hosy any idea why some .strings files are assigned BINARY file type and therefore the diff is also not displayed?

**Comment by javiergonzper** [comment]
- RenameAction.swift line 53 does not have .localized: `"File name cannot contain / or \\"`
- CreateFolderAction.swift line 57 does not have .localized: `"File name cannot contain / or \\"`

**Comment by hosy** [comment]
> @hosy any idea why some .strings files are assigned BINARY file type and therefore the diff is also not displayed?

I added a .gitattributes file, where I defined to treat *strings files not as binary. Now, this is working locally. I'm not sure, why Github does not interpret these files as text. I did not found any solution for that.

**Comment by jesmrec** [comment]
Tested with the German translation. To consider: 

- Welcome view: the deutsch welcome message overflows the screen bounds:

screen shot 2019-03-04 at 09 20 33

- An small typo: `zustimmen` with capital as `Approve`: 
https://github.com/owncloud/ios-app/blob/9f69d47c55175aa20217d3f537b9ed91c494fa19/ownCloud/Resources/de-DE.lproj/Localizable.strings#L35

**Comment by hosy** [comment]
@jesmrec both fixed. Thank you!

**Comment by jesmrec** [comment]
Approved on my side

**Pull request merged**
