### PR TITLE
[feature/new-issue-view] New Issue view / presentation

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
As fixing an iPad layout issue in the old issues view proved too cumbersome, I've replaced the entire implementation with a new issue view, based on code already there and in use for cards and tables.

The result provides a more modern look, is consistent with the rest of the app and shrinks the code base by ~ 220 lines of code.

## Screenshots (if appropriate):
Previously | Certificate warning
---|---
Simulator Screen Shot - iPhone 8 - 2021-01-23 at 13 13 48 | 

Previously | Error 
---|---
Simulator Screen Shot - iPhone 8 - 2021-01-23 at 13 16 45 | 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## QA

Checklist: https://github.com/owncloud/ios-app/pull/874#issuecomment-767400195

Bugs & improvements:

- [ ] (1) Switching orientations https://github.com/owncloud/ios-app/pull/874#issuecomment-767473713

### CODE REVIEW

**Review by mneuwert — APPROVED** [review]

**Comment by jesmrec** [comment]
QA checks

iPhone

- [ ] "Connection review" portrait
- [ ] "Connection review" landscape
- [X] "Issues" portrait
- [X] "Issues" landscape

iPad

- [ ] "Connection review" portrait
- [ ] "Connection review" landscape
- [ ] "Issues" portrait
- [ ] "Issues" landscape

**Comment by jesmrec** [comment]
### (1)

The `Review Connection` message when http connection is stablished in landscape

Screen Shot 2021-01-26 at 12 05 00

text does not fit correctly to the background yellow chart.

If portrait mode is set again after landscape:

Screen Shot 2021-01-26 at 12 05 05

iPhoneXR iOS14
iPadAir iOS13

**Comment by felix-schwarz** [comment]
@jesmrec Thanks. I could reproduce this only when rotating the device. It boiled down to iOS not respecting the provided margins after rotating the table cell view. Fixed as of 83eeab1.

**Comment by jesmrec** [comment]
Totally fixed. Approved on my side

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
