### PR TITLE
[fix/index-bar] Make Index Bar available in general file list

### PR DESCRIPTION
**Pull request by hosy**
## Related Issue
#413 

## Motivation and Context
Better user experience in long file lists. As a user I want to quickly scroll down to the latest item

## How Has This Been Tested?
- Index bar is only visible, if sorting is "Sort by name"
- Index bar is only visible, if more than one different letters are available
- Index bar is only visible, if more items are available as visible

## Screenshots (if appropriate):
Simulator Screen Shot - iPhone X - 2019-08-02 at 11 36 30

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jesmrec** [comment]
QA checklist:

- [X] Empty list -> do not show the bar
- [ ] All items visible at a glance -> do not show the bar
- [X] Scroll file list, but everything starting with the same letter -> do not show the bar
- [X] Scroll file list, with different letters -> show the bar
- [X] Sort by name (A-Z)-> show the list 
- [ ] Sort by name (Z-A) -> show the list (inverse?)
- [X] Sort by type, date, size, date, shared -> do not show the bar

**Comment by jesmrec** [comment]
Just a question about.

By sorting the list by name (A-Z), the bar is there with the regular order. Would make sense (if feasible) to show it in inverse order, like the list?

**Comment by hosy** [comment]
> Just a question about.
> 
> By sorting the list by name (A-Z), the bar is there with the regular order. Would make sense (if feasible) to show it in inverse order, like the list?

Yes, that is right. But would make sense to solve this, after PR #474  was merged into `milestone/1.1`, because I can ask for the sort direction, when sort direction is available.

**Comment by hosy** [comment]
@jesmrec sort direction is now implemented and the index bar is shown inverse, if sort direction is descendant.

**Comment by jesmrec** [comment]
Cool! everything ok on my side!

**Pull request merged**
