### PR TITLE
[feature/account-wizard] Add account wizard

### LINKED ISSUE #1128: [BUG] Av. offline badge is there after making unav. offline
### Steps to reproduce

1. Set any file as available offline -> badge displayed in file list and `Available offline` option in card (check https://github.com/owncloud/ios-app/issues/1065)
2. Set the file as unavailable offline 

### Actual behavior
Av. offline badge is not gone. Sometimes, the option in card/contextual menu is `Available Offline`

### Expected behavior
Av. offline badge is gone because file is not available offline. Option displayed in card/contextual menu is `Make Available Offline`

https://user-images.githubusercontent.com/14894746/173338438-794e18d6-f0f4-49a8-b57c-b990f6895ecd.MP4

**iOS version:** 15.4.1

**ownCloud app version:** `11.10.0` and `12.0 build 223`

**Device model:** iPhone XR

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
- add BookmarkComposer
- add BookmarkSetupViewController UI for BookmarkComposer
- consolidation and extension of branding options
- add support for reordering accounts in the sidebar via drag and drop 
- add location breadcrumb dropdown in the viewer
- fix #1128 
- address client portion of #1295 / add support for ocis private links
- implement HTTP request/response logging as JSON in line with https://github.com/owncloud/client/issues/11224
- add `authentication-oauth2.omit-authorization-parameters` to allow omitting parameters from authorization requests (#1318)

## Screenshots (if appropriate):
Intro | Legacy Webfinger | Server URL  | Basic Auth  | OIDC | Infinite PROPFIND | Completed
--|--|--|--|--|--|--
Simulator Screenshot - iPhone 14 Plus - 2023-09-11 at 12 23 04 | Simulator Screenshot - iPhone 14 Plus - 2023-09-06 at 19 30 08 | Simulator Screenshot - iPhone 14 Plus - 2023-09-06 at 19 31 03 | Simulator Screenshot - iPhone 14 Plus - 2023-09-06 at 19 26 16 | Simulator Screenshot - iPhone 14 Plus - 2023-09-06 at 19 27 35 | Simulator Screenshot - iPhone 14 Plus - 2023-09-11 at 10 27 43 | Simulator Screenshot - iPhone 14 Plus - 2023-09-06 at 19 26 23

### Branding assets
Branding assets are now picked and copied dynamically based on their existence and contents:
- `ownCloud/Resources/Theming/com.owncloud.ios-app` is used by default
- `ownCloud/Resources/Theming/branding-assets` is used **instead** if there's at least one file in it matching the `branding-*.png` pattern

Problems solved:
- branding assets for the pristine app and branded app versions are no longer getting mixed up
- branding assets can now be truly optional, without requiring changes to the Xcode project to prevent build errors

Supported assets:
File name |              | Purpose
--|------|--
`branding-splashscreen-logo.png` | **required** | Logo used in the splash screen during app launch.
`branding-splashscreen-background.png` | **required** | Background image used in the splash screen during app launch.
`branding-logo.png` | **required** | Used by `BrandView` in the setup wizard and sidebar branding pill.
`branding-background.png` | optional | Used by `BrandView` in the setup wizard and sidebar branding pill.
`branding-logo-setup.png` | optional | Variant of `branding-logo.png` to be used in account setup.
`branding-background-setup.png` | optional | Variant of `branding-background.png` to be used in account setup.
`branding-logo-sidebar.png` | optional | Variant of `branding-logo.png` to be used in the sidebar branding pill.
`branding-background-sidebar.png` | optional | Variant of `branding-background.png` to be used in the sidebar branding pill.
`branding-login-logo.png` | legacy | Replaced by `branding-logo.png`, supported as a fallback only.
`branding-login-background.png` | legacy | Replaced by `branding-background.png`, supported as a fallback only.
`branding-logo.png` | optional | Image to build the app icon from (used in `fastlane/Fastfile`)
`branding-sidebar-link-icon.png` | optional | Convention for naming the image to show<br>alongside sidebar links.For it to be used<br>at all, it must be referenced<br>in the respective `branding.sidebar-links`<br>entry/entries. There is no code referencing it.

### Default Theme and customizable light/dark themes based on system colors
The default theme is no longer the first theme in the list (typically `Light`), but `Follow System Appearance`, so the app follows light and dark mode as used by the system.

If `branding.theme-definitions` is **not** used, the app now provides themes for light mode and dark mode to branded clients, with support for light customization through branding:
Option | Description
--|--
`branding.theme-colors`| Values to use in system-color-based themes for branded clients. Mutually exclusive with theme-definitions.
`branding.theme-css-records` | CSS records to add to the CSS space of system-color-based themes for branded clients. Mutually exclusive with theme-definitions.

Both options can be used together.

### Supported `branding.theme-colors` keys/aliases
Alias | Value
--|--
`tint-color` | Color to use as tint/accent color for controls (in hex notation). Replaces `branding.theme-tint-color`.
`branding-background-color` | Color to use as background color for brand views (in hex notation).
`setup-status-bar-style` | The status bar style in the setup wizard, affecting the status bar text color. Can be either `default`, `black` or `white`.
`file-icon-color` | Color to fill file icons with (in hex notation).
`folder-icon-color` | Color to fill folder icons with (in hex notation).

Each alias can be expanded to one or more CSS addresses internally, so that the values set here can be assigned to the right elements - even after major UI changes or refactoring.

Example:
```xml
<key>branding.theme-colors</key>
<dict>
	<key>tint-color</key>
	<string>#ff0000</string>
	<key>branding-background-color</key>
	<string>#0ff0f0</string>
	<key>setup-status-bar-style</key>
	<string>black</string>
	<key>folder-icon-color</key>
	<string>#00ff00</string>
	<key>file-icon-color</key>
	<string>#0000ff</string>
</dict>
<key>branding.theme-css-records</key>
<array>
	<string>sidebar.account.fill: #aabbcc</string>
</array>
````

### Removal of unused branding options
`branding.theme-generic-colors` and `branding.theme-definitions$[X].Colors.*` were already ignored / no longer used. The remaining code referring to these options has now been removed as well.

### Removal of duplicate branding options
The following, duplicate branding options were removed:
Removed option | Was duplicate of / Use instead
--|--
🚫 `account-settings.default-name` | ✅ `branding.profile-bookmark-name`
🚫 `account-settings.default-url` | ✅ `branding.profile-url`
🚫 `account-settings.url-editable` | ✅ `branding.profile-allow-url-configuration`

## Text overrides
The title and message text of each step can be overridden by targeting special translation keys through the `locale.overrides` option, following the format `setup-[stepName]-title` and `setup-[stepName]-message`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>locale.overrides</key>
	<dict>
		<key>setup-serverURL-title</key>
		<dict>
			<key>en</key>
			<string>Enter Instance URL</string>
		</dict>
		<key>setup-serverURL-message</key>
		<dict>
			<key>en</key>
			<string>You can find the instance URL in your sign-up email.</string>
		</dict>
	</dict>
</dict>
</plist>
```

The possible step names are `intro`, `enterUsername`, `serverURL`, `authenticate`, `chooseServer`, `infinitePropfind` and `completed`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Feedback

- [X] (1) `branding.can-add-account=false` ignored https://github.com/owncloud/ios-app/pull/1274#issuecomment-1723694915 [FIXED]
- [X] (2) `branding.can-edit-account=false` should skip Completed screen https://github.com/owncloud/ios-app/pull/1274#issuecomment-1725486374 [FIXED]
- [x] (3) Wrong step in basic auth flow https://github.com/owncloud/ios-app/pull/1274#issuecomment-1727321255 [FIXED]
- [X] (4) Username not propagated to browser https://github.com/owncloud/ios-app/pull/1274#issuecomment-1738619755 [FIXED]
- [X] (5) Glitch in sidebar with the ejecting button https://github.com/owncloud/ios-app/pull/1274#issuecomment-1738623115 [FIXED]
- [X] (6) Bad UI when adding new account https://github.com/owncloud/ios-app/pull/1274#issuecomment-1772259038
- [x] (7) Crash in Share options in sidebar menu https://github.com/owncloud/ios-app/pull/1274#issuecomment-1772259038
- [ ] (8) Missing translations https://github.com/owncloud/ios-app/pull/1274#issuecomment-1772259038
- [x] (9) Some assets require branding.organization-name https://github.com/owncloud/ios-app/pull/1274#issuecomment-1787616518

### CODE REVIEW

**Comment by jesmrec** [comment]
### (3)

basic auth flow with incorrect step:

1. Welcome view ✅ 
2. Enter basic auth URL -> security warning (approve) ✅ 
3. Open login page ❌  -> back and proceed again
4. Credentials ✅ 

Step 3 incorrect. Video:

https://github.com/owncloud/ios-app/assets/14894746/16b8ceb3-d119-4fe2-aaf6-906d5feb4894

iPhoneXR, iOS17.0
`90642530`

**Comment by jesmrec** [comment]
About the legacy webfinger: asks first the username ✅ but then the url before the credentials. Shouldn't be the URL pre-set up somehow? not a parameter for users to know. I guess i'm missing something. My expectation for legacy webfinger:

1. Username in UI
2. Username resolved under the hood, returning the hosting tenant
3. UI triggers authentication against the resolved tenant

let me know if expectation is different.

**Comment by michaelstingl** [comment]
> About the legacy webfinger: asks first the username ✅ but then the url before the credentials. Shouldn't be the URL pre-set up somehow?

Usually it's used with this setup:

```
	<key>branding.profile-url</key>
	<string>https://lookup.sciebo.de/</string>
	<key>branding.profile-allow-url-configuration</key>
	<false/>
	<key>server-locator.use</key>
	<string>web-finger</string>
```

When the user can enter order modify the server URL (not used out there in the wild), I'd prefer 1️⃣ enter URL 2️⃣ enter username, but I can accept it the other way for now. (easier to implement according to @felix-schwarz )

**Comment by michaelstingl** [comment]
> ### (2) `branding.can-edit-account=false` should skip Completed screen

Fixed in https://github.com/owncloud/ios-app/commit/adcdffcdc24c23c2a5345c978c6afde14218f861

**Comment by michaelstingl** [comment]
> (1) `branding.can-add-account=false` ignored

Fixed in https://github.com/owncloud/ios-app/commit/a686d4c217ecf7ec3924a13b55e129bd23fe9311

**Comment by hosy** [comment]
@felix-schwarz css colours should not be reverted, but your current implementation does not support system dark mode. The solution was, to support system dark mode in the account wizard.

**Comment by felix-schwarz** [comment]
@hosy Sorry, I thought these changes were left over from experimentation with dynamic system colors, as they lead to color/theme inconsistencies like in the screenshots below. Supporting both dark and light mode in the setup view also makes theming more difficult (=> f.ex. form background and theme background no longer have a high contrast in this example).

Certificate background doesn't match | Certificate background doesn't match; Textfield background remains white ; form background color and theme background have low contrast | Mixup of colors (app theme = light, setup screen = system(here: dark))
--|--|--
Simulator Screenshot - iPhone SE (3rd generation) - 2023-09-27 at 12 52 59 | Simulator Screenshot - iPhone SE (3rd generation) - 2023-09-27 at 12 54 43 | Bildschirmfoto 2023-09-27 um 12 59 44

**Comment by hosy** [comment]
@felix-schwarz yes, I know about this mixup, but should be done.
Suggested solution: change Certificate background to system colour.

**Comment by felix-schwarz** [comment]
@hosy I restored your color changes to `ThemeCollection` and made the certificate summary view background color default to `UIColor.clear`.

I don't think using dynamic colors in themes is a good idea, though, since it'll conflict with elements using non-dynamic colors. IMO the better solution would be to use distinct colors for light and dark mode.

**Comment by jesmrec** [comment]
### (4)

Add a legacy webfinger server (fill up all fields in the app), together with the [proper branding setup ](https://github.com/owncloud/ios-app/pull/1274#issuecomment-1727361277)

When the browser is open to authenticate, the username field is not filled up, that means, users must type username twice (app and browser). IIRC, there is a field `user` to be added in the request body (redirect_url) that points to the username to be filled up in the browser.

Could you take a look @felix-schwarz ?

**Comment by jesmrec** [comment]
### (5)

Small visual glitch in the sidebar menu if the account name is too long. The reject button is slightly out of the frame:

Screenshot 2023-09-28 at 09 13 23

May not be related with this PR, feel free to fix, not a blocker

**Comment by felix-schwarz** [comment]
@jesmrec (4) and (5) should be fixed as of [af573c1](https://github.com/owncloud/ios-app/pull/1274/commits/af573c183c9f7f246f9e7f0ba4ff708fcf624778)

**Comment by jesmrec** [comment]
(4) and (5) fixed!

**Comment by michaelstingl** [comment]
@felix-schwarz could we perform processes like "Contacting server…" also in the box?

**Comment by jesmrec** [comment]
New round after the latest commits, new findings:

iPhoneXR 17.1
`4aaeed206`

### (6)

1. Add one account
2. In the sidebar click on `+`

Current: strange view (check video below)
Expected: add new account 


https://github.com/owncloud/ios-app/assets/14894746/ec3ac25f-dec3-46f8-b39b-6937d2f30fd1

### (7)

1. Add an account
2. Open sidebar menu  -> Shares -> Shared with me

Current: app crashes
Expected: no crash

Logfile: 
[ownCloud_20_Oct_2023_at_09_10_46.log.txt](https://github.com/owncloud/ios-app/files/13051023/ownCloud_20_Oct_2023_at_09_10_46.log.txt)

### (8)

Translations missing (checked with `Deutsch` language in device). 

All the new authentication wizard is untranslated, but I guess it's pending to be merged from the transifex branch.

Screenshot 2023-10-20 at 09 34 02
Screenshot 2023-10-20 at 09 40 24

**Comment by felix-schwarz** [comment]
@jesmrec (6) is fixed, (8) is already localized for English, but the German translation still missing.

Regarding (7), please re-check with the latest commit as I couldn't reproduce it.

**Comment by jesmrec** [comment]
(6) is fixed

(7) Still reproducible with `` and sdk `` , using iPhoneXR with iOS17.1. Built with Xcode15.0.1 (15A507). Got some extra logs with the latest commits:

[ownCloud_31_Oct_2023_at_09_40_02.log.txt](https://github.com/owncloud/ios-app/files/13213996/ownCloud_31_Oct_2023_at_09_40_02.log.txt)

**Comment by jesmrec** [comment]
### (8)

About branding assets:

in both `ownCloud/Resources/Theming/com.owncloud.ios-app` and `ownCloud/Resources/Theming/branding-assets` i placed the required files inside, using same name in both folders:

`branding-logo.png`
`branding-splashscreen-logo.png`
`branding-splashscreen-background.png`

Current: 

branding-logo  ✅  (got the image from `branding-assets` )
branding-splashscreen-logo :x:  (got the image from `com.owncloud.ios-app` )
branding-splashscreen-background :x: (got the image from `com.owncloud.ios-app` )

Expected:

all images got from `branding-assets` since all of them are correctly named matching the pattern `branding-*.png`

iPhoneXR 17.1
`70e9c28`

**Comment by jesmrec** [comment]
### (9)

About the asset `branding-logo-sidebar.png` and `branding-background-sidebar.png`: they are only set together with `branding.organization-name` whereas the other assets like `branding-logo-setup.png` or `branding-background-setup.png` don't require that branding option to work fine.

I mean, if i set a correct `branding-logo-sidebar.png` and `branding-background-sidebar.png`, i'll not see them in the screen unles i set `branding.organization-name` in `Branding.plist`. Nevertheless, if i set a correct `branding-logo-setup.png` or `branding-background-setup.png`, i'll see them in the screen regardless the `branding.organization-name`.

Is that behaviour expected?

iPhoneXR iOS17.1
`01f4dfa`

**Comment by felix-schwarz** [comment]
@jesmrec Re (9):

The "branding switch" `branding.organization-name` controls whether branding is activated.

If it is, the `BrandView` is also shown as a "branding pill" in the sidebar. And since the `BrandView` picks up and renders different `branding-background*.png` and `branding-logo*.png` images based on where it is placed, it would then – if they exist – also show different images for the sidebar.

What determines whether the "branding pill" is shown at the top of the sidebar, however, remains the "branding switch" `branding.organization-name` in the `Branding.plist`, not the existence of specialized files for that location.

**Comment by felix-schwarz** [comment]
@jesmrec (8) should be fixed as of 166a514.

**Comment by felix-schwarz** [comment]
@jesmrec The `BrandView` follows a simple pattern:
- look for `branding-[logo|background]-[$location].png`
- if nothing is found, use `branding-[logo|background].png`

The `$location` to use is passed when initializing the `BrandView`, which is `setup` for the view put in the Account Wizard and `sidebar` for the view put in the sidebar.

This mechanism used by `BrandView` is independent from any configuration, including `branding.organization-name`.

However, whether a `BrandView` is put at the top of the sidebar or not is controlled by `branding.organization-name`.

**Review by hosy — APPROVED** [review]

**Comment by jesmrec** [comment]
This is approved on my side!

Xcode version: `15.1 (15C65)`

Approved commits:

app: `c07dea01`
sdk: `d9e7c10`

Devices:

iPhoneXR iOS 17.2
iPadPro iPadOS 16.6

Tests reports:

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/iOS/Executions/Version%2012.1/Regression.md

[vs oC 10.13.4  ](https://reports.cucumber.io/reports/ab4b2cc2-6a35-4868-a225-7e8ef1aa1bb6 )

[vs oCIS 4](https://reports.cucumber.io/reports/bb513be5-356f-48ba-bd30-45e1583c5e7a) (current oCIS stable)

[vs oCIS 5](https://reports.cucumber.io/reports/e14bef9f-bca4-4e85-b561-7e4b3e5fb6ff) (new incoming oCIS version, currently in beta)

**Pull request merged**
