### PR TITLE
Feature/delete

### PR DESCRIPTION
**Pull request by pablocarmu**
## Description

This pull request makes the app able to remove files and folders.
Also includes the first implementation of multi-selection which need further discussion.

## Related Issue

https://github.com/owncloud/ios-app/issues/79
https://github.com/owncloud/ios-app/issues/22

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

____

- [x] (1) With no connection, deleting a file makes the app stucked [FIXED]

### CODE REVIEW

**Comment by jesmrec** [comment]
### (1) 

Steps:

1. Switch connection off
2. Delete a file

Current: A spinner with `Deleting` appears in a loop
Expected: App responses with some kind of error about `No connection`

iPhone 6S Plus v11

**Comment by jesmrec** [comment]
Delete feature works properly from my side in online mode. For offline mode issues, check: 

https://github.com/owncloud/ios-sdk/issues/25#issuecomment-410953490

**Review by jesmrec — APPROVED** [review]

**Comment by felix-schwarz** [comment]
I made a couple of changes:
- progress feedback uses the Progress object returned by OCCore (which currently doesn't provide information, but will in the future)
- Change UIAlertController category so it is reusable by adding parameters for cancel and destructive labels (it was previously hardcoded to "Cancel"/"Delete")

**Review by felix-schwarz — APPROVED** [review]
I made a couple of minor changes:
- progress feedback uses the Progress object returned by OCCore (which currently doesn't provide information, but will in the future)
- Change UIAlertController category so it is reusable by adding parameters for cancel and destructive labels (it was previously hardcoded to "Cancel"/"Delete")

**Comment by jesmrec** [comment]
All approved, then merge and close. Great job!

**Pull request merged**
