### PR TITLE
Not showing empty folder message on copy / move

### PR DESCRIPTION
**Pull request by mneuwert**
## Description
Previously even if target folder had files, message "Empty folder" was shown due to the query configured to return only subfolders. Now the message is not shown during target folder selection for copy or move operation.

## Related Issue
#319

## Motivation and Context
Better UX, less confusion for the user

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jesmrec** [comment]
I have one question here. We have two different situations:

- The target folder does not contain any subfolder in which move the item to
- The target folder is empty

The placeholder image that was removed in the current PR was intended to cover the second one. Do you think it should be removed? is it posible to keep for the second situation?

**Comment by mneuwert** [comment]
@jesmrec I think the main problem is that we create a query which excludes the files and therefore we don't know if the particular folder does contain any file or not. I think it would be Ok not to show "empty folder" in this case. But we can check with @michaelstingl.

**Comment by jesmrec** [comment]
just for clarifying: the move picker looks like that in both situations (no subfolders, no content):

Screenshot 2019-05-10 at 08 41 43

Bofore, both cases were displayed like that:

Screenshot 2019-05-10 at 08 45 49

In the first case (current PR implementation), you do not know if  the folder is empty or lacks of subfolders. In the `master` implementation, if the target folder lacks of subfolders you will see it as empty.

**Comment by jesmrec** [comment]
Accorded fix is OK. I only miss some order in the list. For example, in case i have in root folder the following subfolders:

- AA
- bb
- CC
- Dd

if i try to move something there, i see in the picker:

Screenshot 2019-05-14 at 17 30 00

the sorting is neither by size, nor by name, nor by date. 

How are the items listed @mneuwert ?

**Comment by mneuwert** [comment]
@jesmrec Sorry, missed this point.. Added alphabetical sorting with last commit. Would it be fine?

**Comment by jesmrec** [comment]
Absolutely fine.

Approved

**Pull request merged**
