### PR TITLE
Fixed drag&drop selected text -> uploaded text file

### PR DESCRIPTION
**Pull request by mneuwert**
## Description
Improved drag and drop handling for text dragged from Notes, Mail, Safari etc. Prefering RTF and plain-text over other UTIs.

## Related Issue
#887 

## Motivation and Context
Dragged text produced binary blob produced from RTFD item provider which was not viewable. Also the name of the uploaded file was derived from `NSURL.lastPathComponent.`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Review by hosy — APPROVED** [review]

**Comment by jesmrec** [comment]
QA checks:

- [ ] Drag and drop text from Safari
- [ ] Drag and drop picture from Safari
- [ ] Drag and drop text from Notes
- [ ] Drag and drop text from Mail
- [ ] Drag and drop text attached file from Mail
- [ ] Drag and drop pictures from Photos
- [ ] Drag and drop videos from Photos
- [ ] Drag and drop file from Pages

iPadAir iOS13.4

**Comment by jesmrec** [comment]
The only check i did and did not work is with the `Pages` app. There, files dragged and dropped are not moved to oC. Should we fix here or move to a separate ticket @mneuwert ?

**Comment by mneuwert** [comment]
> The only check i did and did not work is with the `Pages` app. There, files dragged and dropped are not moved to oC. Should we fix here or move to a separate ticket @mneuwert ? 

I will check this. There are multiple formats available when dragging stuff. May be Pages is fancy here.

**Comment by mneuwert** [comment]
> The only check i did and did not work is with the `Pages` app. There, files dragged and dropped are not moved to oC. Should we fix here or move to a separate ticket @mneuwert ?

@jesmrec fixed

**Comment by jesmrec** [comment]
Now, it is posible to copy/paste text from Pages correctly. But, i can not drag the whole file: 

https://user-images.githubusercontent.com/14894746/113979650-cf1ece00-9845-11eb-9409-93ec4651b072.MP4

What do you think?

**Comment by jesmrec** [comment]
Problem with Pages app is fixed. Now it's posible to drag&drop files to ownCloud.

Ready to go!

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
