### PR TITLE
[feature/better-sidebar] Improved sidebar with account-wide search

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
This PR:
- removes `Quick Access` from the sidebar, redistributing its prior contents as follows:
  - `Recents`: promoted to a top-level sidebar item
  - `Favorites`: promoted to a top-level sidebar item
  - `Available Offline`: promoted to a top-level sidebar item
  - other Quick Access items: moved as suggestions to new top-level sidebar `Search` item, with a dedicated `Add to sidebar` button that allows re-adding the previous Quick Access items as saved search
  - Saved searches now appear as top-level items in the sidebar
- adds custom user sidebar items
  - can be added via `Add to sidebar`
  - support drag and drop (also cross-account)
  - managed via context menu and swipe actions
- in the share extension automatically connects to the first account if only one account is in the account (superseding  #1296)
- incorporates the latest SDK with important fixes

## Screenshots (if appropriate):
Improved sidebar | Add to Sidebar items | Share Sheet auto-connect
-|-|-
Simulator Screenshot - iPad Air (5th generation) - 2024-02-28 at 22 00 47 | Simulator Screenshot - iPad Air (5th generation) - 2024-02-29 at 11 27 56 | Simulator Screenshot - iPhone 15 - 2024-02-28 at 22 26 26

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by hosy** [comment]
Great new feature!

Some ideas how to improve it:

- Remove item from `Quick Access` section, if already added to sidebar
- add a `Delete` item context menu to a search side bar item

Not sure if the `Search` sidebar section should be expanded, if it has sub items. Maybe it could be sense to save the expanded state of all sidebar items.

What do you think @felix-schwarz ?

**Comment by hosy** [comment]
Another idea:

If a new search is active in the file list, it could make sense to add the `Save search` action to the toolbar, because it is easier to discover for the user.

**Comment by jesmrec** [comment]
QA checks:

- [X] Quick access removed
- [X] Options in sidebar: search, recents, av. offline
   - [ ] Search
      - [ ] PDF
         - [ ] Add to sidebar
         - [ ] Remove from sidebar 
      - [ ] Documents
         - [ ] Add to sidebar
         - [ ] Remove from sidebar 
      - [ ] Images
         - [ ] Add to sidebar
         - [ ] Remove from sidebar 
      - [ ] Videos
         - [ ] Add to sidebar
         - [ ] Remove from sidebar 
      - [ ] Audios 
         - [ ] Add to sidebar
         - [ ] Remove from sidebar 
   - [ ] Recents
   - [ ] Av. offline 
- [X] Favorites in sidebar only in oC10
- [X] Folders in list with option `Add to sidebar`
   - [X] Add to sidebar some folders 
   - [X] Remove to sidebar some folders 
- [ ] Files in list  without option `Add to sidebar`

**Review by hosy — APPROVED** [review]

**Comment by felix-schwarz** [comment]
@jesmrec Very good point. I have added a new "Remove from sidebar" action and made sure the app now shows the "Add to sidebar" and "Remove from sidebar" action as appropriate.

**Comment by jesmrec** [comment]
> @jesmrec Very good point. I have added a new "Remove from sidebar" action and made sure the app now shows the "Add to sidebar" and "Remove from sidebar" action as appropriate.

done and fixed

**Comment by jesmrec** [comment]
Approved... ready to go.

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
