### PR TITLE
Added 'ITSAppUsesNonExemptEncryption' key in Info.plist

### PR DESCRIPTION
**Pull request by ChrisEdS**
Added <key>ITSAppUsesNonExemptEncryption</key><false/> - this is to bypass "Missing Compliance" hint so we don't need to set this  manually after Jenkins uploaded to TestFlight.

### CODE REVIEW

**Comment by michaelstingl** [comment]
@ChrisEdS please add reviewers

**Comment by michaelstingl** [comment]
@felix-schwarz please send some background information to @hodyroff and me to get final approval.

**Comment by felix-schwarz** [comment]
@michaelstingl Just sent the two of you a mail with links on the subject.

**Comment by ChrisEdS** [comment]
Any updates here?

**Comment by hodyroff** [comment]
I reviewed this and I am not sure I understand the holdup. "BIS now requires a year-end Self Classification Report. Consistent with these regulatory changes, Apple has simplified the export compliance review process and will no longer require developers to upload an ERN." So yes, we will do this at year end = end of 2018. Apple should not ask at this time about documentation, so we will go through the questions. I recommend we do it together @ChrisEdS

**Comment by michaelstingl** [comment]
Did some more research with @felix-schwarz , and answer to Apple is `<false/>`.

export_compliance_documentation_for_encryption_-_app_store_connect_help

(Source: https://help.apple.com/app-store-connect/#/devc3f64248f , October 10th 2018)

**Review by michaelstingl — APPROVED** [review]

**Review by felix-schwarz — APPROVED** [review]
Technically approved, while leaving the legal assessment to ownCloud 🙃

**Pull request merged**
