### PR TITLE
[milestone/11.10.0] Milestone 11.10.0

### PR DESCRIPTION
**Pull request by hosy**
## Description
- Build with iOS 15 SDK
- Bugfixes

## Related Issue
https://github.com/owncloud/ios-app/issues/1124

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

## QA

Reports:

- [x] (1) Glitch when browsing back https://github.com/owncloud/ios-app/pull/1117#issuecomment-1121022432 [FIXED]
- [X] (2) Thumbnails blink when browsing https://github.com/owncloud/ios-app/pull/1117#issuecomment-1122081354 [FIXED]
- [x] (3) oCIS version https://github.com/owncloud/ios-app/pull/1117#issuecomment-1127330308 [WONT FIX]

### CODE REVIEW

**Comment by jesmrec** [comment]
### (1)

Sometimes when browsing back, there is a small glitch showing the `Empty folder` for a while and then loading the list. Check the following video out. It does not happen every time but it is frequently visible:

https://user-images.githubusercontent.com/14894746/167407583-29140109-15d6-4e05-bd80-8478615bcc38.MP4

 iPhoneXR v15.4
`94be4380`

**Comment by jesmrec** [comment]
### (2)

Another small glitch. Thumbnails blink when browsing into a folder. In the following video, this effect could be appreciated but it's more visible with a real device:

https://user-images.githubusercontent.com/14894746/167582488-0c7ea30b-6d2b-4572-a4f7-328da654d66d.MP4

iPhoneXR iOS15.4
`22321040`

**Comment by jesmrec** [comment]
### (3)

this is also server related, so we'll maybe need some collaboration from there

App does not connect the latest ocis version (2.0.0). This is how `status.php` looks like in the test instances:

```
{
    "installed": true,
    "maintenance": false,
    "needsDbUpgrade": false,
    "version": "2.0.0.0",
    "versionstring": "2.0.0-beta1",
    "edition": "Community",
    "productname": "Infinite Scale",
    "product": "Infinite Scale"
}
```

So, by typing `ocis.owncloud.com` or `ocis.owncloud.works` , an error happens:

Screenshot 2022-05-16 at 09 30 39

because the minimum oC classic server version is 10, and oCIS is 2... 2 lowen that 10, therefore error comes. Should the fields `product` and/or `productname` be taken in account to the version checks?

iPhoneXR v15.4.1
`fbf68cc6`

Also reproducible in Android.

**Comment by hosy** [comment]
@jesmrec (1), (2) should be fixed with the latest commit

**Comment by felix-schwarz** [comment]
@jesmrec @hosy (3) is a known issue also affecting the Desktop client: https://github.com/owncloud/ocis/issues/3788 @micbar told me it's about to be addressed with top priority by the ocis team for the 2nd public beta.

The public alpha 1 of the iOS client 12.0 with spaces support contains a temporary workaround, so interested users could also use that if needed.

**Comment by jesmrec** [comment]
(1) -> fixed
(2) -> behaviour improved. No blinking when browsing. Sometimes it happen after some seconds but it's really mitigated
(3) -> wont fix here

**Comment by jesmrec** [comment]
11.10 only contains some fixes and improvements that (should) not affect the main features. So, final testing was reduced to automatic tests, basic manual checks and upgrade testing:

Xcode version: `13.3.1 (13E500a)`

Automatic test report:  https://reports.cucumber.io/reports/7fd7a553-61aa-4570-9d50-8227ce4479ac

Devices:

iPhoneXR, iOS v15.4.1
iPadAir2, iPadOS v14.8

Basic checks:

- [X] Basic auth
- [X] OAuth2: create/revoke session
- [X] OIDC: create session -> known issue (https://github.com/owncloud/ocis/issues/3788)
- [X] Av. offline files/folders
- [X] Transfers (uploads/downloads)
- [X] Files App basics

- [X] Upgrade from 10.9.1

Approved commits:

app: `6b238b5`
sdk: `b1bda6a7`

Ready to go!

**Review by felix-schwarz — CHANGES_REQUESTED** [review]

**Pull request merged**
