### PR TITLE
[feature/improve-public-link-creation] Improve creation of public link

### PR DESCRIPTION
**Pull request by hosy**
## Description
- enable dragging public link
- added clear button on public link name
- copy link to clipboard, after link was created

## Related Issue
#671 

## Motivation and Context
Better interaction for public links

## How Has This Been Tested?
- on iPad drag a created public link outside of the app
- create a public link and pasteboard should contain the new link by default
- check if public link name has a clear button inside

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## QA

- [ ] (1) Notify link copied to clipboard https://github.com/owncloud/ios-app/pull/673#issuecomment-617839336

### CODE REVIEW

**Comment by jesmrec** [comment]
### (1)

suggested improvement:

After creating the public link and copy to clipboard, i'd notify to the user with a message in the bottom status bar or similar. Otherwise, it will be a hidden feature.

**Comment by hosy** [comment]
@jesmrec regarding (1) I implemented in-app notifications to give the user a feedback on clipboard actions (copy private link, copy pubic link)

**Comment by hosy** [comment]
@jesmrec I replaced the local notification with an own implementation. Now you can check it again. A internal notification will be displayed, when a public or private link was copied to the clipboard.

**Comment by hosy** [comment]
ezgif com-video-to-gif-2

**Comment by jesmrec** [comment]
Already tested and looks pretty good! also working fine for the private links.

From my side this is approved.

**Pull request merged**
