### PR TITLE
[fix/stuck-sync] Fix stuck actions after app termination / background activity

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
- fixes an issue where sync action events wouldn't be delivered when added to a core while it starts
- last selected bookmark no longer is auto-openend when the app is launched in the background by iOS
- improves durability of underlying SQLite databases

## How to test
- log into an account
- upload several images from the photo library
- force-quit the app
- wait a minute (optional / alternative check)
- launch app again and check that uploads finish and don't get stuck

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by jesmrec** [comment]
Update with commit `3db2133`

Some scenarios performed:

1. Upload 100 files in foreground -> OK

2. Upload 100 pics from Photo albums in foreground -> OK

3. Select 15 videos to upload, and switch to other app (no oC app killed). 

I was checking the webUI to track how the uploads advance. In the moment of switching to other app, there were 6 videos already uploaded, but no more videos were uploaded while the app was not in foreground. 5 minutes later, i reopened the app and all uploads resumed and finished correctly.

Result: everything uploaded, no stucked stuff. Uploads only working in foreground. 

4. Select 100 files to upload, and switch to other app. 

Same behaviour as 3. No uploads finished while app is not in foreground. After reopening the app, everything resumed. 

Then, If you check the webUI, there are 100 uploads finished. If you check the app `Status` tab, there are two pending and stucked uploads. By killing the app ad reopening, the stucked kept being stucked. 

Result: 100% uploaded in server, but 2% stucked in the app as pending ("Stop" button inside the spinner is not visible). No background uploads were performed during the non-foreground stage.

5. Select 100 pics from Photo albums, and switch to other app.

Same behaviour as 4. 

6.  Select 100 files to upload, and kill the app.

Same as 4. and 5. 

7. With the app closed (just after rebooting the device), copy 100 files from a Files App location to oC:

Everything uploaded correctly, no stucked files.

I hope it helps. If you need logs or any further information about any of this scenarios (or other ones), please let me know.

**Comment by felix-schwarz** [comment]
@jrecio Thanks for the comprehensive tests! I'd be highly interested in the log file covering (4) - along with a screenshot of the "Status" tab showing the two stuck files. I can then trace the path of these two files throughout the log and see where things go wrong.

**Comment by jesmrec** [comment]
Here it is the log. It is pretty long in debug level (because the upload of 100 files, i guess)

[ownCloud_4_Sep_2019_at_08_41_55.log.txt.zip](https://github.com/owncloud/ios-app/files/3573096/ownCloud_4_Sep_2019_at_08_41_55.log.txt.zip)

in this case, only one file got stucked (not two as described above): `1 copy 83.txt`

Screenshot 2019-09-04 at 08 50 30

Screenshot 2019-09-04 at 08 50 42

i hope it helps

**Comment by jesmrec** [comment]
These scenarios worked properly in termos of stucked uploads within commit `4771555` in the app and `747d90e` in the sdk

From my side it is approved

**Pull request closed without merging**
