### PR TITLE
Changed full width button to a rounded button

### PR DESCRIPTION
**Pull request by hosy**
## Description
- changed full width button to a rounded button
- fixed passcode view, error label and cancel button for smaller display sizes (iPhone SE)

## Related Issue
#302 

## Motivation and Context
- remove full width buttons, because it doesn't look like a button (see #232)

## How Has This Been Tested?
- open settings
- enable / disable pass-lock 
- please test on iPhone SE, iPhone XS Max, iPad Pro 12,9

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jesmrec** [comment]
Button has the same size in iPhone and iPad. In iPhone, the button takes more or less 2/3 of the screen width, but in iPad it'd bu about 1/3. Should the button has an scalable size?

iPad: 

screen shot 2019-03-07 at 08 43 51

iPhone:

screen shot 2019-03-07 at 08 44 52

**Comment by michaelstingl** [comment]
Please align button-width behaviour across the app. (compare with button on initial empty server screen) 

Alternative: Add it as text-button to the top-right. (not beautiful, but works reliable)

**Comment by hosy** [comment]
I tried it with a larger button on the iPad yesterday, but it looks not nice. Currently it has the same width as the buttons above.

**Comment by hosy** [comment]
The current implementation looks not adapted to the iPad:
img_0035

**Comment by hosy** [comment]
In my opinion it would looks better with a smaller button

**Comment by michaelstingl** [comment]
> In my opinion it would looks better with a smaller button

works for me

**Comment by hosy** [comment]
Changed max width of buttons. `Add Account` and `Cancel` looks now equal and not to large on iPad:

simulator screen shot - ipad pro 12 9-inch 3rd generation - 2019-03-07 at 19 56 18
simulator screen shot - iphone se - 2019-03-07 at 19 56 02

**Comment by jesmrec** [comment]
ok, let's go for the approach. Approved.

**Pull request merged**
