### PR TITLE
[fix/live-preview] Keep viewed files (in app) and opened files (in File Provider) up-to-date

### LINKED ISSUE #630: [BUG] Update Content in Preview, when changed
`DisplayViewController` should automatically update it's content, when the file was changed.

## Steps to reproduce
- open a txt file, photo, PDF in detail mode
- update the content in the Web-UI or via Shortcut Save-Action
- the detail view should update the content, when the file was updated by the core

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
This PR addresses #630 through the newly created `OCClaimType` SDK feature for more fine-grained, more permissive locking of a file.

This PR makes changes to how downloaded files are retained and local copies updated automatically. It should therefore be tested thoroughly.

It also adds live-updates to the Markup feature.

### App-side test
1) open the same image for viewing on two devices
2) edit the image with the markup feature on device 1; device 2 should pick up the change and update what it displays after a couple of seconds
3) edit the image with the markup feature on device 2; device 1 should pick up the change and update what it displays after a couple of seconds
4) repeat the above, but stay within the markup feature

Previously: no updates to the content
Now: content is updated

### File Provider test
1) open an image for viewing inside the Files.app on device 1
2) edit the image on device 2; device 1 should pick up the change (keep an eye on file size)
3) edit the image on device 1; device 2 should pick up the change (keep an eye on file size)
4) open the image for viewing on device 2 and check if its equal to the one on device 1 - it should be

Previously: local copy of the file was not updated
Now: local copy is updated

## Related Issue
#630 
Possibly https://github.com/owncloud/enterprise/issues/3803

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%201.3.2/Keep%20viewed%20files%20up-to-date.md

BUGS & IMPROVEMENTS

- [x] (1) Txt files not updated https://github.com/owncloud/ios-app/pull/653#issuecomment-604384546 [FIXED]
- [x] (2) Files App not updating content [WONT FIX]

### CODE REVIEW

**Review by hosy — APPROVED** [review]

**Comment by jesmrec** [comment]
### (1)

1. Open a txt file in iOS app
2. Open the same file in other client
3. Edit the file in the other client

Current: 

Content is not updated in the iOS app. To get the update, the file must be re-opened. The spinner in the file list is there forever. Screenshot and logs:

Mar-26-2020 12-05-16

[ownCloud_26_Mar_2020_at_12_04_35.log.txt](https://github.com/owncloud/ios-app/files/4386896/ownCloud_26_Mar_2020_at_12_04_35.log.txt)

Expected: File updated in-live

Iphone XR v13.3
app: `868a3a69` sdk: `a433249`

**Comment by jesmrec** [comment]
Regarding (1), i have done the same test with an image (png). 

1. Edit the image with some strokes using other client -> image is updated in iOS app correctly
2. Keeping the image open, it is edited again with the other client -> in this case, the modification is not reflected in iOS app, and the spinner is in the file list

Logs (image is `IMG_0923.PNG` )

[ownCloud_26_Mar_2020_at_12_49_17.log.txt](https://github.com/owncloud/ios-app/files/4386952/ownCloud_26_Mar_2020_at_12_49_17.log.txt)

**Comment by felix-schwarz** [comment]
Thanks for the feedback & logs @jesmrec!

I noticed that not all viewer extension could properly handle file updates. Fixed that - and should work for all file types as of https://github.com/owncloud/ios-app/pull/653/commits/8eddcd842f81ca971100c7868fdc4a332d10844c

**Comment by jesmrec** [comment]
### (2)

In Files app

1. Take two devices, attach the same account and open Files App in both
2. Open the same image
3. Mark the image in one of the devices

Current: Image is uploaded to server but the other device does not update its local copy. This is the same scenario defined in the fist message for the file provider.

Expected: File updated

Tested with a word file and different images.

app commit: `124da5d3`
sdk commit: `8a8b1b3`
iPhone XR and iPadAir, both iOS13.

**Comment by felix-schwarz** [comment]
@jrecio The Files app does not support seem to support live updates while viewing. Even with iCloud Drive, it's not supported.

You should see the file being updated (different date, different size) after viewing and closing the viewer, though:

1. Take two devices, attach the same account and open Files App in both
2. Open the same image
3. Close the image on device 1 (but stay in the file's folder)
4. Mark the image on device 2

Expected: you should now see the date and size update on device 1.

**Comment by jesmrec** [comment]
Thanks for the clarification. That works fine.

**Comment by jesmrec** [comment]
From my side this is approved

**Comment by jesmrec** [comment]
About https://github.com/owncloud/enterprise/issues/3803, with the current implementation, i could not reproduce the problem. The fact that the iOS local edited file is steadily updating makes difficult to cause a conflict. If you are OK, we can go for this approach and approve this one.

**Comment by hosy** [comment]
> About [owncloud/enterprise#3803](https://github.com/owncloud/enterprise/issues/3803), with the current implementation, i could not reproduce the problem. The fact that the iOS local edited file is steadily updating makes difficult to cause a conflict. If you are OK, we can go for this approach and approve this one.

Perfect, for me it is ok to approve.

**Comment by jesmrec** [comment]
Ok, i will update the enterprise issue as well.

We should not forger that for the moment.

Approved

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
