### PR TITLE
[fix/passcode-settings-ui-update] Passcode Settings UI Update

### PR DESCRIPTION
**Pull request by hosy**
## Description
Setting the completion handler was missing, which causes that the UI was not updated after enabling/disabling passcode lock

## Related Issue
#923 

## Motivation and Context
UI feedback to the user, after setting changed

## How Has This Been Tested?
- enable passcode
- disable passcode

As a result the settings UI should be updated immediately

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

## QA

- [X] (1) Biometrical disabled after entering passcode https://github.com/owncloud/ios-app/pull/926#issuecomment-797492878 [FIXED]
- [X] (2) Face ID is requested after disabling passcode https://github.com/owncloud/ios-app/pull/926#issuecomment-800028356 [FIXED]

### CODE REVIEW

**Review by mneuwert — APPROVED** [review]

**Comment by jesmrec** [comment]
### (1)

Check the following behaviour:

1. Install the app from scratch
2. Enter Settings
3. Enable and enter new passcode
4. Enable Touch/Face ID (passcode asked)

Current: After typing passcode, Touch/Face ID switch is disabled

https://user-images.githubusercontent.com/14894746/110946872-b94de400-833f-11eb-94fd-9725f59cece0.mov

Expected: After typing passcode, Touch/Face ID switch is disabled


iPhoneXR v14.4
iPadAir v13.4

`88b7808`

**Comment by hosy** [comment]
@jesmrec should be fixed now!

**Comment by jesmrec** [comment]
(1) -> fixed

**Comment by jesmrec** [comment]
### (2)

1. Enable passcode
2. Enable touch/face ID
3. Disable passcode
4. Enable passcode
5. Close app
6. Open app

Current: Touch/Face is requested to enter in the app

Expected: Passcode is requested to enter in the app, because touch/face id was disabled after step 3.

iPhone XR 14.4
`df5711ce`

**Comment by hosy** [comment]
@jesmrec really good deep testing! Fixed the problem by resetting biometrical security to default value.

**Comment by jesmrec** [comment]
(2) is fixed and PR approved!

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
