### PR TITLE
[milestone/11.10] Milestone 11.10

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
- BookmarkViewController: re-add infinite `PROPFIND` code previously removed due to a merge error
- update CHANGELOG.md
- bump build and version numbers
- update ios-sdk to increase timeout for start of response to infinite `PROPFIND` from 30 seconds to 6 minutes

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## QA

- [X] (1) Older server versions do not connect https://github.com/owncloud/ios-app/pull/1109#issuecomment-1076301147 [FIXED]
- [X] (2) Upgrading https://github.com/owncloud/ios-app/pull/1109#issuecomment-1076304861 [WONT FIX]
- [x] (3) Long time to retrieve metadata https://github.com/owncloud/ios-app/pull/1109#issuecomment-1077364180 [SERVER ISSUE]

### CODE REVIEW

**Comment by jesmrec** [comment]
### (1)

As commented in the infinite propfind pull request -> https://github.com/owncloud/ios-app/pull/1002#issuecomment-998965040, feature will be available only for 11.9+ servers. Are you sure that will be ok? 

If an older server (f.ex. 10.8) is tried to be added:

https://user-images.githubusercontent.com/14894746/159694711-f7a64213-335e-4271-b22c-3c2a95ea5cc9.MP4

account is not attached. Same for ocis (i tested with `ocis.owncloud.works`)

In case you expect not to allow users with older server version to use the app, any notification should be shown to clarify what's going on there.

**Comment by jesmrec** [comment]
### (2)

Following the same path as (1)

After clean installation, older that 10.9 are not attached (reported above). But:

1. Install app 11.9 version
2. Add 10.8 server bookmark
3. Upgrade to current 

Current: everything is OK

From scratch we do not allow old server accounts to be added, but they are allowed if app is upgraded (previoulsy added)

**Comment by michaelstingl** [comment]
iOS app shouldn't rely on the server version, it should only rely on the capabilities.

With 10.9+, you should see this:

```
% curl -u demo:demo 'https://demo.owncloud.com/ocs/v1.php/cloud/capabilities?format=json' | jq '.ocs.data.capabilities.dav'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2441  100  2441    0     0   9893      0 --:--:-- --:--:-- --:--:-- 10213
{
  "chunking": "1.0",
  "reports": [
    "search-files"
  ],
  "propfind": {
    "depth_infinity": true
  },
  "trashbin": "1.0"
}
```


If `"depth_infinity": true` is set, it should do the new initial discovery. If it's not set, it should do the background discovery, same as before, independent from the server version.

**Comment by jesmrec** [comment]
> iOS app features shouldn't rely on the server version, they should only rely on the capabilities.

yes, this is OK and makes sense

> If it's not set, it should do the background discovery, same as before, independent from the server version.

now, with `f879fb3b` (last commit in this PR), only 10.9+ accounts can be used in the app. That means, this is not the expected behaviour.

**Comment by hosy** [comment]
@felix-schwarz please can you have an look here: https://github.com/owncloud/ios-app/pull/1109#issuecomment-1076301147

**Comment by felix-schwarz** [comment]
@jesmrec @hosy @michaelstingl Finding (1) is fixed as of 45634f06be1dbdc2c26a3975ec0ce17692063461.

**Comment by hosy** [comment]
@jesmrec this branch will go inside the release too: https://github.com/owncloud/ios-app/pull/1112

**Comment by jesmrec** [comment]
(1) fixed

**Comment by jesmrec** [comment]
### (3)

About infinite propfind, i've done a test against cloud.owncloud.com (about 90K items) to check what's going on.

1. After entering credentials, starts `Preparing account. Retrieving metadata...`.  It took more than 4 minutes. 
2. After that, it fetches all the items in 40 seconds.

It seems a long time just for the metadata comparing with the time to get the content. Any reason? is that expected? In the test i did 3 months ago, the same amount of files took ~1min (https://github.com/owncloud/ios-app/pull/1002#issuecomment-998965040)

I've caught some logs. Some gaps took my attention. First, a ~90 secs gap:

```
2022-03-24 08:56:44.696000+0100 ownCloud[371:010248] [dbug] ┛ [HTTP, Request, …] ----------------------------------------------------------------- [… PROPFIND, RequestID:1212CE28-A91F-4DA5-BE35-B95561B6A3DC, URLSessionTaskID:4] [OCHTTPPipeline.m:1183|FULL]
2022-03-24 08:58:11.498000+0100 ownCloud[371.010218] [dbug] | [PROCMAN, State] App will resign active [OCProcessManager.m:343|FULL]
```

and immediately, another gap of ~3 minutes

```
2022-03-24 08:58:16.584000+0100 ownCloud[371:016485] [dbug] | [APP, TASK_MANAGER] All tasks executed [ScheduledTaskManager.swift:293|FULL]
2022-03-24 09:01:09.146000+0100 ownCloud[371:010613] [dbug] | Error=(null), inputStream=<__NSCFInputStream: 0x2816a20a0>, basePath=/remote.php/dav/files/jrecio [OCBookmark+Prepopulation.m:154|FULL]
```

i can provide you the full log, if needed.

CC @felix-schwarz

**Comment by felix-schwarz** [comment]
Re (3), it seems cloud.owncloud.com does not stream the response, but complete the PHP script run locally first before starting to send the response. I've seen that both in Little Snitch and Activity Monitor:

1) While "Retrieving Metadata", the app waits for the response and incoming data rate is at the base level background noise rate on my system (177 KB/s here):

Bildschirmfoto 2022-03-24 um 09 58 47

2) Roughly 3 minutes later, the incoming data rate makes a massive jump to ~ 7 MB/s (6,74 MB/s in the screenshot) and parsing commences:
Bildschirmfoto 2022-03-24 um 10 01 22

So this definitely seems to be a server-specific issue.

**Pull request merged**
