### PR TITLE
[milestone/12.0.1] Milestone 12.0.1

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
Version 12.0.1 fixes all findings left over from version 12.0:

- [x] (1) [LOW] Soft keyboard over the results https://github.com/owncloud/ios-app/pull/1095#issuecomment-1559068546 [FIXED]
- [x] (5) [MED] Download instead of streaming -> black screen https://github.com/owncloud/ios-app/pull/1095#issuecomment-1576610804 [FIXED]
- [x] (7) [LOW] Full screen mode does not work properly https://github.com/owncloud/ios-app/pull/1095#issuecomment-1578169428 [FIXED]
- [x] (9) [MED] Offline indicator not gone after re-atuhenticate https://github.com/owncloud/ios-app/pull/1095#issuecomment-1578991305 [FIXED]
- [x] (12) [LOW] Sharing option duplicated in Files App https://github.com/owncloud/ios-app/pull/1095#issuecomment-1580259507 [FIXED]
- [x] (13) [HIGH] Bottons misplaced https://github.com/owncloud/ios-app/pull/1220#issuecomment-1592515336  [FIXED]

#### Regarding (12):
The string naming that action (`Share`) is stored in the File Provider UI's `Info.plist` and therefore can't be changed dynamically at runtime. To keep it branding-friendly, I chose "Share by cloud" instead of "Share via ownCloud", "Share (ownCloud)", which would have required to customize both the `Info.plist` and the translations for branding.

## Related Issue
https://github.com/owncloud/ios-app/issues/1222

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Comment by jesmrec** [comment]
(1), (7), (9) and (12) are fixed

About (5), i still reproduce it. I notice that a new `Loading` dialog is visible in streaming mode (cool!), but in download mode:

https://github.com/owncloud/ios-app/assets/14894746/90ad1891-304b-484c-917b-2ec1b58be679

File is downloading in the background bur black screen is there. 

CC @felix-schwarz

**Comment by felix-schwarz** [comment]
@jesmrec Thanks for the video. The remaining issue in (5) should be fixed now, too.

**Comment by jesmrec** [comment]
(5) fixed

**Comment by jesmrec** [comment]
### (13)

**Feature**: Copy/Move
**Severity**: Medium

1. Select any item and `Copy` or `Move`
2. `Choose destination directory...`
3. `Files`

Current: `Copy Here` / `Move here` buttons are misplaced:

Screenshot 2023-06-15 at 09 28 51

Screenshot 2023-06-15 at 09 29 04

Expected: correctly alligned

iPhone XR v16.5
`ebd4c1ba85`

**Comment by felix-schwarz** [comment]
@jesmrec (13) is fixed now, too.

**Review by hosy — APPROVED** [review]

**Review by jesmrec — APPROVED** [review]

**Comment by jesmrec** [comment]
Everything fixed

**Pull request merged**
