### PR TITLE
Fix for media upload scheduling issue caused by iOS 13.6 changes

### PR DESCRIPTION
**Pull request by mneuwert**
## Description
Apparently in iOS 13.6 the way `NSOperationQueue` schedules `NSOperation` based threads has changed lifting the limitation on how many threads can be spawned concurrently and leading to starvation. Documentation is very vague on this topic and is claiming that max operation count is limited based on current system conditions which in fact seems to be the case in prior iOS versions. E.g. tested on iPad Pro (previous gen) running iOS 13.5.1 and there the number of media upload operations seems indeed to be limited by number of available CPU cores (8). So the change is essentially bringing back pre-iOS13.6 behaviour -> limit number of media upload operations to number of active cores

Also changes from PR  #762 are integrated for easier problem diagnostic.

## Motivation and Context
Making media upload great again on iOS 13.6.

## How Has This Been Tested?
Tested with uploading > 100 media assets on iPhone 11 Pro (6 CPU cores) running iOS13.6 with and without a change.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by michaelstingl** [comment]
@mneuwert feels like a rocksolid one… 👍 🤘

**Comment by mneuwert** [comment]
@michaelstingl yeah, mine testing was also very positive. Shall I just apply same fix to `milestone/1.4`? It's just one line..

**Comment by michaelstingl** [comment]
> @michaelstingl yeah, mine testing was also very positive. Shall I just apply same fix to `milestone/1.4`? It's just one line..

yeah 👍

**Comment by mneuwert** [comment]
Applied same fix in milestone/1.4

**Pull request closed without merging**
