### PR TITLE
Support changing the format of uploaded image file names

### PR DESCRIPTION
**Pull request by mneuwert**
## Description
Legacy App used to change names for uploaded photo assets and use naming scheme as follows: 
[Photo|Video]-timestamp-<xxxxx>.<ext>

Where:
- timestamp was a creation date of photo asset
- <xxxxx> an ID derived from original asset name (like IMG_xxxx.jpg) and ext - file extension.

Some users wanted to have these to at least be able to sort photos.. 

**In fact this PR corrects many other annoyances related to media asset uploads:**

- Performance of exports is improved by avoiding loading image assets into RAM whenever possible and also by picking correct export method for correct asset.
- Correct original image name (starting with IMG_) is now derived correctly by looking at all related asset resources and identifying primary ones.
- Nevertheless legacy naming scheme as requested in related issue is now default. Original names (IMG_xxxx) can be used if corresponding option in settings is activated ("Preserve original media asset names"). So names looking like UUIDs are gone.
- When uploaded asset is seen on the server with a correct creationDate (which is now passed from the photo library to the actual webDAV request). That implements the feature requested in #641 in fact.
- Edited photos are for now preferably uploaded over originals they are based on.
- Conversion of videos to MP4 is back with this PR.

## Related Issue
#676 
#641 

## Motivation and Context
In previous versions we relied very much on Photos.framework implementation and that it would provide a correct name but it turned out iOS photo library is not very consistent in how it handles its internal data structures and often you would end up with the name which looks like some sort of hex UUID.

So I've implemented naming as requested by #676 but also was able to make derivation of original name more reliable and added settings option for users who would rather like to keep original names as assets were named by the photo library.

Also when implementing I was able to refactor asset exporting code which improved the overall readability and also I could get some performance gains by using more efficient asset export mechanisms where appropriate.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

_____

### QA

Test Plan:  https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2011.4.0/Asset%20renaming%20in%20Albums.md

- [x] (1) extension m4 is duplicated https://github.com/owncloud/ios-app/pull/687#issuecomment-640534688
- [x] (2) IMG_ prefix for videos https://github.com/owncloud/ios-app/pull/687#issuecomment-640536619
- [x] (3) Uploads from external app does not match with the setting about the file name https://github.com/owncloud/ios-app/pull/687#issuecomment-641102175

### CODE REVIEW

**Comment by hamiller** [comment]
Hi there. Can we get an update here please?
Will this change make it into 1.4? 
Can I support? Maybe @jesmrec can have a look?

**Comment by jesmrec** [comment]
This is on my queue to test. It will be included in the next release (11.4).

**Comment by jesmrec** [comment]
### (1)

1. Enable "convert videos to MP4"
2. Take a video and upload, no matter if manually or with auto uploads

Current: Extension is .mp4.mp4 (duplicated)
Expected: .mp4

iPhone XR v13.4

**Comment by jesmrec** [comment]
### (2)

This is not a matter of the current PR. With the original media file names, both videos and images were exported with `IMG_` prefix. Was that a problem of the library? just to be sure this is something we can not fix

**Comment by jesmrec** [comment]
### (3)

Check this scenario out:

1. In app, disable `Preserve original media file names`
2. Go to Photos App
3. Select any Photo
4. Select Open In -> Save to Files -> ownCloud (any location inside the account)

Current: Photo uploaded with format `IMG_xxxx`
Expected: Should it be in format `Photo_<timestamp>_<sequence>`? because, the setting is disabled. Or, this is not in the scope f the current PR

iPadAir2 v13.4

**Comment by mneuwert** [comment]
### Re (3)
This is handled by entirely different code path which is supposed to import any type of file and is not performing any special handing for media files. So, is not in scope.

**Comment by mneuwert** [comment]
### Re (1)
This is fixed with the latest commit

**Comment by jesmrec** [comment]
(1) fixed

(2) and (3) clarified, nothing to fix there.

Approved.

**Pull request merged**
