### PR TITLE
[release/1.3.2] Release 1.3.2

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
- bugfix release
- avoid using ":", "/" and "\" in localized time stamp of auto-created file names for document scanning, using "-" instead
- licensing text layout change (background: https://twitter.com/agiletortoise/status/1204801162563731457)
- integrate #652, #653, #656 and #663

## Related Issue
#665 

#### Licensing text layout change
Bildschirmfoto 2020-03-28 um 16 16 19
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by jesmrec** [comment]
QA checks over the new release:

- [ ] What's new
- [ ] #652 
- [ ] #653 
- [ ] #656 
- [ ] #663
- [ ] #665
- [ ] OIDC - OCIS checks
- [ ] Smoke test (to be linked)
- [ ] Upgrade test from 1.3.1

**Comment by jesmrec** [comment]
### (1)

Regarding #653 

Check these steps out:

1. Open the oC account in Files App, where some images are stored.
2. Download an image from Files App
3. With a different client, modify the image.

Current: date and size of the image is correctly updated in the list of files. Thumbnail is not updated, showing the image as before being updated. In the app, thumbnails are correctly updated when the image is externally changed.

Expected: Same as in the app

iPhone XR v13
app commit: `c23ad4d`

**Comment by jesmrec** [comment]
### (2)

The operations's names in the card have changed the color from blue to white/black (theme dependant):

|1.3.1| 1.3.2 |
|:-:|:-:|
|Screenshot 2020-04-07 at 15 05 59|Screenshot 2020-04-07 at 14 59 28|

**Comment by felix-schwarz** [comment]
### Re (1):

If a file exists locally, that thumbnail is generated locally from the file, by the Files app. The File Provider no longer is asked to provide thumbnails in that case.

I quickly experimented a bit with `NSFileCoordinator` to signal changes to files, trying to trigger updates to the thumbnail. And indeed, it did trigger an update of the file's icon. However, for unclear reasons, the Files app always created the thumbnail from the file to be replaced, so the thumbnail (but not the file contents) always lagged one version behind.

I filed #667 to explore how we can make more and better use of `NSFileCoordinator` to address this issue, but think that - as annoying as the issue can be - this should not be considered a show stopper for 1.3.2. @jrecio

**Comment by felix-schwarz** [comment]
Re (2): at first look, this could be related to pointer effects. Can you take a closer look @hosy? Or should I?

**Comment by jesmrec** [comment]
@felix-schwarz (1) will not block the release. The problem will be tracked in the issue you opened. Thanks a lot.

**Comment by felix-schwarz** [comment]
(2) should be fixed as of https://github.com/owncloud/ios-app/pull/664/commits/b3c336e01b6dd92c8a753416c4df2cb2f06bb5ac now @jesmrec

**Comment by jesmrec** [comment]
(2) fixed

**Comment by jesmrec** [comment]
Upgrade test also passed.

From my side, this is ready to go. Approved.

**Pull request merged**
