### PR TITLE
[feature/reorder buttons] Reorder Navigation Bar Actions

### PR DESCRIPTION
**Pull request by hosy**
## Note:
This PR contains the changes of the PR #456, because there was some changes regarding the navigation bar inside. 
Please QA and merge this PR after PR #456 was merged into `milestone/1.1` branch.

## Related Issue
#477

## Motivation and Context
Better UX, Cleaner UI

## How Has This Been Tested?
Navigation Bar contains the following buttons:
- `Add button`, with all create actions inside
- `More button` with the same actions, like in the more action menu, but for the top item. If it is the root item, the actions `Delete`, `Move`, `Copy`, `Duplicate`, `Rename` are not available.

The `Select button` moved to the sort bar on the right side. This button will have an icon instead of a title.

## Screenshots (if appropriate):
Reorder-Bar

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by mneuwert — APPROVED** [review]

**Comment by jesmrec** [comment]
New design is nice, but multiselection behaviour has missed some features:

- We've lost the option to "Select/Deselect All" in multiselection
- Also in multiselection, operations in bottom bar are missed. You can select, but you can not do anything with the selection.

**Comment by hosy** [comment]
@jesmrec fixed:
- missing "Select/Deselect All"
- missing multiselection UI

**Comment by jesmrec** [comment]
Fixed! please fix conflicts in order to merge.

**Review by jesmrec — APPROVED** [review]

**Comment by hosy** [comment]
@jesmrec thank you. I wait with resolving merge conflicts until PR ItemPolicy was approved.

**Pull request merged**
