### PR TITLE
iOS13 gesture based multiple selection

### PR DESCRIPTION
**Pull request by mneuwert**
## Description
Added delegate methods added to `UICollectionView` and `UITableView` allowing to enter-multiple selection mode with (two) finger pan.

Gestures:
- Two finger pan to start multiple selection of items in the file list
- In photo upload selection view, you can use one finger and pan over multiple items to select them.
- Gestures are iOS13 only and will work as long as "Prevent dragging of files and folders" option in settings is inactive

## Related Issue
#725 

## Motivation and Context
Saves few taps and allows select multiple items faster

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tdubbins** [comment]
I tested the multiple selection of items in the file list with an iPhone 6s Plus and Software Version 13.5.1 and discovered the following problem:
When selecting items using two fingers, the screen freezes for about a minute and I cannot scroll up and down. When I try to select more items, there is a delay of multiple seconds.

**Comment by mneuwert** [comment]
@tdubbins I just tested it.. and checked, the performance issue you have seen is not related to gestures in iOS13. There is code which runs a tight loop over all selected items upon each single item selection / deselection and if number of already selected items is big enough, this loop takes quite some time to execute. I will file a separate issue. Thanks for pointing at this.

**Comment by jesmrec** [comment]
Feature is working fine, and no objection from my side to move forward. Only, one consideration: the setting `Prevent dragging files and folders` is perhaps cryptic for the current feature. Drag&drop has different meaning than other gestures like the tap with two fingers. Is there any general word to describe such actions? `Prevent gestures` , `Prevent finger actions` or similar?

What do you think?

**Comment by jesmrec** [comment]
As discussed, we could go for a better option as improvement. For the moment, we can go with the current one.

So, approved.

**Comment by hosy** [comment]
@jesmrec @michaelstingl what do you think about the new option title with a short subtitle to give the user more context:

Simulator Screen Shot - iPhone 11 Pro - 2020-06-22 at 14 51 44

**Comment by michaelstingl** [comment]
Yeah, let’s try this! :+1:

**Comment by jesmrec** [comment]
WFM @hosy . Let me remove the "approved" label to take another look.

**Comment by hosy** [comment]
@jesmrec just pushed a new commit with the option title changes

**Comment by mneuwert** [comment]
@hosy I just thought may be subtitle like "Prevent doing this and that with fingers" may be sounds a little bit strange. May be change "with fingers" to "using system defined gestures" as an idea? WDYT?

**Comment by jesmrec** [comment]
latest wording works for me. Let's give a try and looking forward for users' feedback

approved again.

**Pull request merged**
