### PR TITLE
[milestone/11.8.2] Milestone 11.8.2

### LINKED ISSUE #1090: [RELEASE] 11.8.2
Release a new version

Xcode version to work with:
12.5.1

### Git & Code

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [ ] [TRFX] Update translations from transifex branch.
- [ ] [TRFX] Check for missing translations.
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [DEV] Changelog: Created a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD
- [x] [DEV] Changelog: Moved all changelog files from the unreleased folder to the new version folder
- [ ] [DEV] Inform Documentation-Team for the upcoming major/minor release with new version tag (notify #documentation-internal)
- [ ] [QA] Design Test plan
- [ ] [QA] Regression Test plan
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)
- [ ] [DEV] ownBrander: Update the ownBrander git tag in repository `customer_portal` to new release tag
- [ ] [DEV] Update used Xcode version for the release in [.xcode-version](https://github.com/owncloud/ios-app/blob/master/.xcode-version)
- [ ] [DEV] Inform #documentation about the new release to set new documentation branch tag

If it is required to update the iOS-SDK version:

- [ ] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [ ] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [ ] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [ ] [DIS] Upload the binary to the App Store
- [ ] [DIS] App Store Connect: Trigger release (manually)
- [ ] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [ ] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [ ] [DIS] App Store Connect: Update changelogs
- [ ] [DIS] App Store Connect: Submit for review

### PR DESCRIPTION
**Pull request by hosy**
## Related Issue
https://github.com/owncloud/ios-app/issues/1090

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Comment by jesmrec** [comment]
## QA

**Basic tests:**

- [X] Basic auth
- [X] OAuth2 (create + renewal) 
- [X] OIDC
- [X] Transfers (upload + download)
- [X] Basic checks Files App

**Automatic test report:**

Scenarios: https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber
Result: https://reports.cucumber.io/reports/699dbfca-b5cd-4461-a63a-f240125c6a7d

**Changelog:**

- [X] Audio Playback https://github.com/owncloud/ios-app/pull/1088
- [X] Save PDF edits https://github.com/owncloud/ios-app/pull/1083
- [X] Branding color folder https://github.com/owncloud/ios-app/pull/1086

**Upgrade testing:**

- [ ] From 11.8.1 (release notes included)

**Comment by jesmrec** [comment]
### (1)

1. Install old version (11.8.1)
2. Upgrade to 11.8.2

Current: Release notes empty
Expected: Release notes with the new stuff

`d6b32c83`
iPhoneXR v15.1
iPadAir v14.7

**Comment by hosy** [comment]
@jesmrec release notes are added now and you can test it again.

**Comment by jesmrec** [comment]
(1) is fixed

**Comment by jesmrec** [comment]
Version approved!

Version: `11.8.2`

Xcode version: `12.5.1 (12E507)`

Approved commits:

app: `324351cb`
sdk:  `ef2a2d26`

Devices:

iPhoneXR, iOS v15.1
iPadAir2, iPadOS v14.7

Automatic tests report: https://reports.cucumber.io/reports/699dbfca-b5cd-4461-a63a-f240125c6a7d

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
