### PR TITLE
[iOS 14] New photo picker / permissions model

### PR DESCRIPTION
**Pull request by mneuwert**
## Description
- Using new PHPhotoPicker introduced in iOS14 instead of our custom picker.
- Dealing with the photo permission model introduced in iOS14 where user can grant access just to specific photo assets or albums.

## Related Issue
#851 

## Motivation and Context
- New photo picker in iOS14 has got an album tab and allows searching based on people faces, objects, locations etc.
- Since the user can limit the access, we could provide a convenient UI option allowing to raise access level without the need opening the Settings app.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## QA

Test plan:

Bugs & improvements:

- [X] (1) Bad UX in `Selected` option https://github.com/owncloud/ios-app/pull/853#issuecomment-769832478 [FIXED]

### CODE REVIEW

**Comment by mneuwert** [comment]
@michaelstingl Improved photo selection process on iOS14 using new picker:
- If limited access feature allowing to disable access to certain photos is not active, everything just works.
- If user limits access to certain photos / videos, they can be selected.. And then similar picker used by the system to change permissions is presented allowing the user to revise his choice regarding limited access and to grant access.. (however it is a pity you can't actually highlight stuff which is selected for upload but is missing access permission).
- When user confirms his new limited access selection, then assets are re-fetched and if they are available, then they are uploaded. If none of the assets are accessible, warning alert is shown.

**Review by hosy — APPROVED** [review]
Great work!

**Comment by mneuwert** [comment]
@hosy Thanks! Appreciate!

**Comment by jesmrec** [comment]
I have to finish QA here it. First rounds seems pretty good.

Just one comment. Check these steps out:

1. In Device > Settings > ownCloud > Photos, select `Selected Photos`
2. Select some photos there
3. in ownCloud app, select `Upload from Photo Library`
4. Select photos that were not selected in step 2.

at this point, i expected an alert error, letting user know that it is not allowed (lack of permissions). Something similar to the error that happens when `None` is selected in step 1. 

Instead, the selecting view (the same view that appears in step 1) is displayed to allow users to select new items to allow them for the app. This could be a little confusing, but my question is: is that way to do iOS-native? or is something implemented for the feature?

**Comment by mneuwert** [comment]
> I have to finish QA here it. First rounds seems pretty good.
> 
> Just one comment. Check these steps out:
> 
> 1. In Device > Settings > ownCloud > Photos, select `Selected Photos`
> 2. Select some photos there
> 3. in ownCloud app, select `Upload from Photo Library`
> 4. Select photos that were not selected in step 2.
> 
> at this point, i expected an alert error, letting user know that it is not allowed (lack of permissions). Something similar to the error that happens when `None` is selected in step 1.
> 
> Instead, the selecting view (the same view that appears in step 1) is displayed to allow users to select new items to allow them for the app. This could be a little confusing, but my question is: is that way to do iOS-native? or is something implemented for the feature?

- That's in fact confusing since new photo picker shows all pictures irrespective of photo library permissions. 
- So, if you try to fetch photos which are not available (but you have selected them), second almost identical picker is shown allowing to add more permissions. It comes from the system and there is no way to customise it.
- So, if you don't implement special handling, this second picker is appearing only once and if user doesn't change permissions, he is never asked again by the system. I did try to improve this though.. There is a way to suppress it via setting special key in Info.plist and to trigger it manually. But again, you can just tell the system to show it and can't pass any parameters or so... The only improvement I managed to achieve is: it is always consistently shown whenever current permissions don't match the selection of assets to upload.

So there are some tradeoffs when using new photo picker...

**Comment by michaelstingl** [comment]
Before Apple’s dialogue pops up, could we show an own thing, that tells users what to do?

**Comment by mneuwert** [comment]
> Before Apple’s dialogue pops up, could we show an own thing, that tells users what to do?

yes, we could

**Comment by mneuwert** [comment]
> Before Apple’s dialogue pops up, could we show an own thing, that tells users what to do?

Added an alert conveying that access to media is limited, then when user taps " Change" Apple's dialogue is shown, where photos to which access is granted are displayed with a checkmark.

**Comment by jesmrec** [comment]
> Added an alert conveying that access to media is limited, then when user taps " Change" Apple's dialogue is shown, where photos to which access is granted are displayed with a checkmark.

that's much better

**Comment by jesmrec** [comment]
Approved on my side

**Pull request merged**
