### PR TITLE
[fix/share-sheet-biometrical-unlock] Biometrical Unlock in Share Sheet

### PR DESCRIPTION
**Pull request by hosy**
## Description
Workaround for fixing the biometrical unlock in the share sheet, when opening from Boxer app. View disappeared after the biometrical unlock succeeded. Probably because 'completeRequest' was sent from the biometrical unlock extension, which caused a dismiss in the share sheet extension.

## Related Issue
https://github.com/owncloud/enterprise/issues/5256

## Details
**For a description of the current implementation, please see https://github.com/owncloud/ios-app/pull/1129#issuecomment-1183692817.**

For the previous implementation details, please expand the element below:
<details>

## How Has This Been Tested?

Use a branded client for testing and add the following parameters to the `Branding.plist` file:

```
	<key>passcode.enforced</key>
	<string>true</string>
	<key>passcode.lockDelay</key>
	<integer>60</integer>
	<key>passcode.requiredPasscodeDigits</key>
	<string>6</string>
	<key>passcode.use-biometrical-unlock</key>
	<true/>
	<key>passcode.use-biometrical-unlock-share-sheet</key>
	<true/>

```

Important is to add this new key/value to the MDM configuration:

```
	<key>passcode.use-biometrical-unlock-share-sheet</key>
	<true/>
```

- Install Boxer app
- Open a email with attachment
- Save the attachment to the ownCloud app via share sheet

## Expected results
If the new key was added to the MDM configuration, the biometrical unlock button is visible, but opens the app for unlocking. After unlocking, the user have to go manually back to the third-party app, where the share sheet was opened.
If the lock delay > 0 the share sheet extension should be unlocked.

## Screenshots (if appropriate):
</details> 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Comment by jesmrec** [comment]
@hosy I can still reproduce the problem with `4686195d` (branch `fix/share-sheet-biometrical-unlock`):

Steps i did (after installing the app with the branding setup above and attaching one account):

1. In Boxer app, open an email with attachment
2. Select three-dot-button next to attached file
3. Select "Open In" and `ownCloud`

https://user-images.githubusercontent.com/14894746/177158480-a8cc2794-4b6c-4fa7-8368-125cd0e37120.MP4

I caught some logs, in case it helps:

[ownCloud_4_Jul_2022_at_14_52_38.log.txt](https://github.com/owncloud/ios-app/files/9039565/ownCloud_4_Jul_2022_at_14_52_38.log.txt)

Device: iPhoneXR 15.4.1

**Comment by jesmrec** [comment]
Some testing with `2e99dfe6`, last commit:

- After sharing from Boxer, passcode is asked to select folder. This is the last expected behaviour ✅ 

- If FaceID is selected instead of entering the passcode, app is opened in browsing-mode, not in share-with-mode (is this expected?):

https://user-images.githubusercontent.com/14894746/178431662-16bd411d-4ea5-4f18-9d00-d526848ab9a1.MP4

- This workaround affects every 3rd party app, not only Boxer. Will the fix will only available for one customer? otherwise, the global behaviour is changing regarding external sharing.

**Comment by hosy** [comment]
@jesmrec @NannaBarz please give it a new try with the updated code and read the description above.

**Comment by felix-schwarz** [comment]
### Changes

I've changed the original implementation, replacing the boolean `passcode.use-biometrical-unlock-share-sheet` with a dictionary-based `passcode.share-sheet-biometrical-unlock-by-app` that allow control over the availability of biometric authentication on a per-app basis.

### Default configuration
```xml
	<key>passcode.share-sheet-biometrical-unlock-by-app</key>
	<dict>
		<key>default</key>
		<dict>
			<key>allow</key>
			<true/>
		</dict>
		<key>com.air-watch.boxer</key>
		<dict>
			<key>allow</key>
			<false/>
		</dict>
	</dict>
```

The default configuration already disables biometric auth when invoked from the share sheet inside the Boxer app.

So, unless additional apps need to be added - or the default setting should be replaced - there is no need to add anything to the `Branding.plist` or MDM to get special handling for Boxer.

### How it works:
- when the share sheet is invoked from an app ("host app"), the app looks for `passcode.share-sheet-biometrical-unlock-by-app`, which needs to be provided either via the `Branding.plist` or MDM
- if the share sheet finds a settings dictionary for the bundle ID of the host app, it uses the settings contained therein
- if there is no settings dictionary for the bundle ID of the host app, it uses the `default` settings. If there is no `default` settings dictionary to fall back to, `passcode.share-sheet-biometrical-unlock-by-app` has no effect.
- the settings dictionary supports two keys:
	- `allow`: set to `true` if biometric authentication should be available, set to `false` if it shouldn't
	- `trampoline-url`: an URL to use to return back to the host app.
	
If `trampoline-url` is set, invoking biometric authentication uses `openURL()` to jump to the OC app, where biometric authentication is then performed. The `trampoline-url` would subsequently be used to jump back from the OC app to the share sheet's host app.

Unfortunately, in the single instance where `trampoline-url` would be useful - with Boxer - invoking `openURL()` closes the share sheet. Just like when invoking biometric authentication. The part that jumps back from the app to the share sheet's host app has therefore not been implemented at this point, and **`trampoline-url` should therefore not be used**.

**Comment by jesmrec** [comment]
QA over latest iteration

1. With biometrical (face/touch) enabled

- [X] `passcode.share-sheet-biometrical-unlock-by-app` as `true` for Boxer and `true` for other apps -> Bad expected behaviour in Boxer
- [X] `passcode.share-sheet-biometrical-unlock-by-app` as `false` for Boxer and `true` for other apps
- [ ] `passcode.share-sheet-biometrical-unlock-by-app` as `true` for Boxer and `false` for other apps -> Bad expected behaviour in Boxer, in other apps biometrical is asked :X:
- [ ] `passcode.share-sheet-biometrical-unlock-by-app` as `false` for Boxer and `false` for other apps ->  Biometrical is asked :X:

2. With biometrical (face/touch) disabled (not customer, but global)
 
- [x] `passcode.share-sheet-biometrical-unlock-by-app` as `true` for Boxer and `true` for other apps -> no biom asked
- [x] `passcode.share-sheet-biometrical-unlock-by-app` as `false` for Boxer and `true` for other apps -> no biom asked
- [x] `passcode.share-sheet-biometrical-unlock-by-app` as `true` for Boxer and `false` for other apps -> no biom asked
- [x] `passcode.share-sheet-biometrical-unlock-by-app` as `false` for Boxer and `false` for other apps -> no biom asked

iPhone XR v15.4.1
iPadAir v14.7
`0cef5f970`

**Comment by jesmrec** [comment]
New implementation works fine, but one case:

```
<key>passcode.share-sheet-biometrical-unlock-by-app</key>
  <dict>
      <key>default</key>
           <dict>
              <key>allow</key>
	      <false/>
	  </dict>
     <key>...</key>
       ...
 </dict>
```

with that setup, any app that is not included in the dictionary must not ask biometrical (as far as i understood)

Biometrical is asked in share sheet for this set up, not expected behaviour. Is that correct @felix-schwarz ?

**Comment by felix-schwarz** [comment]
@jesmrec Thanks for testing! This was indeed a bug. As of https://github.com/owncloud/ios-app/pull/1129/commits/11a2ddb84f8816bfbde7a7d814074e1048cd9d0e this should be fixed.

**Comment by jesmrec** [comment]
Fixed! from my side this is approved. Great solution.

**Review by felix-schwarz — APPROVED** [review]

**Comment by hosy** [comment]
@jesmrec this one is also approved by your side?

**Comment by jesmrec** [comment]
@hosy yes, i approved this some days ago. I will do another check in regression stage.

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
