### PR TITLE
[feature/ipad-pointerinteraction] Implementation of iPad UIPointerInteraction to give the user a vi…

### PR DESCRIPTION
**Pull request by hosy**
## Description
Give the user a visual feedback for some custom buttons on mouse cursor movement.

## Related Issue
#655 

## Motivation and Context
Better UX when using a mouse or trackpad

## How Has This Been Tested?
- Run app on iPad with iOS 13.4
- Connect a mouse or trackpad
- Move the cursor over the elements, mentioned in the issue
- Element should be highlighted

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### QA

Test plan:

https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%201.4.0/Trackpad%20%26%20Mouse%20support%20iPad.md

### CODE REVIEW

**Comment by jesmrec** [comment]
After testing this, everything is working fine. But i want to comment with you some details:

- Swipe is not posible. Is this a restriction?

- Same for scroll up/down, f. ex., in the file list

- Hover effect on Settings happens only in the rows with an expand arrow. The options with switch does not show the effect. Is it expected?

**Comment by hosy** [comment]
@jesmrec I just tested your finding on the device with a connected trackpad:

- Scrolling is working for me
- swiping is working for me 
(please use two fingers for swiping and scrolling)

- I decided to not use a hover effect for non selectable table view rows like rows with a switch, this behavior is correct

**Comment by hosy** [comment]
ezgif com-video-to-gif

**Comment by jesmrec** [comment]
Well, i'm not sure what makes the difference, but i can not perform these actions with any gesture that i tried out (i'm using an iPad Air 2 with 13.4). In any case, this should not be a blocker.

**Pull request merged**
