### PR TITLE
[fix/pdf-thumbnailview-position] PDF thumbnail view position on the iPad

### PR DESCRIPTION
**Pull request by hosy**
## Description
This PR changes the position of the PDF thumbnail view on the iPad from the bottom to the right position.

## Motivation and Context
There are some reasons why the right position makes more sense:

- more visible (PDF) content, if the thumbnail view is on the right side
- if the thumbnail view is on the bottom, sometimes scrolling gesture activate the iOS app switcher

## How Has This Been Tested?
- open a PDF on the iPad
- thumbnail view should appear in landscape and portrait mode on the right side
- open a PDF on the iPhone
- thumbnail view should appear in landscape mode on the right, in portrait mode on the bottom

## Screenshots (if appropriate):
| Old version                                                                                                                                                                                  | Updated version                                                                                                                                                                              |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-02-22 at 11 04 11 | Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-02-22 at 11 08 23 |

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Added changelog files for the fixed issues in folder changelog/unreleased

## QA

- [ ] (1) Weird behaviour in iPhone portrait https://github.com/owncloud/ios-app/pull/905#issuecomment-787780425

### CODE REVIEW

**Review by mneuwert — APPROVED** [review]

**Comment by jesmrec** [comment]
### (1)

> This PR changes the position of the PDF thumbnail view on the iPad from the bottom to the right position.

then it should only affect iPad. 

I have check in iPhone, and i detected a weird behaviour in portrait mode: the position of the thumbnail list changes from bottom to right at the time you move the device (not necessary to change orientation):


https://user-images.githubusercontent.com/14894746/109474325-b10ac480-7a74-11eb-97e4-1fb1bfeef292.mp4

**Comment by hosy** [comment]
@jesmrec finding (1) is fixed and you can have a look again. Thank you!

**Comment by jesmrec** [comment]
unfortunately, i still reproduce (1) with commit `24bdf7c`

**Comment by hosy** [comment]
@jesmrec hopefully with the latest commit it is solved.

**Comment by jesmrec** [comment]
Not it is correctly fixed.

Approved on my side.

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
