### PR TITLE
[fix/new-review-request] Improved AppStore Review Request Time

### PR DESCRIPTION
**Pull request by hosy**
## Description
- the first AppStore review request was changed from 14 days to 7 days after app installation
- the time interval between the next review request was changed from 230 days to 122 days

## Motivation and Context
Present the App Store review panel more often to the user.

## How Has This Been Tested?
- please simulate the test like mentioned here: https://github.com/owncloud/ios-app/pull/728#issuecomment-645841323
- please test it on a device in real time (install app and check if the dialog appears after 7 days.)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by felix-schwarz** [comment]
@hosy I think I found the issue in `AppStatistics`. This line:

```swift
userDefaults.set(self.updateDate, forKey:  UserDefaultsKeys.firstLaunchDate.rawValue)
```

1) overwrote `firstLaunchDate` with `updateDate`
2) `updateDate` was never saved, so it was set to `now` at next launch
3) `firstLaunchDate` kept being updated with a recent date (=> close to `now`), so that the review prompt checks would never result in the review prompt getting triggered

**Review by felix-schwarz — APPROVED** [review]

**Comment by jesmrec** [comment]
This feature will be tested post-release in a real scenario:

1. Install from scratch the 11.5 version
2. Add an account
3. Check the device one week later

Expected: Apple review dialog is displayed

**Comment by hosy** [comment]
@jesmrec Ok, but needs to be merged into `milestone/11.5`

**Comment by jesmrec** [comment]
> @jesmrec Ok, but needs to be merged into milestone/11.5

sure. i've done some checks on the branch (installation and basic operations) and it's ok to merge it and delay the tests till the release is done.

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
