### PR TITLE
[feature/openssl-1.1.1] Migration to OpenSSL 1.1.0

### PR DESCRIPTION
**Pull request by hosy**
## Description

With Apple Silicon M1 it was no longer possible to build the app for Simulator.
Because we need to provide additional architecture, we using new OpenSSL as Swift package.
In the context of this, the code was migrated to OpenSSL 1.1.1.

- migrated code to new OpenSSL 1.1.1 API
- using OpenSSL Swift Package

## Motivation and Context
Build against all architectures, using the latest OpenSSL version.

## How Has This Been Tested?
- Build and run on all platforms iOS, Mac Catalyst, Simulator, Device
- Add a new account
- Check if certificate output is the same as before migrating

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

## QA

Checklist: https://github.com/owncloud/ios-app/pull/1116#issuecomment-1091647029

Reports

- [X] (1) Build with Xcode 12.5 https://github.com/owncloud/ios-app/pull/1116#issuecomment-1091685468 [WONT FIX]
- [x] (2) Changes in certificates https://github.com/owncloud/ios-app/pull/1116#issuecomment-1091711061

### CODE REVIEW

**Review by felix-schwarz — APPROVED** [review]

**Comment by jesmrec** [comment]
QA checks:

**Add non-secure server from scratch**

- [ ] Review Connection Warning showed
- [ ] Certificate correctly displayed
- [ ] Cancel -> auth process cancelled
- [ ] Approve -> "Certificate Details" as "Accepted". Certificate added to Settings certificate place
- [ ] Revoke Approval in Settings -> Have to be approved again 

**Certificate changed after account was added**

- [ ] Certificate changes but key does not -> auto approved. Correct reason displayed in Settings -> Certificates
- [ ] Key changes -> User warned. Diff displayed. Added to Settings -> Certificates

**Comment by jesmrec** [comment]
### (1)

Just a comment, maybe not affecting.

Building the branch with Xcode 12.5 -> error  ```Undefined symbol: PocketSVG_PocketSVG_SWIFTPM_MODULE_BUNDLE()```   . I wasn't able to build the branch under that error, with all dependencies up to date.

Building the branch with Xcode 13.2 -> works.

Since the idea is upgrading to latest SDK, it would be not relevant.

**Comment by hosy** [comment]
> ### (1)
> Just a comment, maybe not affecting.
> 
> Building the branch with Xcode 12.5 -> error `Undefined symbol: PocketSVG_PocketSVG_SWIFTPM_MODULE_BUNDLE()` . I wasn't able to build the branch under that error, with all dependencies up to date.
> 
> Building the branch with Xcode 13.2 -> works.
> 
> Since the idea is upgrading to latest SDK, it would be not relevant, right?

Yes, this is not a problem, because this branch will be build and shipped with Xcode 13.3. I think the problem is a new format of the package file. Not relevant, thank you for asking!

**Comment by jesmrec** [comment]
### (2)

Not a regression -> not needed to be fixed here. Up to you.

1. Add a server (insecure) and accept certificate
2. Go to `Settings` and revoke certificate
3. Open list of files -> Certificate issue
4. Open Issue to check Certificate details

Current: some fields in the certificate do not seem to change but are marked as changes:

Screenshot 2022-04-07 at 15 02 02

iPhoneXR v15.3
`7a3bb76d`

**Comment by hosy** [comment]
(2) should not be a blocker in this PR, but it could be added to the milestone PR and maybe @felix-schwarz can have a look. Thanks!

**Comment by jesmrec** [comment]
Checked the way certificates are shown in the app. It's OK from my side.

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
