### PR TITLE
[feature/css] CSS theming

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
Implements CSS themeing for the V12 UI.

[Documentation](https://github.com/owncloud/ios-app/tree/feature/css/ownCloudAppShared/User%20Interface/Theme/CSS#readme)

## Screenshots (if appropriate):
Light theme | Dark theme 
-----|-----
Simulator Screenshot - iPad (10th generation) - 2023-03-31 at 12 24 31 | Simulator Screenshot - iPad (10th generation) - 2023-03-31 at 12 24 54
Simulator Screenshot - iPad (10th generation) - 2023-03-31 at 12 27 42 | Simulator Screenshot - iPad (10th generation) - 2023-03-31 at 12 27 39

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Review by hosy — APPROVED** [review]

**Comment by jesmrec** [comment]
Following the example [here](https://github.com/owncloud/ios-app/tree/feature/css/ownCloudAppShared/User%20Interface/Theme/CSS#adding-styling-via-branding), i created the following `Branding.plist` file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>branding.theme-definitions$[0].cssRecords</key>
	<array>
		<string>sidebar.navigationBar.logo.stroke: #ff0000</string>
	</array>
</dict>
</plist>
```

logo is not tinted. Checking other properties as `fill` or `style` do not cause changes in the app. Something missing to do in order to get css-branding via `Branding.plist` @felix-schwarz ?

**Comment by felix-schwarz** [comment]
@jesmrec For a theme definition to be accepted, it needs to provide a `lightBrandColor` and a `darkBrandColor`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>branding.theme-definitions$[0].lightBrandColor</key>
	<string>#dd7777</string>
	<key>branding.theme-definitions$[0].darkBrandColor</key>
	<string>#770000</string>
</dict>
</plist>
```

… to which the CSS can then be added:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>branding.theme-definitions$[0].lightBrandColor</key>
	<string>#dd7777</string>
	<key>branding.theme-definitions$[0].darkBrandColor</key>
	<string>#770000</string>
	<key>branding.theme-definitions$[0].cssRecords</key>
	<array>
		<string>sidebar.navigationBar.logo.stroke: #ff0000</string>
	</array>
</dict>
</plist>
```

**Comment by felix-schwarz** [comment]
PR is part of #1207 and will be merged as part of it.

**Comment by felix-schwarz** [comment]
Merged into https://github.com/owncloud/ios-app/pull/1095.

**Pull request closed without merging**
