### PR TITLE
UX improvements (Color scheme & + button)

### PR DESCRIPTION
**Pull request by pablocarmu**
## Description

Improves some areas of the UX

## Related Issue

https://github.com/owncloud/ios-app/issues/192
https://github.com/owncloud/ios-app/issues/198

## Motivation and Context

Made to fix https://github.com/owncloud/ios-app/issues/198 and https://github.com/owncloud/ios-app/issues/192

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by michaelstingl** [comment]
@pablocarmu please post screenshots that illustrate your fixes /cc @wuenschedesign

**Comment by jesmrec** [comment]
These are the screenshots. From my side it is OK

screen shot 2019-01-23 at 10 07 50

screen shot 2019-01-23 at 10 04 48

screen shot 2019-01-23 at 10 08 27

screen shot 2019-01-23 at 10 09 03

screen shot 2019-01-23 at 10 09 35

**Comment by jesmrec** [comment]
@michaelstingl are the screenshots ok for you? if they are, we can go ahead with the merge.

**Comment by mneuwert** [comment]
@jesmrec @pablocarmu @michaelstingl wouldn't it make sense to move "Upload" button to the bar with Create Folder / Sorting Option? Then I could put "Select" into the navigation bar for multi-selection.

**Comment by michaelstingl** [comment]
> @michaelstingl are the screenshots ok for you? if they are, we can go ahead with the merge.

Please check failing bitrise.io. Then we can merge.

**Comment by michaelstingl** [comment]
> @jesmrec @pablocarmu @michaelstingl wouldn't it make sense to move "Upload" button to the bar with Create Folder / Sorting Option? Then I could put "Select" into the navigation bar for multi-selection.

Yes (see https://github.com/owncloud/ios-app/issues/198#issuecomment-456940305). Shouldn't be a blocker to merge this PR for now – I assume it can be changed easily later…

**Comment by hosy** [comment]
Documenting the color scheme is a good idea.

**Comment by michaelstingl** [comment]
I played with Figma.com and built a quick example with some `text-styles` and `color-styles`:

branding-test

I'll open a new issue, maybe @wuenschedesign could propose a useful structure of `text-styles` and `color-styles`…

BTW: Here you can play with my quick and dirty example:
https://www.figma.com/file/UZQsKEvz78nbysqyMgATVzzK/Branding-Test?node-id=1%3A3

**Comment by wuenschedesign** [comment]
At first sight, it looks promising, but Contrast Checker claims poor contrast level for this certain blue on white: https://webaim.org/resources/contrastchecker/
bildschirmfoto 2019-01-28 um 19 59 01

I am checking what the Human Interface Guidelines recommend…

**Comment by wuenschedesign** [comment]
There are not much possibilities to use the same color on white and dark with sufficient contrast.

**Comment by wuenschedesign** [comment]
Apple uses different shades of blue for action colours: https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/

**Comment by michaelstingl** [comment]
> At first sight, it looks promising, but Contrast Checker claims poor contrast level for this certain blue on white: https://webaim.org/resources/contrastchecker/

My example is not about the colors I choose. It is also not about the color names I choose. It's just a rough sketch that we need something similar… On scheme should allow to build dark themes, light themes, very colorful schemes or very desaturated themes.

**Comment by michaelstingl** [comment]
> There are not much possibilities to use the same color on white and dark with sufficient contrast.

Please check my example again. There are 2 different color sets. One set of colors related to a foreground color, and another set of color related to a background color. If someone prefers to a have a dark foreground color, they should choose lighter colors for the elements on top. Same or reverse for the background color and the related colors.

But also a totally different scheme to structure and name the colors could be possible. We just need to find a common language and a common understanding to work together. (needs to be documented)

**Comment by michaelstingl** [comment]
> Apple uses different shades of blue for action colours: https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/

Our own color scheme should follow the Apple HIG's but also reflect the ownCloud brand. Other users might choose different color schemes…

**Pull request merged**
