### PR TITLE
[fix/branding-border-color] Branding: Table Border

### PR DESCRIPTION
**Pull request by hosy**
## Description
Fixes an issue with the border color in grouped table views

## Related Issue
https://github.com/owncloud/enterprise/issues/5510

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Review by felix-schwarz — APPROVED** [review]
Code changes look fine, but it looks like the `CHANGELOG.md` got mixed up.

**Comment by jesmrec** [comment]
released a comment in the enterprise issue

**Comment by isantanaowncloud** [comment]
@jesmrec pending review

**Review by jesmrec — APPROVED** [review]

**Comment by hosy** [comment]
No longer necessary, because version 12 fixes this issue

**Pull request closed without merging**
