### PR TITLE
[feature/infinite-propfind] Infinite PROPFIND support

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
This pull requests adds support for prepopulation of newly created account bookmarks via infinite PROPFINDs.

## Related Issue
#950 

#### Test set
- Folders: 3908
- Files: 19535
- Total: 23443 items

#### Results 1 (2021-07-13)
Method | Traffic in | Traffic out | CPU | Network time | Processing time | Total time (mm:ss)
--------|----------|----------|------|------------|-----------------|-------------------
Individual | 20 MB | 2 MB | 200% (app+FP) | n/a | n/a | 7:09 
Infinite | 17 MB | 17 KB | 99% (app) | 0:15 | 0:18 | 0:33

#### Results 2 (2021-08-01) – with presumably slower server
Method | Traffic in | Traffic out | CPU | Network time | Processing time | Total time (mm:ss)
--------|----------|----------|------|------------|-----------------|-------------------
Individual | 20 MB | 2 MB | 200% (app+FP) | n/a | n/a | _7:09_ (copied)
Infinite Preload+Parse | 17 MB | 17 KB | 99% (app) | 0:24 | 0:17 | 0:41
Infinite Stream+Parse | 17 MB | 17 KB | 99% (app) | 0:25 | 0:25 | 0:25

#### Results 3 (2021-08-07) - with memory debugging options turned off
Files | Folders | Total | occ files:scan time | Receive/Parse (total) time | Streamed parsing time | Stream performance
-----|---------|------|--------------------|--------------------|-------------|----
58595 | 11720 | **70315** | 02:16 | not tested | 0:40 |  1757 items / sec
78125 | 15626 | **93751** | 02:35 | not tested | 0:52 | 1802 items / sec
97655 | 19532 | **117187** | 02:54 | 1:07 / 0:50 (1:57) | 1:09 | 1698 items / sec

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by felix-schwarz** [comment]
First results testing the iOS implementation:

### Test set `prop-infinity.shniq.cloud`
- Folders: 3908
- Files: 19535
- Total: 23443 items

### Results
Method | Traffic in | Traffic out | CPU | Network time | Processing time | Total time (mm:ss)
--------|----------|----------|------|------------|-----------------|-------------------
Individual | 20 MB | 2 MB | 200% (app+FP) | n/a | n/a | 7:09 
Infinite | 17 MB | 17 KB | 99% (app) | 0:15 | 0:18 | 0:33

### Error handling
- the implementation keeps track of which folders have been fully received
- if parsing is cancelled by the user or an XML error is encountered:
    - already parsed items are kept
    - schedules individual scans for folders whose contents has not yet been fully received (so item metadata will be fully retrieved eventually)

### Summary
- Infinite PROPFIND is 13 x faster in total compared to individual PROPFINDs (in "split" implementation)
- "parallel" implementation, where incoming PROPFIND XML data is parsed immediately, could give a total speedup of up to 23 x

### User interface
The infinite PROPFIND is automatically performed after account setup, while keeping the user informed and providing an option to cancel it (through a button labeled `Skip`)

HTTP phase | parsing phase
-----------|--------
Simulator Screen Shot - iPhone 12 Pro - 2021-07-12 at 14 53 56 | Simulator Screen Shot - iPhone 12 Pro - 2021-07-12 at 14 54 11

**Comment by felix-schwarz** [comment]
Latest benchmarks and changes as of e425698 described here:
https://github.com/owncloud/ios-app/issues/950#issuecomment-894099485

**Review by hosy — APPROVED** [review]

**Comment by jesmrec** [comment]
First thoughts about this, using the ipa provided by @hosy (`6d9c1c0`, build 203)

- Only works with 10.9 server. Trying to attach a bookmark of older server, does nothing. After credentials, moved to welcome view. (because `"depth_infinity": false` or lacking of?). Is this expected???

- Using a server with "depth_infinity": true` and ~90K items inside. (~50K files, ~40K folders) takes about 1 minute to populate against a remote server (not in the same network). Check the video:

https://user-images.githubusercontent.com/14894746/146972986-c7867fba-dd25-4adb-9c08-c1e5d5a5780c.MP4

Please, take this as a first testing with a regular server.

**Comment by michaelstingl** [comment]
> * Only works with 10.9 server. Trying to attach a bookmark of older server, does nothing. After credentials, moved to welcome view. (because `"depth_infinity": false` or lacking of?). Is this expected???

Yes, works as expected 👍

**Pull request merged**
