### PR TITLE
[feature/new-sharing] New sharing UI with role support

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
This pull request implements a new sharing UI with support for share roles and a modern layout.

## Related Issue
Implements roles as described in [#4848](https://github.com/owncloud/ocis/issues/4848#issuecomment-1283678879), prepared for dynamic roles.

## Screenshots (if appropriate):
Management | Editing a share | Custom permissions
--|--|--
Simulator Screenshot - iPad Air (5th generation) - 2023-04-24 at 11 17 41 | Simulator Screenshot - iPad Air (5th generation) - 2023-04-24 at 11 17 48 | Simulator Screenshot - iPad Air (5th generation) - 2023-04-24 at 11 17 53

Editing a link | Adding expiry date | Password + Expiry date
--|--|--
Simulator Screenshot - iPad Air (5th generation) - 2023-04-24 at 11 18 06 | Simulator Screenshot - iPad Air (5th generation) - 2023-04-24 at 11 18 17 | Simulator Screenshot - iPad Air (5th generation) - 2023-04-24 at 11 18 22

Creating a share | Overview after creation | Sharing in Files.app 
--|--|--
Simulator Screenshot - iPad Air (5th generation) - 2023-04-24 at 11 18 40 | Simulator Screenshot - iPad Air (5th generation) - 2023-04-24 at 11 18 46 | Simulator Screenshot - iPad Air (5th generation) - 2023-04-24 at 11 57 41

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

## QA

Test Plan: https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%2012.0/New%20Sharing.md

Reports:

- [x] (1) Links opened recursively https://github.com/owncloud/ios-app/pull/1198#issuecomment-1522987292
- [x] (2) Bad no connection error https://github.com/owncloud/ios-app/pull/1198#issuecomment-1523168337

### CODE REVIEW

**Comment by jesmrec** [comment]
### (1)

1. Create a new link
2. Once it is created, click on it over the list of links to open it (edit mode)
3. Click on the Link header, where the URL is set

Current: new window opened every time you click on it
Expected: no clickable area. Just the `Copy` button

https://user-images.githubusercontent.com/14894746/234514631-7b415833-115a-4cbd-8862-072830375cfe.MP4

iPhoneXR iOS16
`dea1fbb6`

**Comment by jesmrec** [comment]
### (2)

1. Remove device connection
2. Create Link

Current: `Unknown error (error 2)
Expected: More accurate error message like `No connection`

iPhoneXR iOS16 
`dea1fbb6`

**Comment by felix-schwarz** [comment]
@jesmrec (1) and (2) are fixed by #1207

**Comment by jesmrec** [comment]
both (1) and (2) fixed

**Review by jesmrec — APPROVED** [review]

**Comment by felix-schwarz** [comment]
Merged into https://github.com/owncloud/ios-app/pull/1095.

**Pull request merged**
