### PR TITLE
Multi selection on the file list

### PR DESCRIPTION
**Pull request by mneuwert**
## Description
Implementing feature request to allow actions like move, delete etc. on multiply selected items

## Related Issue
#79 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

____

BUGS & IMPROVEMENTS

- [ ] (1) Multiple error messages https://github.com/owncloud/ios-app/pull/234#issuecomment-459357637

### CODE REVIEW

**Comment by mneuwert** [comment]
> Safe area for the UIToolbar is missing.
@hosy Will check this, thanks

> Would be nicer to have the Plus-Button in the same row like the Add-Folder button. Furthermore UITabBar should be hidden, if only one item is visible.

@hosy I have suggested it in another PR, where + button was added. This is still WIP anyway.

**Comment by jesmrec** [comment]
@mneuwert i will QA when you finish. Ping me and i will take care.

**Comment by mneuwert** [comment]
@jesmrec now it is ready!

**Comment by jesmrec** [comment]
### (1) Improvement

1. Select several files 
2. Move them to a location where exists other files with the same name

Current: Error file appears as many times as files repeated. If you move 90 files, you will receive 90 alerts.

This should not be a blocker and can be addressed separately

**Comment by jesmrec** [comment]
Approved on my side

**Pull request merged**
