### PR TITLE
[translation-sync] Translation sync

### PR DESCRIPTION
**Pull request by hosy**
## Description
Latest translation sync changes from Transifex

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by oils2271** [comment]
> ## Description
> Latest translation sync changes from Transifex
> 
> ## Types of changes
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to change)
> 
> ## Checklist:
> * [ ]  My code follows the code style of this project.
> * [ ]  My change requires a change to the documentation.
> * [ ]  I have updated the documentation accordingly.
> * [ ]  I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
> * [ ]  I have added tests to cover my changes.
> * [ ]  All new and existing tests passed.

@hosy [](url)

**Comment by jesmrec** [comment]
This error happens when building ipa:

Screenshot 2019-06-14 at 09 01 19

some localization files are required UTF-16:

- Russian
- German (Germany)

by changing them it should work

**Comment by hosy** [comment]
> This error happens when building ipa:
> 
> Screenshot 2019-06-14 at 09 01 19
> 
> some localizable files are required UTF-16:
> 
> * Russian
> * German (Germany)
> 
> by changing them it should work

@jesmrec solved this problem. Please can you review it again?

**Comment by jesmrec** [comment]
Now it's working fine. Approved on my side

**Pull request merged**
