### PR TITLE
[release/1.0.4] Release 1.0.4

### PR DESCRIPTION
**Pull request by hosy**
PR for next release 1.0.4, will include all fixes and QA findings

Release a new version

## Related Issue
#459 
#462 

#### If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code) 
- [x] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [x] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [x] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [x] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)
- [ ] [mail] inform #marketing about the new release.

#### App:

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [ ] [TRFX] Update translations from transifex branch.
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan -> Not needed, checklist is enough
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

#### If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [x] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [ ] [DIS] Upload the binary to the App Store
- [ ] [DIS] App Store Connect: Trigger release (manually)
- [ ] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [ ] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [ ] [DIS] App Store Connect: Update changelogs
- [ ] [DIS] App Store Connect: Submit for review

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## QA

Task checklist: https://github.com/owncloud/ios-app/pull/466#issuecomment-517644332

Bugs & improvements:

- [X] (1) https://github.com/owncloud/ios-app/pull/466#issuecomment-517651499 [FIXED]

### CODE REVIEW

**Comment by jesmrec** [comment]
QA checklist

- [X] Log headers: check they are present
- [ ] OAuth2: check renewals are correct and transparent for users
- [ ] OAuth2: check flow when token is revoked
- [ ] Upgrade from 1.0.3
- [ ] Upgrade from 1.0.2

**Comment by jesmrec** [comment]
### (1)

1. Swipe over a bookmark of the list
2. Manage
3. Delete offline copies

Current: crash
Expected: no crash

commit `6202984` iOS12

**Comment by felix-schwarz** [comment]
@jesmrec Fixed (1) as of https://github.com/owncloud/ios-app/pull/466/commits/95d564ba85d77dce43501ff61043fe450efbfa41

**Comment by jesmrec** [comment]
(1) fixed.

The remaining checks passed. Approved an my side.

**Pull request merged**
