### PR TITLE
[feature/link-naming] Link naming

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
Adds a `Name` field for link shares, allowing to enter and edit the name of link shares.

## Related Issue
#1246 

## Screenshots (if appropriate):
Create | Edit
----|-----
Bildschirmfoto 2023-11-16 um 18 51 24 | Bildschirmfoto 2023-11-16 um 18 50 08

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by hosy — APPROVED** [review]
Only one comment about the symbol sizing in the views. Does it make sense to use a linear width for all symbols in this view?


Simulator Screenshot - iPhone 15 Pro Max - 2023-11-20 at 12 49 39-2 | Simulator Screenshot - iPhone 15 Pro Max - 2023-11-20 at 12 49 48-2
-- | --

**Comment by jesmrec** [comment]
QA checks (to do in both oC10 and oCIS):

In app:

- [ ] Create name with regular name -> reflected in web
- [ ] Create link with empty name -> reflected in web
- [ ] Create link with very long link name -> reflected in web
- [ ] Create link with name including special characters -> reflected in web
- [ ] Edit link with name (editing the name) -> reflected in web
- [ ] Edit link with name, removing the name -> reflected in web

Remote: 

oCIS web does not allow to change link names, so, i used Android client to test this

- [ ] Create name with regular name -> reflected in iOS app
- [ ] Create new link with name -> reflected in iOS app
- [ ] Create link with very long link name -> reflected in iOS app
- [ ] Edit link with name (editing the name to another different) -> reflected in iOS app
- [ ] Edit link with name, removing the name -> reflected in iOS app

**Comment by jesmrec** [comment]
### (1)

Trying to add a very long name in the link, cursor is not moving to the right when the screen space is over. Check the video out:

Uploading RPReplay_Final1700561163.MP4…

In the same track, editing a name that exceeds the UI field element is complicated. I was not able to move the cursor right and left.

iPhoneXR iOS17.2
`19c88e27`

**Comment by michaelstingl** [comment]
> oCIS web does not allow to change link names, so, i used Android client to test this

Names from additional links can be renamed in ownCloud web with oCIS:

CleanShot 2023-11-21 at 11 07 07@2x

**Comment by jesmrec** [comment]
### (2)

I'm not sure whether this one is client-side or server-side...

If the link name contains the character `;` , is returned as empty name

Request is sent with the correct body:

```
path:        /Dfs2.avi
shareType:   3
permissions: 1
space_ref:   3ffbf849-6ff7-488f-84aa-eba5aba6138b$5004b524-0799-4d9c-bca0-52ce0a1bf1aa!adcb259c-7115-485a-a7af-f021d5ccb8d8
name:        Aaa;
```
and server responses with empty `<name></name>`

Checked with Android client works fine (request in xml format)

I'd say this is a problem in server, but please confirm and i'll open issue there.

**Comment by jesmrec** [comment]
### (3)

Links created with empty name are reflected as `Link` in the iOS app (human readable)

oCIS web, oC10 web and Android client shows the link id (non human-readable)

I'd go for this approach (link id) for consistency across the clients.

iPhoneXR iOS17.2
19c88e27

**Comment by felix-schwarz** [comment]
@jesmrec [968b834](https://github.com/owncloud/ios-app/pull/1297/commits/968b83452864049e59e03f53b631e176e979d3c2) fixes #1, #2 and #3

**Comment by felix-schwarz** [comment]
@hosy Thanks for spotting this! I changed the layout for the roles to match the other options, but kept the link at the wider width, to be in line with non-link shares and to easily tell shares apart from actions and options:

Roles/Permissions matching other options | Links matching avatars
--|--
Bildschirmfoto 2023-11-23 um 12 53 07 |  Bildschirmfoto 2023-11-23 um 12 52 53

**Comment by jesmrec** [comment]
(2) is fixed now!!

**Comment by jesmrec** [comment]
This is approved on my side. 

Will add some extra [tests](https://github.com/owncloud/ios-scenario-testing/blob/master/src/test/resources/io/cucumber/links.feature) to cover link name cases

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
