### PR TITLE
[fix/enable-markup-iOS16] Enabling Markup Mode on iOS 16

### PR DESCRIPTION
**Pull request by hosy**
## Description
Enabling markup mode was broken on iOS 16 because of rearranged navigation bar and toolbar items.

## Related Issue
#1141 

## Motivation and Context
Enable markup mode automatically after selecting the action.

### on a iOS 16 device
- Select action `Markup` on a PDF or Image file
- Markup UI should be visible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Added changelog files for the fixed issues in folder changelog/unreleased

### CODE REVIEW

**Review by felix-schwarz — APPROVED** [review]

**Comment by jesmrec** [comment]
with commit `600936f6`:

Behaviour is correct in iOS15
Behaviour is not correct in iOS16.0 (20A362). Markup mode is not enabled:

https://user-images.githubusercontent.com/14894746/189658154-351050f9-8ffc-4e75-b07e-528db5696f76.MP4

CC @hosy

NOTE: Built with Xcode13.4.1 (latest stable)

**Comment by hosy** [comment]
@jesmrec please can you show me the iOS version number in the simulator, before running the app. I have 4 bar buttons in the toolbar of this screen.

**Comment by jesmrec** [comment]
It's a real device: 

Screenshot 2022-09-13 at 14 21 43

**Comment by hosy** [comment]
@jesmrec please can you test it with the latest commit?

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
