### PR TITLE
[icon_set] Added beta images in AppIcon.appiconset

### PR DESCRIPTION
**Pull request by ChrisEdS**
## Description
Added "beta" logo set to Assets.xcassets

## Motivation and Context
We have launched an official beta test. I think the icon should also show that this is a beta version. At the moment it causes confusion.
__

owncloud_ios_beta_icon-83 5 2x

### CODE REVIEW

**Comment by michaelstingl** [comment]
@ChrisEdS please check definitions for Alpha and Beta:
https://en.wikipedia.org/wiki/Software_release_life_cycle#Stages_of_development

**Comment by pablocarmu** [comment]
What is the status on this PR, should I review it?

**Comment by ChrisEdS** [comment]
It seems we are waiting with the icons until the app is by definition a beta app.

**Comment by hosy** [comment]
We can add another target to the Xcode project, which builds with different icons.

> Can we have different icons for TestFlight builds and the App Store builds? Or should we build future TestFlight builds with another App ID, so testers could install them side-by-side with the production App Store version?

**Comment by michaelstingl** [comment]
> We can add another target to the Xcode project, which builds with different icons.

Yes, different targets seem to be the right way.

**Comment by hosy** [comment]
> > We can add another target to the Xcode project, which builds with different icons.
> 
> Yes, different targets seem to be the right way.

Ok, I can do this.

**Comment by hosy** [comment]
What we can do, if we add a new target, to set a different application identifier for the beta app. So you can install both apps side by side? We discussed this for Android. Does this make sense?

Disadvantage: Testflight build needs to be a different App as the App Store build.

**Comment by michaelstingl** [comment]
> Disadvantage: Testflight build needs to be a different App as the App Store build.

After App Store release, I'd see it as an advantage, that the TestFlight build doesn't mess up your production data…

**Comment by ChrisEdS** [comment]
We have "NEW" icons in this PR https://github.com/owncloud/ios-app/pull/313
Therefor I close this PR.

**Pull request closed without merging**
