### PR TITLE
[feature/sort direction] Allow sorting asc/desc for all sort methods

### PR DESCRIPTION
**Pull request by hosy**
## Description
- Removed sort methods "name (A-Z)", "name (Z-A)"
- Allow sorting for all sort methods (tap on a selected sort methods again, to change the sort order)

If the SegmentControl is displayed instead of the Sort Menu button, you will not see the indicator for Asc/Desc. This is the same behavior like in the Apple Files.App. Tab on a selected segment again, to change the order.

## Related Issue
#470 

## Screenshot

| Sort Name Asc                                                                                                                                                    | Sort Name Desc                                                                                                                                                   |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Simulator Screen Shot - iPhone X - 2019-08-06 at 11 14 00 | Simulator Screen Shot - iPhone X - 2019-08-06 at 11 13 56 |

Simulator Screen Shot - iPhone X - 2019-08-06 at 12 07 45

## How Has This Been Tested?
- Open file list
- Open sort menu
- Tap on sort menu item "name"
- Tap on sort menu item "name" again
- Try the same with the other sort methods
- Chevron indicator will show the sort direction

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jesmrec** [comment]
QA checklist:

- [X] Name asc
- [X] Name desc
- [X] Type asc
- [X] Type desc
- [X] Size asc
- [X] Size desc
- [X] Date asc
- [X] Date desc
- [X] Share asc
- [X] Share desc
- [X] No shares (take name asc)
- [ ] iPad checks

With iPad, a small UI glitch when switching the sort criteria (by tapping on "shared" option). Should the cell size be static, regardless the cell is tapped?

Aug-07-2019 18-29-25

I noticed a couple of details. Not bad behaviours, just not to forget them:

- With more than one bookmark, the sorting method persists in all of them
- With no shares, name ascending is the criteria
- Date criteria is: the closest to now, the most value

**Comment by hosy** [comment]
@jesmrec thank you for finding this glitch. Action was fired twice, which leads to this glitch. Should be fixed now.

**Comment by jesmrec** [comment]
@hosy with commit `8d4e950` i still reproduce the glitch. When you switch to name|shared, the size of the select bar changes

Aug-08-2019 13-46-37

**Comment by hosy** [comment]
@jesmrec ok, I fixed an other problem before. Please give it a new try now. Thank you!

**Comment by jesmrec** [comment]
Glitch of cell size is fixed. As latest detail, i noticed that the labels are ellipsized with (...) when there is no room to set with the arrow, and then, the arrow is not visible. Is it feasible for the bar to be a bit wider?

Aug-09-2019 08-33-02

**Comment by jesmrec** [comment]
Everything fixed.

Approved.

**Pull request merged**
