### PR TITLE
Remove docs folder

### PR DESCRIPTION
**Pull request by mmattel**
This PR removes the `docs` folder,
because the ios documentation has moved to its own repository `docs-client-ios-app`.

### CODE REVIEW

**Review by hosy — CHANGES_REQUESTED** [review]
The file `docs/modules/ROOT/pages/ios_mdm_tables.adoc` is autogenerated by a script from our comments inside the app source code. If we remove the folder, we will loose the autogenerated MDM documentation. The script will be executed by GitHub Actions, automatically for every push and merge. 
https://github.com/owncloud/ios-app/blob/master/.github/workflows/configuration-documentation.yml
For that we need a solution.

**Comment by michaelstingl** [comment]
@hosy needs https://github.com/owncloud/ios-app/issues/1070 first.

**Comment by hosy** [comment]
There is still an open question how we solve the problem with the dynamically created adoc file for the MDM configuration.
Currently every GitHub push triggers an action, which updates the CONFIGURATION.json file and performs a gomplate script, which creates the MDM adoc file.
@mmattel can this single adoc file stay in this repo or can we move the action to your docs repo?

**Comment by mmattel** [comment]
I will answer you tomorrow.

**Comment by hosy** [comment]
Fix will be handled in https://github.com/owncloud/ios-app/pull/1094

**Pull request closed without merging**
