### PR TITLE
[milestone/11.4.4] Milestone 11.4.4

### PR DESCRIPTION
**Pull request by felix-schwarz**
## Description
- adapt SwiftLint rules to mute nonsensical warnings
- fix other SwiftLint warnings in code
- change ShareNavigationController so that a message is shown instead of the picker if no file provider is available
- change OCCore+FPServices to return an error if no file provider is available
- fixed iPad UI on iOS 12 (was empty in version 11.4.3) https://github.com/owncloud/enterprise/issues/4293

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by jesmrec** [comment]
## QA

#### https://github.com/owncloud/enterprise/issues/4293

Fixed. It was tested with an 12.4 iPad simulator. 

#### https://github.com/owncloud/ios-app/issues/843

New option in diagnostics,  `Delete Authentication Data` to clean username/password for any bookmark

- [X] Basic Auth 
- [ ] OAuth2 -> Waiting for server response till bookmark is reopened. Same behaviour as `invalidate login data`
- [ ] OIDC -> Waiting for server response till bookmark is reopened. Same behaviour as `invalidate login data`

#### Others

- [X] Passcode sanity
- [X] File provider sanity test (basic ops, creating and editing with external editors)
- [ ] Smoke test
- [ ] Upgrade from 11.4.3
- [ ] Upgrade from 11.4.2

Devices: iPhoneXR v14.1, iPadAir v13.7
Xcode version: `12.2 (12B45b)`
Server version: 10.5

**Comment by jesmrec** [comment]
### (1)

1. Add an OAuth2/OIDC bookmark (no matter which one)
2.  `Enable Diagnostics` in Settings
3. In bookmark list, Manage > Diagnostic Overview > Bookmark metadata > Delete Authentication Data
4. Open bookmark again and sign in with correct credentials

Current: `Waiting for server response` forever. You have to go back to bookmark list and open again the bookmark to unblock

On the other hand, for OAuth2 and OIDC, the options `invalidate` and `delete` authentication data do the same. Is that correct?

@felix-schwarz

**Comment by felix-schwarz** [comment]
@jesmrec Thanks! (1) was a very interesting, very complex bug. Fixed as of aff8dfa.

**Comment by jesmrec** [comment]
@felix-schwarz problem is fixed for OAuth2/OIDC bookmarks. In case of basic auth, after the fix the options `Invalidate` and `Delete` do the same: asking only for the password. That means, the `Delete authentication data` is not removing the username, or not asking for it.

**Comment by felix-schwarz** [comment]
@jesmrec Bookmarks now also save the username for bookmarks that were created or edited (via `Edit`) since the change, so that for those it will only ask for the password.

For bookmarks last created or edited with a previous version, deleting the auth data continues to ask for both.

That change turned out to be necessary to ensure paths to the WebDAV endpoint can always be constructed correctly.

**Comment by jesmrec** [comment]
thanks for the clarification. the expected behaviour is correct, then.

**Comment by jesmrec** [comment]
Version approved on my side

- Approved commits:

  - App: `aff8dfa3`
  - SDK `123dd5b`

- Xcode version: 12.2 (12B45b)

- Devices used:

  - iPhoneXR, iOS 14.1
  - iPadAir, iPadOS 13.7

**Review by hosy — APPROVED** [review]

**Pull request merged**
