### PR TITLE
[feature/corporate-design] Corporate Color + UI Refinements

### PR DESCRIPTION
**Pull request by hosy**
## Description
The corporate color of the UI themes was updated and furthermore some colors was adopted for a better contrast.
Furthermore the following images was updated with the new corporate color values:
- Splash screen background image
- App Icon (regular and EMM-App)

This PR includes also some UI Refinements:
- Alignment of the `More` button in the navigation bar and the `Select` button in sort bar with the position of the `More` button in the item cell
- Moved `Sort Popover` some pixels to the left to prevent to see some pixels from item cell icons in the background
- Aligned `Sort Direction Arrow` in `Sort Popover` to the right
- Fixed unselected tab bar items contrast

## Related Issue
#860 

## Motivation and Context
Update UI to the correct corporate color and refine UI design

## Screenshots (if appropriate):

Simulator Screen Shot - iPhone 12 - 2021-01-14 at 14 19 25

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by felix-schwarz — APPROVED** [review]

**Comment by jesmrec** [comment]
About the fixes done here:

> Alignment of the More button in the navigation bar and the Select button in sort bar with the position of the More button in the item cell 

👍 

> Moved Sort Popover some pixels to the left to prevent to see some pixels from item cell icons in the background

is it moved to the right, right? 

> Aligned Sort Direction Arrow in Sort Popover to the right

👍 

> Fixed unselected tab bar items contrast

👍

**Comment by jesmrec** [comment]
Some colors changed. Changes after appyling new themes or anything is missing? here are the changes:

- Dark theme: blue color in sort menu

|Before | Current |
|:-:|:-:|
|Screen Shot 2021-01-15 at 12 33 37|Screen Shot 2021-01-15 at 12 27 24|


- Classic theme: blue color in sort menu

|Before | Current |
|:-:|:-:|
|Screen Shot 2021-01-15 at 12 34 15|Screen Shot 2021-01-15 at 12 30 25|


- Light theme: blue fonts in navigation, sort menu, multiselection menu, action card items and bottom bar selection items tuned to black.

|Before | Current |
|:-:|:-:|
|  Screen Shot 2021-01-15 at 12 41 14|Screen Shot 2021-01-15 at 12 27 54|


- Contrast is not correct in downloads view (light & classic themes). Background should not be black

Screen Shot 2021-01-15 at 12 50 05

**Comment by hosy** [comment]
@jesmrec all your findings are fixed! 
Note: Light blue color might be changed after PR was approved.

**Comment by jesmrec** [comment]
Everything fixed

Approved

**Review by jesmrec — APPROVED** [review]

**Pull request merged**
