### PR TITLE
[feature/filelist-layout] Cleaner File List Layout

### PR DESCRIPTION
**Pull request by hosy**
## Description
Changed file list cell layout to get more space for the filename and more aligned icons, less jumpy

## Motivation and Context
As you can see on the screenthos below, there are more space for file names and the icons for state shared, link is no longer jumpy behind the file name.

| Before Changes                                                                                                                                                        | After Changes                                                                                                                                                         |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Simulator Screen Shot - iPhone 11 Pro - 2020-01-13 at 12 07 07 | Simulator Screen Shot - iPhone 11 Pro - 2020-01-13 at 13 50 40 |
| Simulator Screen Shot - iPhone 11 Pro - 2020-01-13 at 12 06 59 | Simulator Screen Shot - iPhone 11 Pro - 2020-01-13 at 13 52 18 |

## How Has This Been Tested?
- Open file list
- check layout of the icons
- change state of shared, public link

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

____

QA

Test Plan:

https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%201.3.0/New%20List%20Layout.md

BUGS & IMPROVEMENTS:

- [ ] (1) Marks at the right https://github.com/owncloud/ios-app/pull/594#issuecomment-576247312

### CODE REVIEW

**Comment by jesmrec** [comment]
### (1) (idea of improvement)

The marks (not downloaded, private/public share, av. offline) are set at the left inside the second row. 

By checking other clients and the web UI, the marks are always set at the right. Would be a good idea to move them to the right? or would you prefer to iterate and get feedback of this implementation first? for me both are OK, just an UX idea.

CC @michaelstingl

**Comment by hosy** [comment]
@jesmrec @michaelstingl we should discuss this with @wuenschedesign

**Comment by michaelstingl** [comment]
> would you prefer to iterate and get feedback of this implementation first?

works for me

**Comment by jesmrec** [comment]
> works for me

all tests on my sides passed. So, if (1) is not going to be done, it can be moved forward.

**Comment by hosy** [comment]
@jesmrec cool, please approve it and add your label.

**Pull request merged**
